### ISSUE TITLE
Get-CrmRecordsByViewName does not always return all columns in the view

### ISSUE THREAD

**Issue by bemuel** [seanmcne/Microsoft.Xrm.Data.PowerShell#111]
When the FIRST record in the view does not contain a value in one of its columns, that column will NOT be included in the resulting Export using Get-CrmRecordsByViewName

If the FIRST record in a view does have a value for a specific field, that column WILL be included in the resulting PowerShell export

The only workaround I have found is to open the first record in the desired view and be sure it has values for the desired fields of the columns I wish to include in the export

**Comment by kenakamu** [comment]
You are absolutely right. What we can do here is to create record with all attribute by using view metadata. Let me think how I can do so.

**Comment by kenakamu** [comment]
I am so sorry to taking too much time. The only solution I can think of right now is to get metadata, but it neglect performance. Do you think we should always check all metatada to include null column or give option to check, like Get-CrmRecordByViewName -GenerateNullColumn?

**Comment by kenakamu** [comment]
fixed
