### ISSUE TITLE
Import-CrmSolution always returns success (CRM 2016 OnPremise)

### ISSUE THREAD

**Issue by urswi** [seanmcne/Microsoft.Xrm.Data.PowerShell#114]
Hi

as I am trying to write solution automation scripts for solution export and import, I faced a strange behaviour when using the Import-CrmSolution command. (Using CRM 2016 OnPremise - 8.0.0.1088)

The import works totally fine when the solution produces no errors at all and it's not an upgrade solution. As soon as the solution has missing webresources (shown when I try to import it manually) or the solution should upgrade the previous one (Patch-Feature behaviour), the solution import is not working. Unfortunatelly there is no error or warning shown on the powershell command line.

Is this an issue or am I doing something wrong?

Used Command:
`Import-CrmSolution -SolutionFilePath $solManaged.SolutionPath -ActivatePlugIns -conn $connectionTarget -OverwriteUnManagedCustomizations -PublishChanges`

Output (always):
`You are now connected to: Playground2
For a list of commands run: Get-Command -Module Microsoft.Xrm.Data.Powershell
Importing solution file D:\PowerShellCrmSamples\CustomSolution_Test_managed_1_5_2_0.zip into: http://crmplayground:5555/Playground2/XRMServices/2011/Organization.svc
Import of file completed, waiting on completion of importId: 46cbf644-59e4-42d9-b2dc-09a494689dd9
Import of managed solution complete.`

Kind regards
Urs

**Comment by seanmcne** [comment]
Hi Urs - thanks for reaching out!  Here's a quick script you can run to diagnose the import - it will export the xml file for every solution import you've done - then each xml file can be used to troubleshoot what component may be failing.  Once you find why it failed let Ken and I know and we'll try to put some smarter detection within the import-crmsolution.  Thx! 

$results = Get-CrmRecords -EntityLogicalName importjob -FilterAttribute solutionname -FilterOperator not-like -FilterValue "activityfeeds" -Fields solutionname,progress,startedon,completedon,data -AllRows
$FileInfoToWrite = @()
foreach ( $record in $results.CrmRecords ) 
{
    $fileNameForData = "$(([DateTime]($record.startedon)).ToString("yyyyMMdd_hhmmss")))_$($record.solutionname).xml"  
    $record.data > $fileNameForData
    $duration = ($record.completedon_Property.Value - $record.startedon_Property.Value).ToString();
    $FileInfoToWrite+= New-Object PSCustomObject -Property @{
        "FileName" = $fileNameForData
        "SolutionName" = $($record.solutionname) 
        "Progress" = $($record.progress)
        "StartedOn" = $($record.startedon)
        "CompletedOn" = $($record.completedon)
        "Duration" = $duration
    }
}
$FileInfoToWrite|Export-Csv SolutionDumpReport.csv -NoTypeInformation

**Comment by albernhagen** [comment]
I'm seeing similar behavior with CRM Online 2016.  I run the import solution and it says everything succeeds, but my solution never actually deploys/updates in the target environment.  Any ideas of what I could try to resolve this?  I would also like to automate our deployments of solutions.

**Comment by urswi** [comment]
The exported report shows a missing dependency error - I think this is not handled in the correct way within import-crmsolution:
<MissingDependencies><MissingDependency><Required key="22" type="61" schemaName="uwi1_testtest2.js" displayName="uwi1_testtest2.js" solution="Active" /><Dependent key="6" type="60" displayName="Account" parentDisplayName="Account" id="{8448b78f-8f42-454e-8e2a-f8196b0419af}" /></MissingDependency></MissingDependencies>

**Comment by chamindac** [comment]
I have experienced the same issue and made a fix and it seems to be working fine for me now. it really fails on a failure import. Made a pull request #118  with another enhancement to support hold mode solution import and promote the solutions, imported with a hold

**Comment by kenakamu** [comment]
Sean, please look into this.

**Comment by seanmcne** [comment]
Already commented on the commit - need some add'l documentation for the help file but as long as we feel we can rely on the percent completed as an indicator that should work.  That said, we can also analyze the xml file output looking for failures - if the percentage is reliable that's the easier fix (for now).

**Comment by devbeard** [comment]
In CRM 2011/2013, percentages were not always reliable as an indicator if import succeeded for on premise. If you have many import jobs, just take a select on the table (or fetchXml it) to see lots of 98.99% with a successful import.

We have chosen to use the status code of the asyncoperation instead of the progress percentage of the importjob, and our deployment tasks poll this status for until it changes or timeout.

This is C#, but the concept (to get my intent across) should be similar for PS:

    while (timeout > DateTime.Now)
                    {
                        try
                        {
                            var operation = targetService.Retrieve("asyncoperation", asyncJobId,
                                new ColumnSet("asyncoperationid", "statuscode", "message"));

                            var job = targetService.Retrieve("importjob", importJobId,
                                new ColumnSet("solutionname", "progress"));

                               progress = (double)job["progress"];
                                LogMessage(progress.ToString("F"));

                            var statusCode = operation["statuscode"] as OptionSetValue;

                            if (statusCode != null)
                            {
                                var stopProcessing = false;

                                switch (statusCode.Value)
                                {
                                    // Success
                                    case 30:
                                        LogMessage("Import completed at " + DateTime.Now.ToString("s"));
                                        stopProcessing = true;
                                        solutionProcessingCompleted = true;
                                        break;
                                    // Failure conditions
                                    case 21:
                                    case 22:
                                    case 31:
                                    case 32:
                                        throw new DeployTaskException("Import failed: " + operation["message"]);
                                }

                                if (stopProcessing)
                                {
                                    // break out of loop                                    
                                    break;
                                }
                            }
                        }
                        catch (FaultException<OrganizationServiceFault> exception)
                        {
                            LogMessage(exception.Message);
                        }
                        catch (Exception exception)
                        {
                            LogMessage(exception.Message);
                        }

                        Thread.Sleep(2000);
                    }

**Comment by devbeard** [comment]
There is a problematic IF block in the function Import-CrmSolution. The check for completion is:
**`if($import.completedon -eq $null -and $importManifest.result -ne "success"){`**

If this does not evaluate to true, it will print "Processing completed" and exit. However, the field "completedon" is set to a date and time for both failues and successes, so the check simply checks if the import is stopped, not successfully completed. 

To fix this, and to get the success/failure status, the import process has to check either in the data XML for an errortext != "", or (much simpler) run the import as an async request. This will create a asyncoperation entry with a status code of 30 if successful and 31 if failed. The error messages are also quite readable, for example the one below which reads **`Assembly must be registered in isolation.`**.

	Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Plugin Assemblies import: FAILUREDetail: 
	<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
	  <ErrorCode>-2147188685</ErrorCode>
	  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
	  <Message>Plugin Assemblies import: FAILURE</Message>
	  <Timestamp>2016-07-22T10:24:42.3911082Z</Timestamp>
	  <InnerFault>
		<ErrorCode>-2147188685</ErrorCode>
		<ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
		<Message>Plugin Assemblies import: FAILURE</Message>
		<Timestamp>2016-07-22T10:24:42.3911082Z</Timestamp>
		<InnerFault>
		  <ErrorCode>-2147220906</ErrorCode>
		  <ErrorDetails xmlns:d4p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
		  <Message>Action failed for assembly 'Demo.Crm.Activities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97163e06cc655f88': Assembly must be registered in isolation.</Message>
		  <Timestamp>2016-07-22T10:24:42.3911082Z</Timestamp>
		  <InnerFault i:nil="true" />
		  <TraceText i:nil="true" />
		</InnerFault>
		<TraceText i:nil="true" />
	  </InnerFault>
	  <TraceText i:nil="true" />
	</OrganizationServiceFault>
	   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode)
	   at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
	   at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)

**Comment by albernhagen** [comment]
I just wanted to share what we ended up doing with our solution.  We're automating our builds/deploys so we're regularly importing the same unmanaged solution into an environment, so I needed to expand upon the earlier PowerShell suggestion.  Here's what I came up with.

`$fetch = @"
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="true" page="1" count="1" no-lock="true">
  <entity name="importjob">
    <attribute name="solutionname" />
    <attribute name="progress" />
    <attribute name="startedon" />
    <attribute name="completedon" />
    <attribute name="data" />
    <order attribute="startedon" descending="false" />
    <filter type="and">
      <condition attribute="solutionname" operator="eq" value="$($solutionName)" />
    </filter>
  </entity>
</fetch>
"@

$results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch
$FileInfoToWrite = @()
foreach ( $record in $results.CrmRecords ) 
{
	$fileNameForData = "Solution_$($record.solutionname).xml"

	$record.data > $fileNameForData
	$duration = ($record.completedon_Property.Value - $record.startedon_Property.Value).ToString();
	$FileInfoToWrite+= New-Object PSCustomObject -Property @{
		"FileName" = $fileNameForData
		"SolutionName" = $($record.solutionname) 
		"Progress" = $($record.progress)
		"StartedOn" = $($record.startedon)
		"CompletedOn" = $($record.completedon)
		"Duration" = $duration
	}
}
$FileInfoToWrite|Export-Csv SolutionDumpReport.csv -NoTypeInformation

[xml]$XmlDocument = Get-Content Solution_$solutionName.xml
$result = $XmlDocument.importexportxml.succeeded
Write-Output "Solution Result: " $result
if ([String]::IsNullOrWhitespace($result) -or $result -eq "failure") {
	Write-Error "Solution import failed.  Review below XML file for details."
	Get-Content Solution_$solutionName.xml
	exit -1
}`

**Comment by seanmcne** [comment]
I have now completed the integration of the changes submitted a long while back.  Now that we've had it tested out it should be good to proceed.  To continue helping out with solutionImport timeouts I've added an async import option and added a switch to trigger an async import via the regular import function (to allow for an easy bypass from timeouts).  Please take a look as I'm open to changing it around or altering how the commands operate. Feel free to test it out and give more feedback!  Thanks again for the great work & testing everyone!
