### ISSUE TITLE
Support for Corporate Proxy

### ISSUE THREAD

**Issue by albernhagen** [seanmcne/Microsoft.Xrm.Data.PowerShell#117]
Any chance you could build in support for a corporate proxy?

**Comment by kenakamu** [comment]
Our connection fully depends on XrmTooling. So if XrmTooling get through your proxy, it does, otherwise it doesn't.

**Comment by seanmcne** [comment]
@albernhagen is it not using the windows proxy settings?

**Comment by albernhagen** [comment]
Sorry for the delay, guys.  Ours does use the windows proxy settings, but we're looking to utilize these scripts on our build servers where we want to override the windows proxy settings.  Is there anyway around it?
