### ISSUE TITLE
Not possible to use default credentials

### ISSUE THREAD

**Issue by devbeard** [seanmcne/Microsoft.Xrm.Data.PowerShell#126]
As far as I can tell, there is no way to tell the commandlets to use default network credentials, thus barring unattended usage. It is considered bad practice to write username and password in clear text in the scripts using the module, to pass credentials. 

I know this is listed in the code as a known thing, but it would be a great enhancement to have it run as the current user when credentials are null or a switch is set.

**Comment by seanmcne** [comment]
@devbeard it's my understanding the CRM Dev team (who owns/writes the powershell connection library) do not allow default credentials for security reasons.  When using powershell you can securely store your passwords using a securestring like this mentions: http://social.technet.microsoft.com/wiki/contents/articles/4546.working-with-passwords-secure-strings-and-credentials-in-windows-powershell.aspx 

All of these various scripts are using a psCredential with secure string in combination with: ConvertTo-SecureString and ConvertTo-SecureString to store it.  

Quote from: https://technet.microsoft.com/en-us/library/hh849814.aspx 
>The ConvertFrom-SecureString cmdlet converts a secure string (System.Security.SecureString) to an encrypted standard string (System.String). Unlike a secure string, an encrypted standard string can be saved in a file for later use. The encrypted standard string can be converted back to a secure string by using the ConvertTo-SecureString cmdlet. 
> If an encryption key is specified by using the Key or SecureKey parameters, the Advanced Encryption Standard (AES) encryption algorithm is used. The specified key must have a length of 128, 192, or 256 bits, because those are the key lengths supported by the AES encryption algorithm. If no key is specified, the Windows Data Protection API (DPAPI) is used to encrypt the standard string representation.

If you're using Powershell workflow or azure automation my understanding is that these enviornments will allow you to save and re-use passwords securely as well.

**Comment by devbeard** [comment]
Thanks @seanmcne. For security reasons PowerShell doesn't expose the data of the security context, and that is great. It doesn't mean we can't use the context. In my case I wanted to put some CRM automation inside of a TeamCity build step, and I think I have found a tiny extension of your code for people who need it. I can of course submit a pull request (if this would be something the library would accept). For now I have just locally extended the module and it is working as I wanted it to.

Your module uses the Get-CrmConnection command from the Microsoft.Xrm.Tooling.CrmConnector.Powershell.dll, which also accepts a connection string parameter in addition to what the module currently uses. If a connection string simply is given as: `"Url=https://crm.mydomain.com/OrganizationName"` the SDK will connect using the default network credentials. 

I have tested this locally (5 additional lines of code) and it works for my scenario, but someone else would have to look at it to see if it "breaks" something else, somewhere else. It doesn't exactly take a connection string, which I would prefer, but instead builds it if `Credential -eq $Null`. In this specific function, if the credentials are not supplied, we only have server URI and organization, so this connection string is the extent of what can be achieved.

    elseif($Credential -eq $Null)
	{		
		# Default to using connection string if no credentials are supplied
		$cstr = "Url=$ServerUrl$OrganizationName;"		
		$global:conn = Get-CrmConnection -ConnectionString $cstr
		Write-Verbose "You are now connected and may run any of the CRM Commands."
		return $global:conn;
	}

My apologies for my lack of PowerShell knowhow. I tend to live in C# land :smile:

**Comment by Badajoz95** [comment]
FYI, Rather than wanting to update the framework, I actually used 
`New-Object Microsoft.Xrm.Tooling.Connector.CrmServiceClient -ArgumentList "Url=$($crmUrl)"`
which got me around the issue of wanting to use default credentials.
