### ISSUE TITLE
new-crmrecord should accept a crm record object as an input

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#132]
To support 'copying' or 'cloning' a record new-crmrecord should accept a previous record object as an input (select out a record, alter some properties, then call create w/ that object).  The ID param should be allowed and set to the records id - however, if it's a dup that will throw an exception.  The script writer would be expected to null out the ID before calling new-crmrecord.

**Comment by kenakamu** [comment]
Got it.

**Comment by kenakamu** [comment]
Just checking with you if upsert works instead of adding new parameter for New-CrmRecord?

**Comment by seanmcne** [comment]
I wouldn't expect a new parameter at all - upsert would work but if new-crmrecord is passed a crmrecord it should try to insert it with that GUID provided.  If the GUID provided is a dup we should throw the exception back from CRM.  If the GUID is empty or missing, then we should clear it and create it.  

It would be nice to simply retrieve a record, update an attribute or add an attribute and call set-crmrecord without extra effort and in the same way I could call new-Crmrecord and create one (even if it throws an exception. 

$rec = get-crmrecord -id {GUID} -EntityTypeName "Account"
$rec.id = $null 
new-crmrecord $rec #success 

$rec = get-crmrecord -id {GUID} -EntityTypeName "Account" | new-crmrecord #throwException of duplicate record most likely

**Comment by seanmcne** [comment]
@kenakamu do you think we'll be able to get this into 2.6?  We should probably try to get a release out soon as it's lagged for a while here and we've got some good bug fixes.

**Comment by kenakamu** [comment]
I am adding new parameter for New-CrmRecord -CrmRecord $record. There are several challenge like how we handle "address" which only 1 address can be assigned even though it is N:1. I will add it anyway to see how it goes.

**Comment by kenakamu** [comment]
Done
