### ISSUE TITLE
Get-Records issues warning on custom entity names

### ISSUE THREAD

**Issue by mattp65** [seanmcne/Microsoft.Xrm.Data.PowerShell#136]
When calling Get-Records with Verbose logging, warning is shown saying entity name contains upper case characters even when the name is all lower case.  RegEx isn't looking for _ in name.

**Comment by kenakamu** [comment]
Thanks for report. I will look into this.

**Comment by seanmcne** [comment]
Regex match can be updated to: "^[a-z_]*$" on @ line 2922 which includes an underscore, I wouldn't suggest getting any more "fancy" for validation, since it's just a casing check.

**Comment by kenakamu** [comment]
fixed.
