### ISSUE TITLE
Get-CrmConnection parameter is wrong

### ISSUE THREAD

**Issue by kenakamu** [seanmcne/Microsoft.Xrm.Data.PowerShell#141]
ServerUrl -> ServerUri

**Comment by seanmcne** [comment]
Ken, I don't see this as a bug - get-crmconnection's param is ServerUrL 

![image](https://cloud.githubusercontent.com/assets/2292260/21197325/b1b2616c-c200-11e6-949a-0487ab5ebf1d.png)

**Comment by kenakamu** [comment]
okay! then I close this.
