### ISSUE TITLE
Add  user to several Teams

### ISSUE THREAD

**Issue by bermudas** [seanmcne/Microsoft.Xrm.Data.PowerShell#143]
Hi All,
could you please hint me with the idea if it's possible to add a team to a user (so that user had a couple of teams aligned, not just the default one from Busines unit).
I was actually trying to do that by 

$sql_fin_protected=@"
select teamid from  TeamBase where Name='Financial Protected Team'
"@

$NewSequenceID = invoke-sqlcmd -ServerInstance "localhost" -Database "Org_mscrm" -Query $sql_fin_protected
$teamid_fin_protected=$NewSequenceID.teamid.ToString()

$user='Someuser'
$sql=@"
declare @domname AS VARCHAR(100)
set @domname='$domain\$user'
select systemuserid from SystemUser where domainname=@domname
"@
$NewSequenceID = invoke-sqlcmd -ServerInstance "localhost" -Database "Org_mscrm" -Query $sql
$userid=$NewSequenceID.systemuserid.ToString()
Add-CrmRecordAssociation -EntityLogicalName1 team -Id1 $teamid_fin_protected -EntityLogicalName2 systemuser -id2 $userid -RelationshipName teammembership_association

But it doesn't look like doing the job.... probably I was doing something wrong

**Comment by bermudas** [comment]
issue appeared to be in my script values of Guid. SOrry for inconvenience.

**Comment by kenakamu** [comment]
no worries,
I encourage you to write everything with our powershell command so it should work in Online environment too!

**Comment by bermudas** [comment]
Sure, completely agree with you. I'm just getting started....
