### ISSUE TITLE
FecthXML Count not restricting resultset

### ISSUE THREAD

**Issue by mattp65** [seanmcne/Microsoft.Xrm.Data.PowerShell#144]
Adding COUNT="n" to a FetchXML query doesn't restrict the result set.

**Comment by kenakamu** [comment]
Could you give the script you run?

**Comment by mattp65** [comment]
$fetchxml = @"
<?xml version="1.0"?>
	<fetch distinct="false" version="1.0" output-format="xml-platform" mapping="logical" count="2">
	  <entity name="account">
		<attribute name="name"/>
		<order attribute="name" descending="false"/>
	  </entity>
	</fetch>
"@

$crmServerList = Get-CrmRecordsByFetch -Fetch $fetchxml -conn $crmConn

$crmServerList.CrmRecords.Count

When running this, I get all Accounts returned.  Same query when run via C# or any of the FetchXML test utilities returns 2 records as expected.

**Comment by kenakamu** [comment]
Thanks.
I repro the issue. This is interesting issue that I will fix it in next release. The cause is underlying CrmServiceClient has method GetEntityDataByFetchSearch which has two argument overload. We are using more detail one but it ignores count in fetch as it expect to separately set top.

I will check if FetchXML contains count and pass it accordingly.

Meanwhile if the query is simple enough, then try using Get-CrmRecords with -TopCount please.

**Comment by mattp65** [comment]
Hmmm, using the following does work:
`$crmServerList = Get-CrmRecordsByFetch -Fetch $fetchxml -conn $crmConn -TopCount 2
`
Hadn't noticed the -TopCount parm previously as was used to using it inside the FetchXML itself.

Be good to have the stock support there, but this is it at least is an alternative.  I was trying to use some conditional code that just used different FetchXML based on conditions which just means some other changes to include the -TopCount parm.

That said, in looking at the SDK doc for GetEntityDataByFetchSearch, it really isn't TopCount, but PageCount that is being sent.  While a slight difference, they do behave differently in SQL and other processing as PageCount triggers the logic for paging, while COUNT doesn't.  A better choice might be to conditionally call the different overloads based on which parms are supplied (and rename TopCount to PageCount to match SDK).  Since you are triggering that overload explicitly, it is assuming all paging parms are included and thus ignoring the COUNT in the XML since the paging directive is seen as overriding it.

**Comment by seanmcne** [comment]
Hey Matt, I agree on the naming it should probably match the terms used in other places (pageCount/pageNumber).  The function we're calling is wrapping this one here https://msdn.microsoft.com/en-us/library/dn742141.aspx which ultimately overwrites these values. 

We could look to determine if there is no pageCount, pageNumber, and pageCookie we could use the second constructor:  https://msdn.microsoft.com/en-us/library/dn699708.aspx 

This appears to skip the "help" and just submits the fetchxml directly. Unfortunately this isn't just the sdk calls - it's using the tooling connector underneath which has some 'special' methods that behave slightly different.

**Comment by mattp65** [comment]
Totally understand that the tooling connector is playing some games here.  I also get that overloads in PS aren't as easy as C#.  I would vote for something like this though to put usability "in line" with the tooling connector to eliminate another layer of gaming.

`if ($PageCount -or $PageNumber -or $PageCookie) {
    if($PageNumber -eq 0)
    {
        $PageNumber = 1
    }
    $PagingCookie = ""
    $NextPage = $false
    if($PageCookie -eq "")
    {
        $PageCookie = $null
    }
    $records = $conn.GetEntityDataByFetchSearch($Fetch, $PageCount, $PageNumber, $PageCookie, [ref]$PagingCookie, [ref]$NextPage, [Guid]::Empty)
}
else {
    $records = $conn.GetEntityDataByFetchSearch($Fetch, [Guid]::Empty)
}
`
I ran a quick test on my side and this seems to work as expected with the 2nd (simpler) constructor.

**Comment by seanmcne** [comment]
Completely agree @mattp65. 

@kenakamu one suggestion, let's create a random new Guid and verbose log it.  If the caller wants to log the request ID for support purposes this gives them some ability to help out support (if that's needed).  Replace [Guid]::Empty with --> [System.Guid]::NewGuid()  then log it out. Also since we've got the import solution branch in flight let's be mindful of that so as not to cause merge conflicts :)

**Comment by kenakamu** [comment]
fixed. For Guid issue, we need to open new issue to track it separately.
