### ISSUE TITLE
Way to assign lookup fields.

### ISSUE THREAD

**Issue by bermudas** [seanmcne/Microsoft.Xrm.Data.PowerShell#146]
Hi
could you please help me to understand if there are any ways to assign lookup fields values?

$Custom_entity=New-CrmRecord -EntityLogicalName Custom_entity -Fields @{"custom_name"="Test";"custom_source"="Source";
"description"="test"}
Write-Output $Custom_entity.Guid
$another_customentity =New-CrmRecord -EntityLogicalName another_customentity -Fields @{"custom_name"="test";"Custom_entityid"= $Custom_entity.Guid}

Custom_entityid is not getting the value... am I doing something wrong?

**Comment by kenakamu** [comment]
Try using New-CrmEntityReference. You can see sample by Get-Help New-CrmRecord -examples

**Comment by seanmcne** [comment]
Going to close this out as it appears to be more discussion around capabilities.
