### ISSUE TITLE
Get-CrmRecords does not throw error on bad field name

### ISSUE THREAD

**Issue by mattp65** [seanmcne/Microsoft.Xrm.Data.PowerShell#148]
The tooling wrapper doesn't throw an exception when a bad attribute name is provided.  For example:

`Get-CrmRecords -EntityLogicalName 'account' -Fields 'xaccountnumber' -conn $crmconn`

While there is info in LastCRMError, there is no way to clear that ahead of time since it's a read-only property on the connection so there is no way to accurately determine that an error occurred on the call.

**Comment by seanmcne** [comment]
Hey Matt, a member of our pg has mentioned that this property is cleared every time there is a server side interactions. He said you can assume that this is cleared each time so after an action of there is am error that error was thrown during the prior operation.  Are you not seeing that happen?

**Comment by mattp65** [comment]
I guess it does....kept testing error conditions so I hadn't noticed it got cleared on success.  Makes for complicated code though when you have to explicitly check after a call that in other scenarios would throw an exception.  It is basically forcing a model that assumes ErrorActionPreference = SilentlyContinue.  Seems like if the wrapper  checked the return code and issued a Throw, then the code becomes responsible for handling it w/o having to put code everywhere explicitly to check it.

A similar check for error was done in New-CrmRecord.

**Comment by seanmcne** [comment]
FWIW I agree :) but it is in the core product connection that this pattern is used. I'll see if I get a chance to talk with Matt this week as I am not sure what the longer term plan is with error handling and the core powershell connection library. I think it would be good to always assume an exception would be thrown when something fails rather than having some cases where checking the last error is needed and other cases have an exception thrown.

**Comment by mattp65** [comment]
Yeah, the tooling wrapper is inconsistent compared to how core SDK code works (and doc is pretty limited on how it works).  Adding the IF check below in Get-CrmRecordsByFetch mirrors core SDK behavior (and is similar to what you guys added to New-CrmRecord.  This at least puts the pattern into the common call and eliminates the need to write for it.  Otherwise, I'm going to end up writing a separate wrapper for both functions just to do this same check.

```
$records = $conn.GetEntityDataByFetchSearch($Fetch, $TopCount, $PageNumber, $PageCookie, [ref]$PagingCookie, [ref]$NextPage, [Guid]::Empty)
if ($conn.LastCrmException -ne $null) {
  throw $conn.LastCrmException
}


```

**Comment by seanmcne** [comment]
@kenakamu - do you think we're Ok in assuming lastCrmException is cleared every single time we execute an operation?

**Comment by kenakamu** [comment]
That's my understanding.
