### ISSUE TITLE
Write-Warning messages should be removed

### ISSUE THREAD

**Issue by mattp65** [seanmcne/Microsoft.Xrm.Data.PowerShell#150]
There are "warnings" generated during Get operations that aren't true "warnings" and should be removed.  They cause confusion when interpreting script output as real Warnings can get lost.  Examples include:

WARNING: PERFORMANCE: $FilterAttribute $FilterOperator $FilterValue were not supplied, fetching all records with NO filter.
WARNING: PERFORMANCE: All rows were requested instead of the first 5000
WARNING: No Result

When being called from within a scripted process, these serve no value.  At a min, a Switch parm should be added to suppress these or convert them to Write-Verbose.

**Comment by seanmcne** [comment]
Hey Matt, 
This seems reasonable, the perf warnings are there for obvious reasons but we should be able to assume people know what they're getting into :) 

We'll look to update to write-information or write-verbose.  Thanks!

**Comment by seanmcne** [comment]
Matt, this just occurred to me today.  Have you tried suppressing the warnings for this cmdlet/function?   This would accomplish what you're looking for, I believe (if suppressing with a param is an option). 

Like this: -WarningAction SilentlyContinue

![image](https://cloud.githubusercontent.com/assets/2292260/21196515/79ecbc26-c1fd-11e6-8d69-94cec8e14f29.png)

**Comment by seanmcne** [comment]
@mattp65 just checking in to see if the suppress option works for you. 

@kenakamu any of your powershell buddies have an opinion on 'warnings'?  From a purist standpoint I'd think we should probably suppress by default however it's nice to know if you got 'no results' from a query. Thoughts?

**Comment by kenakamu** [comment]
or we may be able to put it to verbose option? Not sure how many people already relying on this.

**Comment by amervitz** [comment]
I think the PERFORMANCE warnings are beneficial because they're showing there's an alternate recommended usage, especially for new users who wouldn't see them if they were only shown via verbose. I agree the final 'No result' message is a good candidate for verbose - the return value is already an indicator of whether there were any results.

**Comment by mattp65** [comment]
From the standpoint of a larger script, supressing "could" work, but kind of violates the concept behind PowerShell because then if I want Warnings, they would be totally hidden in these calls no matter what or I would have to put complex handling around every call to pass in the Warning setting based on what came into the parent routine. Warning are suppossed to about about something that "might" be wrong, in this case, nothing is wrong and it is 100% what is expected.

Do other query modules "warn" you if you don't use a filter? No.  The problem with catering to the "new user" is they become frustrated quickly with those warnings when they are no longer a "new user". PowerShell is dev work in the end and there is a little "buyer beware" that comes with any dev work.

**Comment by kenakamu** [comment]
@mattp65 what you said here makes sense to me. The reason why we put it there is to let people aware performance issue as @amervitz  mentioned. 

Only thing I need to understand or get agreement from others here is that what kind of thing we should "warn" then? Error is error when something went wrong, but do you have some example of "warning"? 

Personally I am happy to remove the warning we are discussing in this thread but I would like to have same level of consistency across the module.

**Comment by kenakamu** [comment]
confirmed this is change in PR 171.
@seanmcne  please separate PR for separate issue in the future so that it is easier to track issue :)

**Comment by seanmcne** [comment]
@kenakamu - I believe the request was to write all current warnings (at least ones that aren't truly warnings) as verbose.  Have we confirmed full coverage in PR171 of Get-CrmRecords, Get-CrmRecord, Get-CrmRecordsFetch, etc?
