### ISSUE TITLE
Add share/unshare record

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#151]
Still investigating the appropriate verb but placing this here for comments and tracking.

**Comment by seanmcne** [comment]
Proposing based off of https://msdn.microsoft.com/en-us/library/hh547423.aspx 

Grant-CrmRecordAccess
Revoke-CrmRecordAccess
Modify-CrmRecordAccess 

Also need to consider querying a crm records current shares and modifying.  We could start with grant/revoke/modify for now.

**Comment by amervitz** [comment]
I would be interested in implementing these.

**Comment by seanmcne** [comment]
Thanks! Go ahead and script them up :) I was looking at this recently and I'm thinking this could get a little complicated as the accessRights are bitwise'd together Read|Write|Delete (C#) but in Powershell I'm not 100% sure how "usable" this will be for an admin. 

We may consider using params and abstracting that from the user (at least for grantAccess). 
-Read
-Write

**Comment by amervitz** [comment]
Thanks. I'll keep the usability in mind as I work on this and will be sure to request a pull request review to get your feedback.

**Comment by amervitz** [comment]
How should help comments be authored? It appears existing help has been written with [PowerShell Cmdlet Help Editor](https://pscmdlethelpeditor.codeplex.com/) but when I use it the xml help file appears to not have been updated in a while and I have to increment the module version number plus other changes get added beyond what I'm making. Comment-based help would be a cleaner diff in viewing changes in the commit, but not be consistent with other help.

**Comment by amervitz** [comment]
The name Modify-CrmRecordAccess gives a warning for using an unapproved verb when the module is imported. Should we use the suggested alternative verb of Edit? I could add an alias of Modify-CrmRecordAccess if you think that would be helpful.

> VERBOSE: The 'Modify-CrmRecordAccess' command in the Microsoft.Xrm.Data.PowerShell' module was imported, but because its name does not include an approved verb, it might 
> be difficult to find. The suggested alternative verbs are "Edit".

**Comment by kenakamu** [comment]
As modify is not approved verb, we should use different ones. You can see all approved verb by running get-verb.

In this case, Grant and Revoke sounds good?

**Comment by amervitz** [comment]
I think Grant and Revoke are fine, they aren't giving a warning when imported.

**Comment by seanmcne** [comment]
Congrats - thanks for the help @amervitz!  Closing, as we're done here :)
