### ISSUE TITLE
UniqueIdentifier is not part of the type mapping 

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#153]
With version 2.4 is it not possible to update attribute of type "UniqueIdentifier", for instance "processid" or "stageid" of the entity "lead". 
````
# NOTE: ProcessId and StageId are not of type lookup!
$update = @{ 
    processid = $defaultProcessId;
    stageid  = $prospectStageId;
}

Update-CrmRecord -EntityLogicalName 'lead' -Id $lead.leadid -Fields $update;
````

The following code must be added ("Microsoft.Xrm.Data.Powershell.psm1", line 748)  in order to update attribute of type "UniqueIdentifier".

`````
"Guid" {
     $newfield.Type = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::UniqueIdentifier;
}
````

**Comment by seanmcne** [comment]
@thuld do you want to contribute this change and issue a PR for it?

**Comment by thuld** [comment]
Hello Sean, 
I have just created my very first PR ever. Not sure if everything is correct (in terms of the pull request). I have tested the modifications locally and the new function "Get-FieldTypeByFieldValue" should work as expected.

**Comment by kenakamu** [comment]
closed. Thanks @thuld for your PR!
