### ISSUE TITLE
Set-CrmRecord for Custom Activity Entities

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#155]
The logic of the ````Set-CrmRecord```` does not work, because the primary-attribute of an custom activity entity is not ````foobar_namecustomentityid````, instead is the primary-key attribute simply ````activityid````.

I will create an PR that tries to bypass this limitation by introducing an additional optional parameter for the function ````Set-CrmRecord````.

**Comment by thuld** [comment]
I just created the PR and removed the not needed ";"

**Comment by kenakamu** [comment]
thanks! I am closing this.
