### ISSUE TITLE
Set-CrmSystemSettings not calling Get-CrmEntityAttributes with $conn parameter

### ISSUE THREAD

**Issue by amervitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#160]
Hello,

When calling the Set-CrmSystemSettings cmdlet in a script, it exits early with the following message:

> WARNING: You need to create Connect to CRM Organization. Use Get-CrmConnection to create it.

I've tracked this down to the following line of code that isn't passing in the $conn parameter to Get-CrmEntityAttributes:

`$attributesMetadata = Get-CrmEntityAttributes -EntityLogicalName organization`

Thanks,

Alan

**Comment by amervitz** [comment]
Let me know if you'd like me to submit a pull request with a fix.

**Comment by seanmcne** [comment]
That would be great if you could do that, thanks!

**Comment by seanmcne** [comment]
Merged...
