### ISSUE TITLE
Update to v8.2 dlls (Dynamics 365 versions)

### ISSUE THREAD

**Issue by amervitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#165]
It would be helpful to update the various referenced dlls from v8.1 to v8.2 as included in the [Dynamics 365 SDK](https://www.microsoft.com/en-us/download/details.aspx?id=50032), so that the `Microsoft.Xrm.Tooling.Connector.CrmServiceClient` is the same version as that which is used with the package deployer cmdlets included in the Dynamics 365 SDK. Otherwise you get errors when trying to share the connection object between cmdlets in the two projects.

Is this something you're open to updating?

**Comment by seanmcne** [comment]
Great idea!  I'll connect w/ Ken and see if we can get a release with the 8.2 updated DLL's.  I'm also exploring the usage of the global discovery request but I'm not quite ready to wire that all up yet.

**Comment by kenakamu** [comment]
done
