### ISSUE TITLE
Add-CrmSecurityRoleToUser bug or?

### ISSUE THREAD

**Issue by mlysgaard** [seanmcne/Microsoft.Xrm.Data.PowerShell#168]
Hi, I have been trying to assign roles to my users, but when I check my users role in the browser afterwards no role is assigned. 
The powershell is something like below and I have tried using both rolename  and roleid:
$global:conn = Get-CrmConnection -Credential $Cred -DeploymentRegion EMEA -OnLineType Office365 -OrganizationName $Org

$upn = "xxxx@domain.dk"
$role = 'Sales Manager'
$salesmanagerroleid = "7b2f5673-696b-e611-80ed-5065f38b05b1"

$users = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq -FilterValue $upn -Fields *
$user = $users.CrmRecords[0]

Add-CrmSecurityRoleToUser -UserId $user.systemuserid -SecurityRoleName $role

Checking users settings afterwards using Get-CrmUserSecurityRoles $user.systemuserid I see the role correctly and if I compare this to a user which has bee assigned role through the browser values are the same, what is going wrong??

**Comment by kenakamu** [comment]
Could you double check if you have any error. Run Add-CrmSecurityRoleToUser and check $conn object to see last error?

**Comment by mlysgaard** [comment]
**This is my code:**
Import-Module Microsoft.Xrm.Data.Powershell

$User = "admin@domain.dk"
$PWord = Get-Content c:\scripts\encrypted_password3.txt | ConvertTo-SecureString 
$Cred = New-Object –TypeName System.Management.Automation.PSCredential –ArgumentList $User, $PWord

$CRMOrgs = Get-CrmOrganizations -Credential $Cred -DeploymentRegion EMEA –OnlineType Office365
$Org = $CRMOrgs[2].UniqueName

$Org 2>> c:\scripts\logging\$userid.txt

$global:conn = Get-CrmConnection -Credential $Cred -DeploymentRegion EMEA -OnLineType Office365 -OrganizationName $Org

$upn = "xxx@domain.dk"
$role = 'EG Sales Manager'

$users = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq -FilterValue $upn -Fields *
$user = $users.CrmRecords[0]

Write-Host "UserId:"
$user.systemuserid 2>> c:\scripts\logging\$userid.txt

#Add-CrmSecurityRoleToUser -UserId $user.systemuserid -SecurityRoleId $salesmanagerroleid 2>> c:\scripts\logging\$userid.txt

Add-CrmSecurityRoleToUser -UserId $user.systemuserid -SecurityRoleName $role
Write-Host "Print errors (if any):"
Write-host $global:conn.LastCrmError
Write-host $global:conn.LastCrmException

Write-Host "Role assigned:"
Get-CrmUserSecurityRoles $user.systemuserid

Write-Host "Remove role..."
Remove-CrmSecurityRoleFromUser -UserId $user.systemuserid -SecurityRoleId $salesmanagerroleid

**And this is output form ISE:**
UserId:

Guid                                                                                                                                          
----                                                                                                                                          
31204a8c-29e2-e611-8104-5065f38b0581                                                                                                          
Print errors (if any):


Role assigned:

RoleId           : 7b2f5673-696b-e611-80ed-5065f38b05b1
RoleName         : EG Sales Manager
BusinessUnitName : org********

Remove role...

**Comment by seanmcne** [comment]
I just tested this several times with several roles and had success as-is.  I wonder if you're somehow connected to the wrong org?  Or it's possible that there's a UI cache (but that should be real-time pulling from the data).  

I do see that you have a remove role step - that would obviously role back the change.  Can you try this out? 

$sysuserroles = Get-CrmRecords -EntityLogicalName systemuserroles -Fields * -FilterAttribute systemuserid -FilterOperator eq -FilterValue $user.systemuserid

$sysuserroles.CrmRecords

This should confirm the users role being updated.

**Comment by mlysgaard** [comment]
Argh, nvm was me nothing using correct organisation, sorry for the inconvience.
