### ISSUE TITLE
Get-CrmRecords does not support null searches

### ISSUE THREAD

**Issue by gregmcguffey** [seanmcne/Microsoft.Xrm.Data.PowerShell#169]
It appears that the `Get-CrmRecords` does not support null searches. I wanted to search for the top level business unit, which would be the only one with a null *parentbusinessunitid*.  Fetch XML supports the `null` and `not-null` operators, which do not require a value, but `Get-CrmRecords` always requires a value. It would be nice to extend filter capabilities for null searches.

**Comment by seanmcne** [comment]
@kenakamu I think we should try to support this, longer term i'd like to see us pull in a workitem that turns the operators into an enumeration instead of having to know the options so you can simply start tabbing to select the proper operator.

**Comment by seanmcne** [comment]
@gregmcguffey a simple workaround that might help with this is doing something like this: 

Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute fullname -FilterOperator not-null -FilterValue " "

**Comment by kenakamu** [comment]
Sure. I will.

**Comment by seanmcne** [comment]
FYI I'm pretty sure this code would work for us - took me a bit to get the dynamic parameter to work but in my testing I was able to get it working eventually. I was originally using the ConditionOperator Enum however those values don't match 100% to the fetch operators :( 

Regardless, this code should work - I've included a simple test to show how the dynamic param should be added to something like get-crmrecords - in case we need to use the fetch operators anywhere else we can use a simple function to build out the dynamic parameters: 


function DynamicFetchOperatorParameter {
        PARAM(
        [Parameter(Mandatory=$true, Position=0)]
        [object]$ParameterName, 
        [Parameter(Mandatory=$true, Position=1)]
        [object]$Position, 
        [Parameter(Mandatory=$true, Position=2)]
        [object]$Mandatory
        )
    # Create the collection of attributes
    $AttributeCollection = New-Object System.Collections.ObjectModel.Collection[System.Attribute]
 
    # Create and set the parameters' attributes
    $ParameterAttribute = New-Object System.Management.Automation.ParameterAttribute
    $ParameterAttribute.ValueFromPipeline = $true
    $ParameterAttribute.ValueFromPipelineByPropertyName = $true
    $ParameterAttribute.Mandatory = $Mandatory
    $ParameterAttribute.Position = $Position
 
    # Add the attributes to the attributes collection
    $AttributeCollection.Add($ParameterAttribute)
 
    # Generate and set the ValidateSet
    $ValidateSetAttribute = New-Object System.Management.Automation.ValidateSetAttribute(@('eq'
      ,'neq'
      ,'ne'
      ,'gt'
      ,'ge'
      ,'le'
      ,'lt'
      ,'like'
      ,'not-like'
      ,'in'
      ,'not-in'
      ,'between'
      ,'not-between'
      ,'null'
      ,'not-null'
      ,'yesterday'
      ,'today'
      ,'tomorrow'
      ,'last-seven-days'
      ,'next-seven-days'
      ,'last-week'
      ,'this-week'
      ,'next-week'
      ,'last-month'
      ,'this-month'
      ,'next-month'
      ,'on'
      ,'on-or-before'
      ,'on-or-after'
      ,'last-year'
      ,'this-year'
      ,'next-year'
      ,'last-x-hours'
      ,'next-x-hours'
      ,'last-x-days'
      ,'next-x-days'
      ,'last-x-weeks'
      ,'next-x-weeks'
      ,'last-x-months'
      ,'next-x-months'
      ,'olderthan-x-months'
      ,'olderthan-x-years'
      ,'olderthan-x-weeks'
      ,'olderthan-x-days'
      ,'olderthan-x-hours'
      ,'olderthan-x-minutes'
      ,'last-x-years'
      ,'next-x-years'
      ,'eq-userid'
      ,'ne-userid'
      ,'eq-userteams'
      ,'eq-useroruserteams'
      ,'eq-useroruserhierarchy'
      ,'eq-useroruserhierarchyandteams'
      ,'eq-businessid'
      ,'ne-businessid'
      ,'eq-userlanguage'
      ,'this-fiscal-year'
      ,'this-fiscal-period'
      ,'next-fiscal-year'
      ,'next-fiscal-period'
      ,'last-fiscal-year'
      ,'last-fiscal-period'
      ,'last-x-fiscal-years'
      ,'last-x-fiscal-periods'
      ,'next-x-fiscal-years'
      ,'next-x-fiscal-periods'
      ,'in-fiscal-year'
      ,'in-fiscal-period'
      ,'in-fiscal-period-and-year'
      ,'in-or-before-fiscal-period-and-year'
      ,'in-or-after-fiscal-period-and-year'
      ,'begins-with'
      ,'not-begin-with'
      ,'ends-with'
      ,'not-end-with'
      ,'under'
      ,'eq-or-under'
      ,'not-under'
      ,'above'
      ,'eq-or-above'))
 
    # Add the ValidateSet to the attributes collection
    $AttributeCollection.Add($ValidateSetAttribute)
 
    # Create the dictionary
    $RuntimeParameterDictionary = New-Object System.Management.Automation.RuntimeDefinedParameterDictionary
 
    # Create and return the dynamic parameter
    $RuntimeParameter = New-Object System.Management.Automation.RuntimeDefinedParameter($ParameterName, [string], $AttributeCollection)
    $RuntimeParameterDictionary.Add($ParameterName, $RuntimeParameter)
    return $RuntimeParameterDictionary}
function test-fetchParam
{
    #for reference only - can be used in get-crmrecords, etc
    [CmdletBinding()]
    Param()
    DynamicParam {
        return DynamicFetchOperatorParameter -ParameterName "FilterOperator" -Position 0 -Mandatory $true
    }
    Process{
        Write-Output "FilterOperatorValue is: $($PSBoundParameters.FilterOperator)"    
    }
}

**Comment by amervitz** [comment]
What would the call to Get-CrmRecords look like with this new dynamic parameter? Can you show an example?

**Comment by seanmcne** [comment]
exactly the same, the difference is that you now would get Tab completion for the FilterOperator parameter 

Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq "user@domain.com"

**Comment by seanmcne** [comment]
You can try it by importing the module, then run this block of code and it should overwrite the function - you'll find that all you need to do now for filteroperator is press Tab to get a valid operator.  We could also use this to validate the operators if we wanted to do that as well. 

```powershell
function DynamicFetchOperatorParameter {
        PARAM(
        [Parameter(Mandatory=$true, Position=0)]
        [object]$ParameterName, 
        [Parameter(Mandatory=$true, Position=1)]
        [object]$Position, 
        [Parameter(Mandatory=$true, Position=2)]
        [object]$Mandatory,
        [Parameter(Mandatory=$false, Position=3)]
        [string[]]$Alias = @()
        )
    # Create the collection of attributes
    $AttributeCollection = New-Object System.Collections.ObjectModel.Collection[System.Attribute]
 
    # Create and set the parameters' attributes
    $ParameterAttribute = New-Object System.Management.Automation.ParameterAttribute
    $ParameterAttribute.ValueFromPipeline = $true
    $ParameterAttribute.ValueFromPipelineByPropertyName = $true
    $ParameterAttribute.Mandatory = $Mandatory
    $ParameterAttribute.Position = $Position
 
    # Add the attributes to the attributes collection
    $AttributeCollection.Add($ParameterAttribute)
 
    # Generate and set the ValidateSet
    $ValidateSetAttribute = New-Object System.Management.Automation.ValidateSetAttribute(@('eq','neq','ne','gt','ge','le','lt','like','not-like','in','not-in','between','not-between','null','not-null','yesterday','today','tomorrow','last-seven-days','next-seven-days','last-week','this-week','next-week','last-month','this-month','next-month','on','on-or-before','on-or-after','last-year','this-year','next-year','last-x-hours','next-x-hours','last-x-days','next-x-days','last-x-weeks','next-x-weeks','last-x-months','next-x-months','olderthan-x-months','olderthan-x-years','olderthan-x-weeks','olderthan-x-days','olderthan-x-hours','olderthan-x-minutes','last-x-years','next-x-years','eq-userid','ne-userid','eq-userteams','eq-useroruserteams','eq-useroruserhierarchy','eq-useroruserhierarchyandteams','eq-businessid','ne-businessid','eq-userlanguage','this-fiscal-year','this-fiscal-period','next-fiscal-year','next-fiscal-period','last-fiscal-year','last-fiscal-period','last-x-fiscal-years','last-x-fiscal-periods','next-x-fiscal-years','next-x-fiscal-periods','in-fiscal-year','in-fiscal-period','in-fiscal-period-and-year','in-or-before-fiscal-period-and-year','in-or-after-fiscal-period-and-year','begins-with','not-begin-with','ends-with','not-end-with','under','eq-or-under','not-under','above','eq-or-above'))
 
    # Add the ValidateSet to the attributes collection
    $AttributeCollection.Add($ValidateSetAttribute)
 
     if($Alias.count -gt 0) {
        $ParamAlias = New-Object System.Management.Automation.AliasAttribute -ArgumentList $Alias
        $AttributeCollection.Add($ParamAlias)
    }
    # Create the dictionary
    $RuntimeParameterDictionary = New-Object System.Management.Automation.RuntimeDefinedParameterDictionary
 
    # Create and return the dynamic parameter
    $RuntimeParameter = New-Object System.Management.Automation.RuntimeDefinedParameter($ParameterName, [string], $AttributeCollection)
    $RuntimeParameterDictionary.Add($ParameterName, $RuntimeParameter)
    return $RuntimeParameterDictionary
}

function Get-CrmRecords{
# .ExternalHelp Microsoft.Xrm.Data.PowerShell.Help.xml
 [CmdletBinding()]
    PARAM(
        [parameter(Mandatory=$false)]
        [Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn,
        [parameter(Mandatory=$true, Position=1)][alias("EntityName")]
        [string]$EntityLogicalName,
        [parameter(Mandatory=$false, Position=2)][alias("FieldName")]
        [string]$FilterAttribute,
        [parameter(Mandatory=$false, Position=4)][alias("Value", "FieldValue")]
        [string]$FilterValue,
        [parameter(Mandatory=$false, Position=5)]
        [string[]]$Fields, 
        [parameter(Mandatory=$false, Position=6)]
        [switch]$AllRows,
        [parameter(Mandatory=$false, Position=7)]
        [int]$TopCount
    )
    DynamicParam{
        return DynamicFetchOperatorParameter -ParameterName "FilterOperator" -Position 3 -Mandatory $false
    }

    begin{
        $FilterOperator=$PSBoundParameters.FilterOperator
        $conn = VerifyCrmConnectionParam $conn
        if($FilterOperator -and $FilterOperator.StartsWith("-"))
        {
            $FilterOperator = $FilterOperator.Remove(0, 1)
        }
        if( !($EntityLogicalName -cmatch "^[a-z_]*$") )
        {
            $EntityLogicalName = $EntityLogicalName.ToLower()
            Write-Verbose "EntityLogicalName contains uppercase which isn't possible in CRM, overwritting with ToLower() new value: $EntityLogicalName"
        }
        if( ($Fields -eq "*") -OR ($Fields -eq "%") )
        {
            Write-Warning 'PERFORMANCE: All attributes were requested'
            $fetchAttributes = "<all-attributes/>"
        }
        elseif ($Fields)
        {
            foreach($Field in $Fields)
            {
                if($field -ne $null){
                    $fetchAttributes += "<attribute name='{0}' />" -F $Field
                }
            }
        }
        else
        {
            #lookup the primary attribute 
            $primaryAttribute = $conn.GetEntityMetadata($EntityLogicalName.ToLower()).PrimaryIdAttribute
            $fetchAttributes = "<attribute name='{0}' />" -F $primaryAttribute
        }
        #if any of the values are missing, but they're not *ALL* missing 
        if( (!$FilterAttribute -OR !$FilterOperator -OR !$FilterValue) -AND ($FilterAttribute -Or $FilterOperator -Or $FilterValue) -And !($FilterAttribute -And $FilterOperator -And $FilterValue))
        {
            #TODO: convert this to a parameter set to avoid this extra logic
            Write-Error "One of the `$FilterAttribute `$FilterOperator `$FilterValue parameters is empty, to query all records exclude all filter parameters."
            return
        }
    
        if($FilterAttribute -and $FilterOperator -and $FilterValue)
        {
            # Escape XML charactors
            $FilterValue = [System.Security.SecurityElement]::Escape($FilterValue)
            Write-Verbose "Using the supplied single filter of $FilterAttribute '$FilterOperator' $FilterValue"
                    $fetch = 
@"
    <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" no-lock="true">
        <entity name="{0}">
            {1}
            <filter type='and'>
                <condition attribute='{2}' operator='{3}' value='{4}' />
            </filter>
        </entity>
    </fetch>
"@
        }
        else{
            Write-Warning "PERFORMANCE: `$FilterAttribute `$FilterOperator `$FilterValue were not supplied, fetching all records with NO filter."
            $fetch = 
@"
    <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" no-lock="true">
        <entity name="{0}">
            {1}
        </entity>
    </fetch>
"@
        }
        $fetch = $fetch -F $EntityLogicalName, $fetchAttributes, $FilterAttribute, $FilterOperator, $FilterValue

    }
    process{
        if($AllRows)
        {
            Write-Warning "PERFORMANCE: All rows were requested instead of the first 5000"
            $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -AllRows
        }
        else
        {
            $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount $TopCount
        }
        return $results

    }
}
```

**Comment by amervitz** [comment]
I'm not sure if it's something wrong with the code or my environment but the autocompletion on the filter operator wouldn't work. I'll take your word for it though 😄 

Another option which is arguably simpler code but not as user friendly is a custom enum with some handling for hyphens in variable names because C# doesn't allow them:

```powershell
Add-Type -TypeDefinition @"
   public enum FilterOperator
   {
      @null,
      not_null,
      eq,
      yesterday
   }
"@

function FetchTest {
  param (
    [FilterOperator]
    $Operator
  )
  
  Write-Host "original = $Operator"
  $fetchOperator = $Operator.ToString().Replace('_','-')
  Write-Host "fetch version = $fetchOperator"
}

PS C:\WINDOWS\system32> FetchTest -Operator null
original = null
fetch version = null

PS C:\WINDOWS\system32> FetchTest -Operator not_null
original = not_null
fetch version = not-null

PS C:\WINDOWS\system32> FetchTest -Operator yesterday
original = yesterday
fetch version = yesterday
```

Either way this is looking like a nice addition 👍

**Comment by seanmcne** [comment]
Yep, that's exactly what this is - it's essentially an Enum with dynamic parameter so it's easy to update.  There's other ways to do this that are less dynamic such as follows.  However, if you use this method, we would need this same ValidateSet for every function param that works from this set - the only way to make it re-usable and dynamic is to use the dynamic parameter values above.  Since we're only using this in one function we can go with the static set approach for now as it's a bit simpler. 

```powershell
[parameter(Mandatory=$false, Position=3)][alias("Op")]
[ValidateSet('eq','neq','ne','gt','ge','le','lt','like','not-like','in','not-in','between','not-between','null','not-null','yesterday','today','tomorrow','last-seven-days','next-seven-days','last-week','this-week','next-week','last-month','this-month','next-month','on','on-or-before','on-or-after','last-year','this-year','next-year','last-x-hours','next-x-hours','last-x-days','next-x-days','last-x-weeks','next-x-weeks','last-x-months','next-x-months','olderthan-x-months','olderthan-x-years','olderthan-x-weeks','olderthan-x-days','olderthan-x-hours','olderthan-x-minutes','last-x-years','next-x-years','eq-userid','ne-userid','eq-userteams','eq-useroruserteams','eq-useroruserhierarchy','eq-useroruserhierarchyandteams','eq-businessid','ne-businessid','eq-userlanguage','this-fiscal-year','this-fiscal-period','next-fiscal-year','next-fiscal-period','last-fiscal-year','last-fiscal-period','last-x-fiscal-years','last-x-fiscal-periods','next-x-fiscal-years','next-x-fiscal-periods','in-fiscal-year','in-fiscal-period','in-fiscal-period-and-year','in-or-before-fiscal-period-and-year','in-or-after-fiscal-period-and-year','begins-with','not-begin-with','ends-with','not-end-with','under','eq-or-under','not-under','above','eq-or-above')] 
[string]$FilterOperator
```

**Comment by amervitz** [comment]
It would be great if the dynamic parameter could restrict the allowed operators based on the data type of the provided filter value (e.g. supplying a string filter value wouldn't allow the date comparison operators). Ideally the filter attribute would influence this too but that would require metadata queries which I'm sure would want to be avoided.

**Comment by seanmcne** [comment]
@amervitz - tough part with that is, we'd need to be metadata aware which means we'd have to pull entity metadata every time you connect, etc.  Might be cool in the future but for now I think it would add a lot of potential overhead. However, if we had all the orgs metadata we could do this with dynamic params for sure. 

Created branch and PR #171 to address this issue

**Comment by amervitz** [comment]
@seanmcne understood re: metata, all I'm suggesting is a dynamic parameter implementation of FilterOperator might be able to perform a simplified form of validation of allowed operators to choose from solely given the supplied FilterValue's  .NET data type, or even vice versa. Just my 2 cents for if this is enhanced in the future.

**Comment by seanmcne** [comment]
Ok all set - Merged so I'm going to close it out.  Thanks everyone!
