### ISSUE TITLE
approve-crmemailaddress CONN parameter not functioning in foreach.

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#17]
![image](https://cloud.githubusercontent.com/assets/2292260/11434070/21c09e7c-948c-11e5-96e5-d9bcd5371314.png)

![image](https://cloud.githubusercontent.com/assets/2292260/11434077/33f6f91a-948c-11e5-8bbd-a4dff7808f00.png)

**Comment by kenakamu** [comment]
fixed
