### ISSUE TITLE
Publish 2015/2016 theme

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#170]
Can anyone provide an example of how to publish a theme with powershell?  We are already using the XRM Data PowerShell functions.

**Comment by jeffreynelson** [comment]
I did try Publish-CRMEntity specifying the logical entity of theme, but that did not seem to work.

**Comment by seanmcne** [comment]
Leaving myself a note here.  Should be able to whip up a sample shortly. 

<request i:type="b:PublishThemeRequest">
            <b:key>Target</b:key>
            <b:value i:type="a:EntityReference">
              <a:Id>2b0758d8-562f-4181-752e-4eb07907f510</a:Id>
              <a:LogicalName>theme</a:LogicalName>
<a:RequestName>PublishTheme</a:RequestName>

**Comment by seanmcne** [comment]
Give this a shot - you just need to create a publishTheme request, assign it the entity ref of the theme you've created or want to publish - then send the request in.  This would probably make a good cmdlet to have for people to use (maybe publish-crmtheme?). Let me know how it works for you. 

```powershell
$req = New-Object Microsoft.Crm.Sdk.Messages.PublishThemeRequest
$req.target = New-CrmEntityReference -EntityLogicalName "theme" -Id "2b0758d8-562f-4181-752e-4eb07907f510"
$result = [Microsoft.Crm.Sdk.Messages.PublishThemeResponse]$conn.ExecuteCrmOrganizationRequest($req, $null)
```

**Comment by jeffreynelson** [comment]
Thanks, 

That seems to have worked OK.

**Comment by kenakamu** [comment]
added new function Publish-CrmTheme
