### ISSUE TITLE
shorten 2.5 release schedule?

### ISSUE THREAD

**Issue by amervitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#172]
Would it be possible to schedule the 2.5 release before all the remaining open issues assigned to the 2.5 release are closed? I would really like to be able to deploy the commits from #160 and #165 via the PowerShell gallery.

**Comment by kenakamu** [comment]
Yes, we are planning to include most issues to 2.5 and target release date is end of this week. (sunday)

**Comment by amervitz** [comment]
Perfect, thanks!
