### ISSUE TITLE
Create an: Enable-CrmMailbox cmdlet 

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#186]
Enable-CrmMailbox function (I don’t know if we should be specific to user, as it could be any mailbox technically) 
-	At this point it should take a parameter for orgmarkedasprimaryforexchangesync
-	Function will (hard coded) set the testemailconfigurationscheduled = $true which should scheduled the email approval check and run it shortly after - if it succeeds it will enable the mailbox (need to verify with testing)

**Comment by kenakamu** [comment]
Like this? Not sure about orgmarkedasprimaryforexchangesync though. Can we simply set it per record?

```powershell
Set-CrmRecord -EntityLogicalName mailbox -Id $mailbox.mailboxid -Fields @{"testemailconfigurationscheduled"=$true;"statecode"= (New-CrmOptionSetValue -Value 0);"statuscode"=(New-CrmOptionSetValue -Value 1)}
```

**Comment by seanmcne** [comment]
I say set it per mailbox as those can associate to queues or users.  Have a paramter for OrgMarkedAsPrimaryForExchangeSync, that would make sure it's the primary when it gets enabled (It should probably be optional).  Also, do we have to set the state/status codes?  I think we just need to set the test scheduled value to $true and the platform should do the rest for us. 

https://msdn.microsoft.com/en-us/library/mt607605.aspx

Note: we still want this helper but it's somewhat less of a concern than it used to be.  CRM 8.2+ will auto approve email addresses as long as the primary email address matches the users primary email address in ExchangeOnline

**Comment by kenakamu** [comment]
Added parameters to existing function Set-CrmUserMailBox. I also added Set-CrmQueueMailBox
