### ISSUE TITLE
New function proposal: Invoke-CrmAction

### ISSUE THREAD

**Issue by amervitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#189]
Would you be interested in a PR for a new function that [executes an action](https://msdn.microsoft.com/en-us/library/dn481600.aspx#bkmk_execute)? I had to do this recently and didn't find a function specifically for this purpose.

It would be named _Invoke-CrmAction_. It would wrap the [Execute](https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.client.organizationserviceproxy.execute.aspx) method and accept a hashtable of parameters as its input. I still need to determine if it would return the raw response object or extract values from the result.

**Comment by seanmcne** [comment]
@amervitz this sounds like a good idea - it will have to be somewhat dynamic though in that it may be a bit difficult to use.  Actions can define any number of inputs and outputs that vary in number (from action to action) as well as vary in the input/output types.   I'd suggest following the pattern for C# execution of actions today and probably going with two parameter sets - one for bound actions and one for unbound.  It may also require some kind of additional helper to make packaging up the inputs a little easier (just thinking off the top of my head).

**Comment by amervitz** [comment]
@seanmcne OK, I'll take all of that into consideration. Something I've been thinking about and will experiment with is to see if the output argument(s) can themselves be represented as a CrmRecord return object. If so I think that could be a nice familiar return type to work with.

Regarding a helper for inputs, assuming this is possible, what do you think of it being in the form of a function that retrieves metadata about the action, so that one could inspect the resulting information to know what input/output parameters are involved in the action's usage. For example, it could be _Get-CrmActionMetadata_, with parameters to qualify the one to retrieve information about.
