### ISSUE TITLE
Error - The authentication endpoint Kerberos was not found on the configured Secure Token Service!, when specifying homerealm url

### ISSUE THREAD

**Issue by Toftager** [seanmcne/Microsoft.Xrm.Data.PowerShell#190]
I have a setup where an onprem CRM 2016 is connected to a ADFS federation broker which in turn connects to differenct customers adfs servers, including the adfs server connected to the domain of the CRM server. 

When specifying the CRM Domain adfs server via HomeRealm Url i'm getting these errors: 

```
WARNING: Failed to connect to CRM: BadConnect
WARNING: Failed to connect to CRM: The authentication endpoint Kerberos was not found on the configured Secure Token Service!

Get-CrmConnection : The pipeline has been stopped.
At XXXXXXX:16 char:12
+ $crmConn = Get-CrmConnection -OrganizationName XXXXXX -HomeRealmUrl https://ad ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (:) [Get-CrmConnection], PipelineStoppedException
    + FullyQualifiedErrorId : -9,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand
 
Get-CrmConnection : Failed to connect to CRM: The authentication endpoint Kerberos was not found on the configured Secure Token Service!
At XXXXXXX:16 char:12
+ $crmConn = Get-CrmConnection -OrganizationName XXXXXX -HomeRealmUrl https://ad ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Get-CrmConnection], Exception
    + FullyQualifiedErrorId : -3,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand

```
The enviroment works fine when connecting via Web or Outlook. Also XRMToolbox works fin. 

I also have an enviroment where CRM connects directly to the domain ADFS on the same domain. Here the parts work as expected. 

So i guess there is some problem in code when handling HomeRealmUrl. 

Could you take a look at this. And let me know if you need any other info,

/Peter

**Comment by seanmcne** [comment]
Can you try using the -interactiveMode switch when connecting using discovery? Also, taking a fiddler trace when connecting may help. Finally, there is a xrm tooling log file created that will show failures in the underlying connector code if that's where the failure is  - because get-crmConnection is provided in the xrm tooling dll we'll have to try and figure out why it's unable to connect to the endpoint in adfs when specifying the home realm url.

https://technet.microsoft.com/en-us/library/dn756303.aspx

Sent from Outlook<https://aka.ms/qtex0l> on a phone

_____________________________

**Comment by Toftager** [comment]
Thanks for your response Sean. 

Unfortunately using interactivemode, does not giv the possibility of adding a homerealmurl, so this is not an option. 

I tried connecting using the Get-CrmConnection from Microsoft.Xrm.Tooling.CrmConnector.Powershell.dll, this gives the following error

```
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:26:59  Created CrmConnectionManager 
Microsoft.Xrm.Tooling.CrmConnectControl	Verbose	16	01-03-2017 09:26:59  Error Message: Failed to get credentials from Windows Vault
Source	: Microsoft.Xrm.Tooling.CrmConnectControl
Method	: ReadCredentials
Date	: 01-03-2017
Time	: 09:26:59
Error	: Failed to read the saved credentials.
Stack Trace	: at Microsoft.Xrm.Tooling.CrmConnectControl.Utility.CredentialManager.ReadCredentials(String target)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.LoadConfigFromFile(Boolean readLocalFirst)
======================================================================================================================

Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:26:59  SetConfigKeyInfo, Key Count = 10
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:26:59  Using CRM deployment type Prem
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:26:59  SSL Connection = True
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:26:59  Discovery URI is = https://XXXXXXXX:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	01-03-2017 09:26:59  DiscoverOrganizations - Initializing Discovery Server Object with https://XXXXXXXX/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	01-03-2017 09:26:59  DiscoverOrganizations - attempting to connect to CRM server @ https://XXXXXXXX/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	01-03-2017 09:26:59  DiscoverOrganizations - created CRM server proxy configuration for https://XXXXXXXX/XRMServices/2011/Discovery.svc - duration: 00:00:00.2010000
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	01-03-2017 09:26:59  DiscoverOrganizations - proxy requiring authentication type : Federation 
Microsoft.Xrm.Tooling.CrmConnectControl	Error	2	01-03-2017 09:26:59  Error Message: Can't connect to Microsoft Dynamics CRM - XXXXXXXX.
Source	: Microsoft.Xrm.Sdk
Method	: GetIssuerEndpoint
Date	: 01-03-2017
Time	: 09:26:59
Error	: The authentication endpoint Kerberos was not found on the configured Secure Token Service!
Stack Trace	: at Microsoft.Xrm.Sdk.Client.IssuerEndpointDictionary.GetIssuerEndpoint(TokenServiceCredentialType credentialType)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:28:24  Created CrmConnectionManager 
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:28:24  CheckBoxState = False
Microsoft.Xrm.Tooling.CrmConnectControl	Information	8	01-03-2017 09:28:24  CheckBoxState = False
```
I tried writing my own consol app connecting to the same Org, and also encountered problems when working with the CrmServiceClient. 

Finally i tried using a OrganizationServiceProxy, and using this as the constructor to the CrmServiceClient. This worked. 

I changed this into powershell like this

```
Add-Type -Path "Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Sdk.dll" 
Add-Type -Path "Microsoft.Xrm.Data.PowerShell\Microsoft.Crm.Sdk.Proxy.dll"

$cred = New-Object System.ServiceModel.Description.ClientCredentials
$cred.UserName.UserName = "LOGIN"
$cred.UserName.Password = "PASSWORD"

$homerealmUrl = New-Object System.Uri -ArgumentList "https://adfs.ADFS/adfs/services/trust/mex"
$url = New-Object System.Uri -ArgumentList "https://XXXXXXXX/XRMServices/2011/Organization.svc"
$proxy = New-Object Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy -ArgumentList ($url,$homerealmUrl,$cred,$null)
$crmConn = New-Object Microsoft.Xrm.Tooling.Connector.CrmServiceClient -ArgumentList $proxy
```
And then it connected, and the conn can be used in all the components. 

So I guess there is a bug in the CrmServiceClient, when working with homerealmurl :-(

**Comment by seanmcne** [comment]
@Toftager 
Can you test again with this latest repo update (newer assemblies)?  We haven't released an updated module yet but would be nice to see if the updated assemblies help or not. 

Thanks!

**Comment by Toftager** [comment]
Just tested again, with the latest files. But unfortunately same error.

We have opened a ticked with MS Support, but no news yet. 

Hoping for a fix in V.Next

**Comment by seanmcne** [comment]
How's the support ticket going?  Get-CrmConnection is a core cmdlet in the tooling connector and not part of this project.  Curious how that is progressing.  Thanks!

**Comment by Toftager** [comment]
Hi Sean,

Sorry for the long reply time, its vacation time here.

Unfortunately it is not going very well with our support ticket. After opening the ticket, almost a month went by before we got any kind for response from MS. After that we went through 2 supporters before finally a supporter acknowledged, and understood the problem. Unfortunately he went on vacation, and passed our ticket on. This meant we started from scratch again. Finally I have been on vacation the last 14 days, and the MS closed our ticket 

We have isolated the problem to the CrmServiceClient object. When this object is initialized with a connection string, containing a homerealm url, the homerealm is ignored. 

If we create a OrganizationServiceProxy, and pass this to the CrmServiceClient, everything is fine. Unfortunately doing this only works for the first org we want to connect to. When instantiating a new CrmServiceClient, with another OrganizationServiceProxy. The first org is still call, making our automated scripts quite problematic. 

So the problem is in the code for CrmServiceClient, but we are having a really hard time getting traction with MS, as the seems to be a quite unique situation, and people don’t seem to understand the problem 

If you have any possibility inside MS to do anything let me know and I can send you the ticket number or any info you need.

/Peter

**Comment by seanmcne** [comment]
Can you ping me via: seanmcne_github at outlook.com (seanmcne underscore github at outlook dot com).  If you send me your case# I'll look into it and see if they've logged a bug for new assemblies coming out in the near future.

**Comment by Toftager** [comment]
Just droped you an email. Let me know if you need anything else. 

Thanks

**Comment by RIKIKU** [comment]
Hi, 
I've had some experience with this error in the past. It is likely that the cmdlet is trying to authenticate through an ADFS proxy server and also trying to use Windows/Kerberos Authentication to do so. The Kerberos Endpoint cannot be published through a proxy as it is unsafe. The only way you can get around this is to use a different authentication method that is supported by the proxy, such as OAuth or Forms. Alternatively, connecting through a VPN and not using the proxy at all would solve this issue. 
I am not sure if you can choose to use Forms authentication via Get-CrmConnection, @seanmcne do you know if there's a way to do it? Is it even necessary now with v9.2 ?

**Comment by seanmcne** [comment]
Hi everyone, is this still a blocker?  I'm not exactly sure what we can do here, since this seems to be an issue with Xrmtooling connector or CrmServiceClient which you should be able to reproduce.  If you can get it working in a console app or another .net app we can probably get it working in powershell if there's a tweak that needs to be made - thanks!
