### ISSUE TITLE
Using for delegated administration

### ISSUE THREAD

**Issue by Zoltango** [seanmcne/Microsoft.Xrm.Data.PowerShell#193]
Hi All,

Can you please help how I can use these cmdlets to manage customer Dynamics 365 (online) tenant's where I have admin on behalf/Delegated Admin permission?

I tried to connect to like this but it seems I was connected to my own tenant:
_Connect-CrmOnline -Credential $Cred -ServerUrl 'https://**CUSTOMERTENANT**.crm4.dynamics.com'_

Result is:
IsReady                        : True
IsBatchOperationsAvailable     : True
CrmConnectOrgUriActual         : https://**MYTENANT**.api.crm4.dynamics.com/XRMServices/2011/Organization.svc

Is the solution supports delegated administration?
On Office 365 level I have no issue I can perform routine tasks like create users - even with PowerShell using -tenantID switch. Also I can log to application on customer's tenant as Delegated Admin. 

Thank you a lot in advance!

Best regards,
Zoltán

**Comment by amervitz** [comment]
I haven't tried that scenario myself, but if you can try using `Get-CrmConnection -InteractiveMode` and see if the resulting connection object is connected to the correct organization, it might give us some clues as to whether this scenario is possible.

**Comment by Zoltango** [comment]
Thank you for reply. 
Get-CrmConnection -InteractiveMode  connecting to my own, default organization automatically. I think this is correct.
In this scenario I am looking for a way to manage dozens of customers using Delegated Administrator feature for CSP and Advisory partners. On Azure AD level we can use -tenantID <customerGUID> parameter for any cmdlet if customer accepted Admin on Behalf request.

**Comment by amervitz** [comment]
To be clear, when running `Get-CrmConnection -InteractiveMode`, select **Office 365** as Deployment Type, and select **Display list of available organizations**. Does it show you any of the customer organizations afterwards?

**Comment by Zoltango** [comment]
When I am running  Get-CrmConnection -InteractiveMode with these settings it displays "Retrieving available organizations" for a few seconds then displays "Connecting to default organization" and I became connected to my own partner organization. It is not showing list of my customers.

**Comment by amervitz** [comment]
OK, that's not a good sign! Ultimately this depends on whether delegated authentication is even supported in the Dynamics 365 SDK, but I can't find anything that describes this though. Perhaps @seanmcne or @kenakamu can comment or ask around in msft?

**Comment by seanmcne** [comment]
Ahh this is a very interesting scenario and one I'd hope we can accommodate.  Apologies for my ignorance on the delegated admin feature as it's something I haven't personally explored yet.  Are you able to write Xrm SDK tools/utilities using delegated admin as you'd expect?  

Here's my theory - today the xrm tooling connector verifies serverurl by using discovery - I suspect the org isn't in the discovery response which may be why it's coming back with another org. I seem to recall an email on this recently but I'm having trouble finding it - let me see if I can figure out if there's a way to disable that discovery check/validation.

**Comment by Zoltango** [comment]
Unfortunately I don't have Developer background, and I have no expreince on SDK :(

In web client we can use Delegeted Admin in a special access mode: it connects to customers organization by direct URL like https://CONTOSO.crm4.dynamics.com by using my partner (eg. user@partner.onmicrosoft.com) login. With this Delegated admin I can manage his settings on organization level, create Records, etc. But for example you can't use this Delegated admin user to link Customer organization to Outlook client. On TechNet we have this info: https://technet.microsoft.com/en-us/library/dn896595.aspx

On Office 365 / Azure level I can use my own partner account to manage customer's subscriptions, create users on Office 365 level or manage his settings like instances, updates, solutions using a tool called Partner Center - where all my customers listed where I have delegated admin privileges.

**Comment by seanmcne** [comment]
@Zoltango there is an update due out for the SDK in the near future that will allow us to disable or remove the discovery check on Xrm tooling which should let us specify the URL and credential without that verification (which should allow for this).  The issue right now is that XrmTooling is _trying_ to be _helpful_ by verifying using discovery and discovery is only designed to discover instances in the direct tenant (which means no delegated admin instances will return).  I presume the discovery bit is what's messing us up here and when we're able to shut that off we'll be able to do this.

**Comment by Zoltango** [comment]
Thank you Sean for the clarification. I'll follow it up in the next releases.

**Comment by seanmcne** [comment]
Going to mark this as "Blocked" - we'll have to wait for the XRM Connector v.next to ship (hopefully soon)

**Comment by seanmcne** [comment]
FYI - v.next will ship with CRM 9.0.  I look forward to updating the assemblies - at that time we should be able to allow delegated admin.

**Comment by seanmcne** [comment]
PR #254 contains the v3 **PREVIEW** assemblies and new code to allow for this, 
```powershell
#when prompted enter your partner upn user@patnerdomain.com and your PW 
#since discovery validation is now skipped by default you can login as a partner now
#WARNING: oAuth is not yet able to do this - future updates to the v3 assemblies should allow for this however Office365 auth should suffice especially for now. 

Connect-CrmOnline -ServerUrl customerinstance.crm.dynamics.com
```

**Comment by seanmcne** [comment]
Please test - I've testing using a similar model and had success.  Open a new issue/bug if you find an issue w/ the new assemblies and CSP.  Thanks for reporting this and thanks for your patience!
