### ISSUE TITLE
Cannot alter a team's administratorid via set-crmrecord

### ISSUE THREAD

**Issue by PvilleStang** [seanmcne/Microsoft.Xrm.Data.PowerShell#197]
Using Dynamics CRM 2016 on-prem deployment.  Microsoft.Xrm.Data.Powershell ver. 2.5.

x-post from https://community.dynamics.com/crm/f/117/t/231885

"get-crmrecords -entitylogicalname team" shows the administratorid as the team admin.  I need to alter these via script, but when I do:
`set-crmrecord -entitylogicalname team -id <team guid> -fields @{administratorid = "Name"}`

Also note: I've used name, domainname, GUID, no luck.

I get the following error: 
```
System.InvalidCastException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #7537B7EB
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:758 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : System.InvalidCastException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #7537B7EB
```

**Comment by seanmcne** [comment]
I believe administratorid is a lookup and should be set to an entity reference instead. You'll have to create a new-crmentityreference with the ID number for the new admin then change the name from a string to this entity ref - I am not at a pc to mock up code for it, but it shouldn't be too bad. Let me know if you need some additional info.

**Comment by seanmcne** [comment]
I have a few minutes on the plane here and thought I'd bump this with some code, there is a bug we have with @kenakamu to support a 'toEntityReference' in #152 - I was just thinking maybe every single entity record ought to have an EntityReference property that can be used instead.  Either way, it's a little extra work now until we make it a little easier to get an entity reference. 

``` powershell
$teamGuid = (Get-CrmRecords -EntityLogicalName team -FilterAttribute name -FilterOperator eq -FilterValue "myteam").CrmRecords[0].teamid

$newAdmin = (Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute fullname -FilterOperator eq -FilterValue "John Doe").CrmRecords[0].systemuserid

$newAdminRef = New-CrmEntityReference -entitylogicalname systemuser -Id $newAdmin

set-crmrecord -entitylogicalname team -id <team guid> -fields @{administratorid = $newAdminRef}
```

**Comment by PvilleStang** [comment]
You, sir, are a gentleman and a scholar.  Thank you very much!
