### ISSUE TITLE
Get-crmrecord doesn't retrieve all crm fields

### ISSUE THREAD

**Issue by MickaSecureIT** [seanmcne/Microsoft.Xrm.Data.PowerShell#198]
Hi
First of all, your tool is very great.
I got an issue with get-crmrecord cmdlet. Actually I try to make a script that can bulk change some CRM 2016 fields value, such as ownershipcode. 
First, I launch this command to retrieve all the filed values of an account : 
$CTM = Get-CrmRecord -EntityLogicalName account -Id <accountid of my crm account> -Fields *
A lot of attributes came out, but not the ones I need, such as ownershipcode.
Is it possible to really retrieve all of account attributes with get-crmrecord ?
Thanks again for your great job.
Micka

**Comment by amervitz** [comment]
@MickaSecureIT the fields are only on the returned objects when they actually have a value. If the object doesn't contain the field, you can infer it is null.

**Comment by MickaSecureIT** [comment]
Hi
OK I understand.
Thanks for your answer.
Regards
