### ISSUE TITLE
ERROR: Import-CRMSolution with the -AsyncOperationImportMethod is referencing missing write-information method

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#199]
The 2.5 release is referencing write-information calls that do not exist. 

I tried to switch to the async method due to importing a large solution that times out after two minutes.  The timeout occurs even after updating the default timeout settings.  Any ideas?

**Comment by amervitz** [comment]
@jeffreynelson Write-Information was introduced in PowerShell 5.0. A short-term solution would be to upgrade to that version of PowerShell if possible.

Longer term, the module should probably either specify PowerShell 5.0 as a minimum required version, or not use Write-Information for compatibility with older version of PowerShell.

**Comment by seanmcne** [comment]
@amervitz, every time I think we should cut off at v5 another few folks pop in that are still on 4 (or sometimes less).  So, I've been hesitant to bump that up here.  I'd be open to switching over to write-verbose for compat reasons in the short term though - it's just for informational/helpful messages anyhow :)

**Comment by seanmcne** [comment]
Fixed in PR #203
