### ISSUE TITLE
CRM Online 8.2: Create Application User/Identity

### ISSUE THREAD

**Issue by bermudas** [seanmcne/Microsoft.Xrm.Data.PowerShell#200]
Hi All,
Could you please help me to understand if it's possible.
We are using Dymanics 365.
There is a need to create an Application User (system user with Application ID) directly in CRM (not in Azure AD):
https://msdn.microsoft.com/en-us/library/mt790170.aspx

is it possible to do that using Microsoft.Xrm.Data.PowerShell?
I was trying to do it following way:
[GUID]$id="valid GUID of registred application"
$applicationuser=New-CrmRecord -EntityLogicalName systemuser -Fields @{"applicationid"=$id ; "fullname"="Test App";"internalemailaddress"="a@te.com"}
Write-Output $applicationuser

**Comment by bermudas** [comment]
One more question - is there any way to copy/clone security role using Microsoft.Xrm.Data.PowerShell?
Thank you in advance.

**Comment by amervitz** [comment]
@bermudas what happens when you try creating the applicaton user? Is there an error?

**Comment by seanmcne** [comment]
@bermudas yes you can create users using this - it just calls a create message via the api, obviously this would only apply to stub users and s2s auth but as long as you provide the right fields this would do the trick. If not, please let us know the error you're getting (remember app users for s2s is an 8.2 only feature). 

As for question #2, nothing provided but it could easily clone a role by creating  a new role, then retrieving the related rolePrivileges of the role to be cloned, then attaching those privileges to the new role you created.  There may even be a way to accomplish this in a streamlined fashion by using a compound create (Wrapping the role & role privileges into a single create message) but if that caused issues - adding the role prives one at a time or in an execute multiple would work just as well.

**Comment by seanmcne** [comment]
Let us know if you run into any issues with this approach @bermudas - I'll close this for now.  Thanks!
