### ISSUE TITLE
Does this module support partylists?

### ISSUE THREAD

**Issue by 2ATCaroline** [seanmcne/Microsoft.Xrm.Data.PowerShell#201]
Hi,
I'm trying to set a partylist column on an entity, but I when I try to create a partyactivity I get the following error:
The 'Create' method does not support entities of type 'activityparty'.

Does your module support settings partylist columns? and if so could you explain to me how?
Thank you in advance!
Caroline

(Update: I'm trying to set the customer field of a campaign response)

**Comment by seanmcne** [comment]
@2ATCaroline CRM doesn't support creating activity parties directly (the message you're seeing is from the platform).  Once you create an array of parties array you can associate it with the appropriate attribute of activity like sender or receiver etc.  To be honest I haven't tried doing this from our powershell module but i'd expect it to work fine with a list of activity party records. 

I don't have an environment to look at, at this second, but is customer on a campaign response a regarding field or activity party? Depending on that you may need to adjust the approach.
