### ISSUE TITLE
Does this module support add member list requests?

### ISSUE THREAD

**Issue by 2ATCaroline** [seanmcne/Microsoft.Xrm.Data.PowerShell#202]
Hi,

I'm trying to add a member to a marketinglist,
When I use add-crmassocation I get the error:
Associate is not supported for ListMember

I understand you need to use an AddMemberListRequest:
https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.addmemberlistrequest(v=crm.6).aspx

but I can't find a similar method in this powershell module, so I assume it's not implemented. 
Thanks in advance!
Caroline

**Comment by seanmcne** [comment]
Hi we don't have that wrapped in a message but you could do something like the following.  Just an FYI the xrm tooling connect (which is included in this module) allows you to execute "ExecuteCrmOrganizationRequest" so any message can technically be executed (you'll see that in our source code here on GitHub). 

``` powershell 
Import-Module Microsoft.Xrm.Data.Powershell

$AddMember = new-object Microsoft.Crm.Sdk.Messages.AddMemberlistRequest
$AddMember.EntityId = $RelatedEntityId 
$AddMember.ListId = $MarketingListId
$conn.ExecuteCrmOrganizationRequest($AddMember)
``` 
Hope this helps!
Sean

**Comment by amervitz** [comment]
@seanmcne this seems like a potential new function to add to simplify discovery and use of the module - if you agree feel free to create an enhancement issue and assign to me.

**Comment by seanmcne** [comment]
@amervitz yeah a little wrapper around this I think would be OK - the message is pretty simple which makes me hesitate a little, but making this it more accessible for this type of common function is also a good idea.  I could go either way :)
