### ISSUE TITLE
Import-CRMSolution V2.5 timout waiting for response.

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#207]
I have seen this occur off and on and have not been able to figure out a way to get around it.  This solution file size is 59K and this is not a default solution.

**Import Options:**
$maxWaitTimeInSeconds = 900
Import-CrmSolution -conn $conn -MaxWaitTimeInSeconds $maxWaitTimeInSeconds -SolutionFilePath $ZipFile -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -ActivatePlugIns:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true

**Script Output:**
Importing solution file C:\Clarety\DEV4\CRM\Dynamics2016\Solutions\Roles.zip into: https://dev-crm.ad.trs.state.tx.us/DEV4/XRMServices/2011/Organization.svc
VERBOSE: OverwriteCustomizations: True
VERBOSE: SkipDependancyCheck: True
VERBOSE: ImportAsHoldingSolution: False
VERBOSE: Maximum seconds to poll for successful completion: 900
VERBOSE: Calling .ImportSolutionToCrm() this process can take minutes...
VERBOSE: ImportId: 00000000-0000-0000-0000-000000000000
Import-CrmSolution : System.Management.Automation.RuntimeException: The 
request channel timed out while waiting for a reply after 00:02:00. Increase 
the timeout value passed to the call to Request or increase the SendTimeout 
value on the Binding. The time allotted to this operation may have been a 
portion of a longer timeout. => The HTTP request to 
'https://dev-crm.ad.trs.state.tx.us/DEV4/XRMServices/2011/Organization.svc' 
has exceeded the allotted timeout of 00:02:00. The time allotted to this 
operation may have been a portion of a longer timeout. => The operation has 
timed out

**Comment by jeffreynelson** [comment]
One other thing, when this error occurs it is does not appear to be captured within a try catch block.  I have coded in a retry with some information messages within the catch and they are not being processed.

`            $error.Clear()
            try {
			    Import-CrmSolution -conn $conn -MaxWaitTimeInSeconds $maxWaitTimeInSeconds -SolutionFilePath $ZipFile -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -ActivatePlugIns:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true
            } catch {
                # Repeat the import to capture a timeout issue
				write-error $Error[0].ErrorDetails
                try {
					write-warning "Attempting the import a second time."
    			    Import-CrmSolution -conn $conn -MaxWaitTimeInSeconds $maxWaitTimeInSeconds -SolutionFilePath $ZipFile -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -ActivatePlugIns:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true
                } catch {
                    write-error $Error[0].ErrorDetails
				    throw $Error[0].ErrorDetails
                    exit 4
                }
            }
`

**Comment by seanmcne** [comment]
Great info, can you try using the async import?  Import-CrmSolutionAsync

Params are the same but the method is different and if there is latency or issues causing the import to lag using the async import should help. I'm curious to see if you find this same issue occurring or not.

Sent from Outlook<https://aka.ms/qtex0l> on a phone
________________________________

**Comment by jeffreynelson** [comment]
I changed the call to import-crmSolutionAsync as follows 

Import-CrmSolutionAsync -conn $conn -MaxWaitTimeInSeconds 900 -SolutionFilePath ..\crm\Dynamics2016\Solutions\Roles.zip -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -ActivatePlugIns:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true

And received the following error

Import-CrmSolutionAsync : A parameter cannot be found that matches parameter name 'ActivatePlugIns'.

By changing the command as follows it seems to work, but how do you activate plugins?

Import-CrmSolutionAsync -conn $conn -MaxWaitTimeInSeconds 900 -SolutionFilePath ..\crm\Dynamics2016\Solutions\Roles.zip -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true -BlockUntilImportComplete:$true

Importing solution file ..\crm\Dynamics2016\Solutions\Roles.zip into: https://dev-crm.ad.trs.state.tx.us/DEV4/XRMServices/2011/Organization.svc
VERBOSE: OverwriteCustomizations: True
VERBOSE: SkipDependancyCheck: True
VERBOSE: ImportAsHoldingSolution: False
VERBOSE: Maximum seconds to poll for successful completion: 900
VERBOSE: Getting file contents
VERBOSE: ExecuteCrmOrganizationRequest with ExecuteAsyncRequest containing ImportSolutionRequest() this process can take a while...
VERBOSE: ImportId (asyncoperationid): e4cd11ba-1d27-e711-80eb-005056bb2db8
Import of file completed, waiting on completion of AsyncOperationId: e4cd11ba-1d27-e711-80eb-005056bb2db8
Waiting - 005 seconds of max: 900
Waiting - 010 seconds of max: 900
Waiting - 015 seconds of max: 900
Waiting - 020 seconds of max: 900
Waiting - 025 seconds of max: 900
Waiting - 030 seconds of max: 900
Waiting - 035 seconds of max: 900
Waiting - 040 seconds of max: 900
Waiting - 045 seconds of max: 900
Waiting - 050 seconds of max: 900
Waiting - 055 seconds of max: 900
Waiting - 060 seconds of max: 900
Waiting - 065 seconds of max: 900
Waiting - 070 seconds of max: 900
Waiting - 075 seconds of max: 900
Waiting - 080 seconds of max: 900
Waiting - 085 seconds of max: 900
Waiting - 090 seconds of max: 900
Waiting - 095 seconds of max: 900
Waiting - 100 seconds of max: 900
Waiting - 105 seconds of max: 900
Waiting - 110 seconds of max: 900
Waiting - 115 seconds of max: 900
Waiting - 120 seconds of max: 900
Waiting - 125 seconds of max: 900
Waiting - 131 seconds of max: 900
Waiting - 136 seconds of max: 900
Waiting - 141 seconds of max: 900
Waiting - 146 seconds of max: 900

Thanks

**Comment by seanmcne** [comment]
@jeffreynelson apologies, I must have missed a parameter let me make sure it's something we can just wire up.

**Comment by seanmcne** [comment]
Ok just did some checking, my humble opinion both ActivatePlugins and PublishWorkflows are poorly named.  Both of them mean the same thing and neither describes what the underlying feature/flag does. 

Both options do the same thing, both enable any SdkMessageProcessingStep's contained in the solution that aren't already enabled (workflows, plugins, etc).  

An easier correlation is: each of these flags are equivalent to checking this checkbox on import: 
![image](https://cloud.githubusercontent.com/assets/2292260/25305616/61f5573e-2744-11e7-826b-e1a498ad8b39.png)

**Comment by jeffreynelson** [comment]
Thanks for the help and quick response.

On Apr 22, 2017, at 8:17 AM, Sean McNellis <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok just did some checking, my humble opinion both ActivatePlugins and PublishWorkflows are poorly named. Both of them mean the same thing and neither describes what the underlying feature/flag does.

Both options do the same thing, both enable any SdkMessageProcessingStep's contained in the solution that aren't already enabled (workflows, plugins, etc).

An easier correlation is: each of these flags are equivalent to checking this checkbox on import:
[image]<https://cloud.githubusercontent.com/assets/2292260/25305616/61f5573e-2744-11e7-826b-e1a498ad8b39.png>

**Comment by jeffreynelson** [comment]
Ok, great info to have.  I will proceed  without the activatePlugin option.

On Apr 22, 2017, at 8:17 AM, Sean McNellis <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok just did some checking, my humble opinion both ActivatePlugins and PublishWorkflows are poorly named. Both of them mean the same thing and neither describes what the underlying feature/flag does.

Both options do the same thing, both enable any SdkMessageProcessingStep's contained in the solution that aren't already enabled (workflows, plugins, etc).

An easier correlation is: each of these flags are equivalent to checking this checkbox on import:
[image]<https://cloud.githubusercontent.com/assets/2292260/25305616/61f5573e-2744-11e7-826b-e1a498ad8b39.png>

**Comment by jeffreynelson** [comment]
I updated our process to use the Async import method and it seems to be working better.  The only conern that I have remaining is the following verbose message.  

Don't forget to publish customizations. 

We have the -PublishChanges flag set is there a different flag that we need to set or does the following combination of flags address this?

Import-CrmSolutionAsync -conn $conn -MaxWaitTimeInSeconds $maxWaitTimeInSeconds -SolutionFilePath $ZipFile -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -verbose:$true -ActivateWorkflows:$true -BlockUntilImportComplete:$true

**Comment by seanmcne** [comment]
It looks like that parameter wasn't wired up in the async import - I'm going to try a fix you want to test and verify it works? Honestly the parameter is just there to call "publish all" after the import if it was an unmanaged solution which can be done in script but I realize parity is ideal for this to work best. 

check out the code in this branch if you're able to test? 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/tree/SolutionImportAsyncPublishFlag-Fix

**Comment by jeffreynelson** [comment]
Thanks, I downloaded the latest and tested the same solutions as before but it looks like the manifest could not be loaded.  Here are the results. 

Importing solution file C:\Clarety\DEV4\CRM\Dynamics2016\Solutions\Roles.zip into: https://dev-crm.ad.trs.state.tx.us/DEV4/XRMServices/2011/Organization.svc
VERBOSE: OverwriteCustomizations: True
VERBOSE: SkipDependancyCheck: True
VERBOSE: ImportAsHoldingSolution: False
VERBOSE: Maximum seconds to poll for successful completion: 1800
VERBOSE: Getting file contents
VERBOSE: ExecuteCrmOrganizationRequest with ExecuteAsyncRequest containing 
ImportSolutionRequest() this process can take a while...
VERBOSE: ImportId (asyncoperationid): a91faa65-c829-e711-80ec-005056bb2db8
VERBOSE: Import of file completed, waiting on completion of AsyncOperationId: 
a91faa65-c829-e711-80ec-005056bb2db8
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 005 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 010 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 015 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 020 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 025 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
VERBOSE: Import Job status check FAILED this could be due to a bug where the 
service returns a 401. We'll allow up to 5 failures before aborting.
 - 030 seconds of max: 1800
VERBOSE: Manifest is null, checking job with data to get the manifest
Import-CrmSolutionAsync : Import Job status check FAILED 5 times this could be 
due to a bug where the service returns a 401. Throwing lastException:
At C:\Clarety\DEV4\Scripts\ps1\CRM-Import-Objects.ps1:345 char:8
+                 Import-CrmSolutionAsync -conn $conn -MaxWaitTimeInSeconds 
$maxWaitTimeInS ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Import-CrmSolutionAsync
 
Import-CrmSolutionAsync : AsyncOperation with ID: 
a91faa65-c829-e711-80ec-005056bb2db8 has encountered an exception: 
'AsyncOperation' entity doesn't contain attribute with Name = 'solutionname'.
At C:\Clarety\DEV4\Scripts\ps1\CRM-Import-Objects.ps1:345 char:8
+                 Import-CrmSolutionAsync -conn $conn -MaxWaitTimeInSeconds 
$maxWaitTimeInS ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Import-CrmSolutionAsync

**Comment by seanmcne** [comment]
Bummer I had wondered if this may be the case. Allow me to noodle on this a bit, I'll try to find some time today to look into this.

**Comment by seanmcne** [comment]
I gave this a little more thought, I really am not a huge fan of the auto publish but I completely realize the desire to have it.  I think I'm going to assume success and if the import job reports 'Completed - Succeeded' we'll assume whatever was uploaded was done successfully.  If Block Until Complete is true PublishChanges will be respected.  If Block Until Complete is True then it will be respected as long as the import is successful. 

I'll get the branch updated quick here and hopefully we'll finally have this working well - thanks for your patience!

**Comment by jeffreynelson** [comment]
Thanks,

I have added the publish to my script after the import completes issue.

Jeffrey S. Nelson
Practice Infrastructure Architect

M +1.503.504.2080
T + 1.360.212.3463

DXC Technology

dxc.technology<http://www.dxc.technology/> / Twitter<https://twitter.com/dxctechnology> / Facebook<https://www.facebook.com/DXCTechnology/> / LinkedIn<https://www.linkedin.com/company/dxctechnology>

Learn about DXC Technology.
dxc.technology<http://www.dxc.technology/>

**Comment by seanmcne** [comment]
Hey @jeffreynelson does the latest branch resolve things for you?  I'm getting ready to merge it and want to be sure you're seeing it work successfully.  Thanks again!

**Comment by petefer** [comment]
> Import-CrmSolution : System.Management.Automation.RuntimeException: The request channel timed out while waiting for a reply after 00:02:00.

I think the problem might be that the underlying connection timed out, not Import-CrmSolution.

Try adding -MaxCrmConnectionTimeOutMinutes to Get-CrmConnection.

**Comment by seanmcne** [comment]
You can also increase it this way (also keep in mind the network timeout will likely max out at 5 minutes).  Also, you can use the async method of import which uploads a batch and subsequently waits for it to complete. 

```powershell
$conn.OrganizationServiceProxy.Timeout = (New-TimeSpan -Minutes 5) 
```
and if connected with oAuth: 
```powershell
$conn.OrganizationWebProxyClient.ChannelFactory.Endpoint.Binding.ReceiveTimeout = (New-TimeSpan -Minutes 5)
$conn.OrganizationWebProxyClient.ChannelFactory.Endpoint.Binding.SendTimeout = (New-TimeSpan -Minutes 5)
```
