### ISSUE TITLE
Linking existing TFS Work Item

### ISSUE THREAD

**Issue by tjahnks23** [seanmcne/Microsoft.Xrm.Data.PowerShell#210]
Not so much an issue but a question. We have a TFS check-in policy for our project that requires a work item, PBI, or task to be linked to a check-in. When using the ExtractSolution script, this policy is essentially skipped and the build partially succeeds. Is there a way in the script I could link it to a work item that already exists in TFS. For instance, a permanent work item that is only in place to appease the check-in policy so that the build "Succeeded" as opposed to "Partially Succeeded"?

**Comment by seanmcne** [comment]
@tjahnks23 - can you give me a little more context?  When you say ExtractSolution do you mean Export-CrmSolution or do you mean solution packager in the SDK? Or is this specific to the TFS cmdlets?  

Thanks!

**Comment by seanmcne** [comment]
Feel free to re-open if you have further details - thanks!
