### ISSUE TITLE
Disable-CrmRecord

### ISSUE THREAD

**Issue by petefer** [seanmcne/Microsoft.Xrm.Data.PowerShell#214]
Hi,

Is there a way to disable a crm record with the existing crm cmdlets?

I'm trying to use Remove-CrmRecord to delete an SdkMessageProcessingStep, and judging by the error, I'm guessing I need to disable it before deleting it.

Thanks,
Pete

**Comment by seanmcne** [comment]
What error are you getting?  You should be able to execute the command unless there's maybe a dependency that needs to be removed first?

**Comment by petefer** [comment]
The error is "assembly must be registered in isolation" which spurious because I'm not registering a plugin. I tried disabling the step in the UI, but Remove-CrmRecord still returned the same error. I think I've figured it out -- delete works-- and the correct error message should be "user cannot delete SdkMessageProcessingStep -- requires Deployment Manager role"; sys admin role is not sufficient.

**Comment by ian-moore** [comment]
You can use Set-CrmRecordState to disable/enable plugins and workflows
