### ISSUE TITLE
Export-CrmSolution Throws uninformative exception if incorrect or insufficient parameters are specified. 

### ISSUE THREAD

**Issue by RIKIKU** [seanmcne/Microsoft.Xrm.Data.PowerShell#215]
The following error is received if `$response = [Microsoft.Crm.Sdk.Messages.ExportSolutionResponse]($conn.ExecuteCrmOrganizationRequest($exportRequest))`  returns nothing:
> Export-CrmSolution : System.Management.Automation.MethodInvocationException: Exception calling "WriteAllBytes" with "2" argument(s): "Value cannot be null.
> Parameter name: bytes" ---> System.ArgumentNullException: Value cannot be null.
> Parameter name: bytes
>    at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
>    at CallSite.Target(Closure , CallSite , Type , Object , Object )
>    --- End of inner exception stack trace ---
>    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> At line:1 char:13
>              Export-CrmSolution -conn $conn -SolutionName $records.Crm ...
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-CrmSolution

It would be better to throw a terminating error if $response -eq $null  for example "CRM server did not return a solution file. Check your parameters and try again."

**Comment by seanmcne** [comment]
this should be fixed now as of may 19th: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/commit/04e4e66a9ee3f4a34bb7fc9b8247961ea535920a 

and finalized / merged in #184 

![image](https://user-images.githubusercontent.com/2292260/28603154-0d92989e-7188-11e7-8039-fd5d4f8aa690.png)
