### ISSUE TITLE
Export-CrmSolution description for TargetVersion Parameter enhancement

### ISSUE THREAD

**Issue by RIKIKU** [seanmcne/Microsoft.Xrm.Data.PowerShell#216]
Could the parameter help either include what a valid version string looks like or provide a link to this [MSDN article](https://msdn.microsoft.com/en-us/library/dn689055.aspx#BKMK_ExportSolutionForVersion) that has a list of currently valid Target versions? 

For example:  

-  "Specify TargetVersion of exporting solution. See https://msdn.microsoft.com/en-us/library/dn689055.aspx for valid versions"

- "Specify TargetVersion of exporting solution. Valid versions are 7.0.0.0, 7.1.0.0, 8.0.0.0, 8.1.0.0, 8.2.0.0"

**Comment by kenakamu** [comment]
good idea. Could you make Pull Reqeust?
