### ISSUE TITLE
Import-CrmSolution AsyncOperationImportMethod switch

### ISSUE THREAD

**Issue by ansariwn** [seanmcne/Microsoft.Xrm.Data.PowerShell#217]
When calling the Import-CrmSolution with AsyncOperationImportMethod switch, the ActivateWorkflows and PublishChanges parameters are not set on Import-CrmSolutionAsync method. This does not allow users to Activate Plugins and Workflows if they choose to take this route to call Import-CrmSolutionAsync method.

I don't have permission to create a pull request hence raising the issue here.

**Comment by seanmcne** [comment]
@ansariwn in the meantime you can execute Import-CrmSolutionAsync directly with those parameters.  Understand that async is guaranteed to finish in a set # of seconds or minutes thus these parameters may not matter anyhow - unless you wait long enough.

**Comment by seanmcne** [comment]
Just noticed a typo, it should be "async is *not* guaranteed to finish in a set # of seconds or minutes" so it may not know when to execute a publish operation.

**Comment by ansariwn** [comment]
@seanmcne I don't think I have permission to raise a PR. If not, I will paste the code here for you to take forward. thanks.

**Comment by seanmcne** [comment]
@ansariwn I'm going to close this for now, please raise a PR or just paste in the code/approach into this issue and re-open it when you want us to take a look.  Thanks!
