### ISSUE TITLE
InsertOptionValueRequest  is not available in Microsoft.Crm.Sdk.Messages

### ISSUE THREAD

**Issue by mwolfaardt** [seanmcne/Microsoft.Xrm.Data.PowerShell#221]
Hi, I'm trying the following : 

```
$oppsetreq = New-Object Microsoft.Crm.Sdk.Messages.InsertOptionValueRequest
$oppsetreq.OptionSetName  = "new_salutation"
$label = New-Object Microsoft.Xrm.Sdk.Label("Mnr",1033)
$oppsetreq.label = $label
$oppsetreq.RequestName = "InsertOptionValue"
$conn.ExecuteCrmOrganizationRequest($oppsetreq)
```
``
but powershell is giving me the following : New-Object : Cannot find type **[Microsoft.Crm.Sdk.Messages.InsertOptionValueRequest]**: verify that the assembly containing 
this type is loaded.

**Comment by seanmcne** [comment]
Make sure you're running an Import-Module microsoft.xrm.data.powershell - that should make sure all the assemblies are loaded. Let me know if you are already doing that and I'll give it a shot myself (I'm without a pc right this min)

**Comment by mwolfaardt** [comment]
Hi, assembly already loaded. No luck

**Comment by seanmcne** [comment]
Try this once:  New-Object Microsoft.**Xrm**.Sdk.Messages.InsertOptionValueRequest

**Comment by mwolfaardt** [comment]
Great!!! Thank you so much
