### ISSUE TITLE
Change status of activity

### ISSUE THREAD

**Issue by mcboodle** [seanmcne/Microsoft.Xrm.Data.PowerShell#222]
Hey there.  

How would I go about changing the status of an activity? I'm struggling as I need to re-open some, but the code response is 'Cannot update Closed or Cancelled Activity'

Cannot update Closed or Cancelled Activity
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\microsoft.xrm.data.powershell\Microsoft.Xrm.Data.Powershell.psm1:758 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : Cannot update Closed or Cancelled Activity

**Comment by mwolfaardt** [comment]
You would need to use **Set-CrmRecordState**
Here is an example of how I changed the status of a Task 
`Set-CrmRecordState -EntityLogicalName "task" -Id "71D2FA6B-21BE-E511-80DD-6C3BE5A8DAD0" -StateCode 0 -StatusCode 2
`
Have a look at [https://technet.microsoft.com/en-us/library/dn531157.aspx](url) for status and state codes

**Comment by seanmcne** [comment]
Thanks for the sample!
