### ISSUE TITLE
New-CRMRecord -EntityLogicalName BusinessUnitNewsArticle thows not found in MetadataCache error

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#223]
I am able to use Get-CRMRecords -EntityLogicalName BusinessUnitNewsArticle with a filter and it returns the announcements without any issues.  However when I try and add an announcement it is failing with BusinessUnitNewsArticle was not found in the MetadataCache.

Do you know how I an create and then later on update an announcement?

Thank You

**Comment by mwolfaardt** [comment]
Based on the following : [https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming) announcement will be deprecated in the next release . Can you post your code please

**Comment by jeffreynelson** [comment]
Thanks, I changed my approach so that I am using a custom entity for this requirement.
