### ISSUE TITLE
Updating empty properties

### ISSUE THREAD

**Issue by mcboodle** [seanmcne/Microsoft.Xrm.Data.PowerShell#224]
Hi

I'm trying to update a field in a batch of records, but, where that field is 'null' I'm unable. It does work quite happily where there is a value in the field.

I've tried using -CrmRecord and individually named fields, as shown below, but neither way will work.

`Set-CrmRecord -CrmRecord $_ -PrimaryKeyField activityid;`

`Set-CrmRecord -conn $conn -EntityLogicalName new_financialreturnactivity -ID $_.activityid -PrimaryKeyField activityid -Fields @{"new_daysdue"=$days}`

I am returned:

`Exception setting "new_daysdue": "The property 'new_daysdue' cannot be found on this object. Verify that the property exists and can be set`

Any pointers please?1?!

Thanks!

**Comment by mwolfaardt** [comment]
Make sure that "new_daysdue" is in your data retrieval field queryset `Get-CrmRecords  -EntityLogicalName "new_financialreturnactivity" -Fields new_name,new_daysdue`

**Comment by mcboodle** [comment]
Hi, thanks, but I'm already doing that. I've tried just using Fetch and individual records, but I can't update the null fields either way. (This fetch is set to return only the null records for demonstration - records where the field is not null are updating ok)

```
 <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
            <entity name="new_financialreturnactivity">
                <attribute name="activityid" />
                <attribute name="subject" />
                <attribute name="createdon" />
                <attribute name="statuscode" />
                <attribute name="scheduledend" />
                <attribute name="new_daysdue" />
                <order attribute="subject" descending="false" />
                <filter type="and">
                <filter type="or">
                    <condition attribute="statecode" operator="eq" value="0" />
                    <condition attribute="statuscode" operator="eq" value="1" />
                </filter>
                <condition attribute="scheduledend" operator="not-null" />
                <condition attribute="new_daysdue" operator="null" />
                </filter>
            </entity>
            </fetch>
$TheRecords=Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -AllRows
```

**Comment by seanmcne** [comment]
Can you describe what you're trying to do?  I'm reading between the lines but it appears you have a record with an attribute and that attribute has a null value.  You're then trying to use set-crmrecord to set that same attribute to some determined value (like 5 or something).  Is that correct?

**Comment by mcboodle** [comment]
Hi
That's exactly what I'm trying to do!
Any help would be fantastic
Thanks
Mark

**Comment by kenakamu** [comment]
If it says new_daysdue, then i assume name could be wrong? could you double check the schemaname

**Comment by mcboodle** [comment]
Hi, the schema name is correct, and I can update it if it has an existing value, however if the existing value is null then I can't assign it a new value

**Comment by NickelBomber** [comment]
Greetings,

I'm also experiencing similar issues as @mcboodle of having a record available but being unable to update / set a value to a field that is currently null on the record. Here is a snippet of code I used for testing this:
```
$test = Get-CrmRecord -EntityLogicalName "application"  -Id $guid -fields applicant, applicantid
$test.applicantid = 5

Exception setting "applicantid": "The property 'applicantid' cannot be found on this object. Verify that the property exists and can be set."
At line:1 char:1
+ $test.applicantid = 5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```
I'd be interested in any tips available on this matter as well.

Thanks,
Nickel Bomber

**Comment by seanmcne** [comment]
Ken/@kenakamu please feel free to correct me on this, but I believe if you select a property that is null - the resulting record will not contain that property at all.  Is that correct? 

@NickelBomber Try this, since you know the field: 

```powershell
Set-CrmRecord -EntityLogicalName "application" -Id $guid -Fields @{"applicantid"=5}

```

**Comment by kenakamu** [comment]
You are right Sean. Maybe we should add parameter -IncludeNullValue for Get-CrmRecord?

**Comment by kenakamu** [comment]
I added -IncludeNullValue switch for Get-CrmRecord in v2.6. Please try to see if this works.

**Comment by raph91** [comment]
Hi

The same issue occurs with Get-CrmRecords. Is there a similar parameter?
I am able to get the field itself with Get-CrmRecord and the parameter "IncludeNullValue", but when I want to get it for multiple accounts (eg. for all accounts from a specific location), it does not work.
As a workaround, I have to iterate through all accounts and get the record again, so I read data twice which is not very efficient...

Any idea?

Thanks!
