### ISSUE TITLE
Add new cmdlet to list all entity logical and display names 

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#225]
helps when looking up a display name to get the schemaname, etc.  Current cmdlet is tough to get this data - same goes for a simple listing of all entities attributes.

**Comment by kenakamu** [comment]
Like this?

```powershell
Get-CrmEntityAllMetadata | select -property @{N='LogicalName';E={$_.logicalname}}, @{N='DisplayName';E={$_.DisplayCollectionName.UserLocalizedLabel.Label}} | sort DisplayName
```

**Comment by kenakamu** [comment]
As this is simple enough, I just added sample for Get-CrmEntityAllMetadata. If you still need function, please let me know.
