### ISSUE TITLE
Automating Business Closure entries

### ISSUE THREAD

**Issue by PvilleStang** [seanmcne/Microsoft.Xrm.Data.PowerShell#227]
How would one go about entering business closures for CRM?  In anticipation of a rollout, we are trying to automate this for our new org deployments, and I haven't seen an entity that correlates with Business Closures and haven't seen anything in System Settings.

**Comment by seanmcne** [comment]
I did find a short blog on retrieving the settings from CRM 

https://community.dynamics.com/crm/b/salimadamondynamicscrm/archive/2013/05/21/retrieving-business-closure-dates-from-dynamics-crm

It would appear that you could retrieve the business closure calendar ID from the organization table/entity and then query and add or remove from that calendar or set calendar rules. 

You can use get-crmrecords to pull in the calendar and investigate - unfortunately we don't have any helpers around this but it appears to be as accessible as any other entity.
