### ISSUE TITLE
Connection to CRM11

### ISSUE THREAD

**Issue by simonwhittington** [seanmcne/Microsoft.Xrm.Data.PowerShell#228]
Hi

I'm trying to connect to a Dynamics 365 instance located on crm11.dynamics.com but that region is not listed in InteractiveMode.

I've tried to connect using Connect-CrmOnline and adding the server URL but I get 'Unable to Login to Dynamics CRMOrganizationServiceProxy is nullOrganizationWebProxyClient is null'.

Could you offer any advice to get around this.

Many thanks

**Comment by seanmcne** [comment]
@simonwhittington crm11 is "United Kingdom" from the list of options in the interactive mode dialog. 

Europe, Middle East and Africa is CRM4.dynamics.com & United Kingdom is CRM11.dynamics.com

**Comment by simonwhittington** [comment]
Many thanks for the reply.

I believe that I have downloaded the latest version but United Kingdom is not available from the dropdown (on Advanced) and doesn't appear to check it if I select 'Don't Know'.

Regards,

Simon

**Comment by seanmcne** [comment]
I'm thinking you might need to update, I just confirmed by importing the latest off powershell gallery 

If you used powershell gallery and what to update try this:  
Update-Module Microsoft.Xrm.Data.Powershell -Force -Verbose

If you did not use powershell gallery and want to switch to that as your source try: 
Install-Module Microsoft.Xrm.Data.Powershell -Scope CurrentUser -Verbose

![image](https://user-images.githubusercontent.com/2292260/28544597-642b04d4-7089-11e7-8683-bf2815453b02.png)

**Comment by simonwhittington** [comment]
Many thanks for your assistance on this, I've now managed to connect.

I've got a new issue now when trying to create a contact and associate it with an account but I will check my facts first and possible log a new issue.

Thanks again

Simon
