### ISSUE TITLE
Adding a Contact to an Account

### ISSUE THREAD

**Issue by simonwhittington** [seanmcne/Microsoft.Xrm.Data.PowerShell#229]
Hi

I'm a little new to this but I'm trying to script the creation of a contact which is then associated with a Parent Account. I can create the contact (user) without issue but I'm having issues linking it to the parent account (company). 

I believe that the field used to associate it with the company is 'parentcustomerid' but I get "An unexpected error occurred." if this is included. Removing it from the field list adds the contact but means I have to link it to the company Account manually through a browser.

Currently I am using...

$contactId = New-CrmRecord -conn $conn -EntityLogicalName contact -Fields @{"lastname"=$lastname;`
                                                                "firstname"=$firstname;`
                                                                "emailaddress1"=$emailaddress;`
                                                                "telephone1"=$telephone;`
                                                                "address1_line1"=$address1line1;`
                                                                "address1_line2"=$address1line2;`
                                                                "address1_line3"=$address1line3;`
                                                                "address1_city"=$address1city;`
                                                                "address1_stateorprovince"=$address1stateorprovince;`
                                                                "address1_postalcode"=$address1postalcode;`
                                                                "address1_country"=$address1country;`
                                                                "parentcustomerid"=$companyname
                                                                }
I've tried all sorts of other ways of resolving it, such as creating the contact and then doing a Get-Record and a Set-Record with the additional field

Set-CrmRecord -conn $conn -CrmRecord $contact -Fields @{"parentcustomerid" = "ECA74DB9-795F-E711-80F8-70106FAAEAD1"} 

I also tried using the actual Account name but seem to get the same issue which is "Parameter set cannot be resolved using the specified named parameters.". I've tried updating other fields as well but it seems if the field is empty then it generates the same error. If the field is already populated then it updates but if it is empty then it cannot be retrieved or updated.

As I said, I am new to Dynamics, so probably making an obvious mistake here. We are trying to get add this process into our customer provisioning scripts so that new users are added straight into the database.

Any assistance would be appreciated.

Many thanks

Simon

**Comment by seanmcne** [comment]
Hey Simon, thanks for hanging in there - and you're very close! 

For references like this the platform needs to know the related entity type as well as the ID (an entityreference).  Here's one of your above sample with the slight alteration.  This will work on create or update - the update was just a bit easier as you already had the id present. 

```powershell
$parentAccount = new-crmentityreference -EntityLogicalName account -Id "ECA74DB9-795F-E711-80F8-70106FAAEAD1"

Set-CrmRecord -conn $conn -CrmRecord $contact -Fields @{"parentcustomerid" = $parentAccount}
```

**Comment by simonwhittington** [comment]
Many thanks for the advice. By adding the new-crmentityreference command I was able to create the new contact and link it with the account in one process....

############################################
$parentAccount = new-crmentityreference -EntityLogicalName account -Id "ECA74DB9-795F-E711-80F8-70106FAAEAD1"

$contactId = New-CrmRecord -conn $conn -EntityLogicalName contact -Fields @{"lastname"=$lastname;`
                                                                "firstname"=$firstname;`
                                                                "emailaddress1"=$emailaddress;`
                                                                "telephone1"=$telephone;`
                                                                "address1_line1"=$address1line1;`
                                                                "address1_line2"=$address1line2;`
                                                                "address1_line3"=$address1line3;`
                                                                "address1_city"=$address1city;`
                                                                "address1_stateorprovince"=$address1stateorprovince;`
                                                                "address1_postalcode"=$address1postalcode;`
                                                                "address1_country"=$address1country;`
                                                                "parentcustomerid" = $parentAccount
                                                                }

############################################

I couldn't initially get your set-crmrecord command to work but tweaked it to listed below was successfull.

Set-CrmRecord -conn $conn -id $contactId -Fields @{"parentcustomerid" = $parentAccount} -Verbose -EntityLogicalName contact

If I can really try and push my luck and ask another question. I can't seem to work out how to look up an account using the name, such as 'Microsoft'. I want to be able to use that command to then obtain the ID of the company account which can then be pushed into my contact creation. Get-CRMrecord requires -ID and I can't seem to work out how to get around it. I can obviously just manually make a list of them by other means and set it in the script but it would be a little slicker if it could look it up. 

Many thanks again for the assistance.

Simon

**Comment by seanmcne** [comment]
Thanks Simon - I think I wrote the entity reference part of it, got distracted, and pressed comment before correcting the parameter names - sorry about that :) 

For your scenario try this: 
```powershell 
#you can put this into a powershell function that would accept the name and 
#return the entity reference for you - this would allow you to use it inline
$accounts = get-crmrecords -entitylogicalname account -
#it'd be recommended to check for multiple results 
$accountRef = new-CrmEntityReference -EntityLogicalName account -Id $accounts.CrmRecords[0].accountid 

#update your contact here using $accountRef 

```

We have a couple of features that I'd like to get in but we haven't had the time yet: 
- get an entityReference from a Crm Record, it seems simple but there's some disagreement as to the best way to handle this longer term to help avoid breaking changes in the future :)  
- Allow alternate keys (this is one that may take some additional work)

**Comment by simonwhittington** [comment]
Many thanks, I'll give it a go and see how I get along.

Appreciate the assistance and look forward to future updates!
