### ISSUE TITLE
Create a develop branch for versions 2.7 and above 

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#243]
Create a branch that we will merge v.next into before pushing into master.  
Master will be in sync with the current released/in-flight module and develop will be v.next.  

When we release a new update we will merge develop into Master (they will then be in sync) until the next enhancement or bug - all updates/changes will go to develop until a release takes place. ''

Let me know if you agree @kenakamu 

Thx!

**Comment by amervitz** [comment]
What is prompting this new branch? Is there a problem with the way changes are currently being made to master?

**Comment by seanmcne** [comment]
Nope, no problems, I think we should keep some separation to better track things (what's in flight vs released).

**Comment by kenakamu** [comment]
It's just a policy and i am okay with it, but all the pull request needs to point the branch which is not common for some people. So maybe we should stick with master and use Tag to mark release as we did before?

**Comment by amervitz** [comment]
To quote [one of your own](https://blogs.msdn.microsoft.com/bharry/2017/05/24/the-largest-git-repo-on-the-planet/#comment-331215), I would suggest something closer to this:

>  All works happens as close to master as possible and we have no (or very few – count them on 1 hand) long term development branches other than master. People create short lived topic branches, do their work and merge to master quickly. We “branch for release” by creating a new branch for each release we ship and all the servicing work for the release happens in the release branch.

I'm thinking all PRs would go to master, which is good for visibility into the project's activity by seeing commits to the master branch. Branches would be created for individual features if they're very large or need to be tested outside of PRs, but ultimately should be merged to master asap, and branches created for releases to achieve stabilization and maintenance.

**Comment by seanmcne** [comment]
I think this ultimately comes down to personal preference - even if we went with a develop branch (which is a common method as well) you can merge all commits (versus squash and merge).  I'm fine sticking with tagged releases for now - I just thought it would be nice to have master represent whats in flight vs. new as it's more accessible to folks less familiar with Git.  

For now, it's less work and time to keep it the same so let's stick with what we have for now Ken :)  

I've been doing some testing on the v3 Xrm Tooling binaries and I think we'll be able to quickly move on to 2.7 for assembly updates as well as some new options in connect-crmonline.
