### ISSUE TITLE
Set-CRMUserMailBox erros with a valid email address

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#246]
When the following commands execute I am getting a validation error on the email address.  The passed in email address is a valid email address.

$EmailAddress = "noreply@my.email.com"
Set-CrmUserMailbox -conn $conn -EmailAddress $EmailAddress -Verbose -ScheduleTest -ApproveEmail 

Error:
Set-CrmUserMailbox : Cannot validate argument on parameter 'EmailAddress'. The argument "/NoReply@trs.texas.gov/" does not match the 
"/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/" pattern. Supply an argument that matches 
"/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/" and try the command again.
At line:1 char:46
+ Set-CrmUserMailbox -conn $conn -EmailAddress ${EmailAddress}.Trim() -Verbose -Sc ...
+                                              ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-CrmUserMailbox], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-CrmUserMailbox

**Comment by jeffreynelson** [comment]
Sorry, I forgot to mention that this is being tested with version 2.6.

**Comment by seanmcne** [comment]
Oh yeah, this check is too restrictive. 

I can look at this hopefully this week and we can get you some patched code to hack in. I'm almost thinking we can forgo validation but this article has a novel approach we can use in powershell. 

https://stackoverflow.com/questions/5342375/regex-email-validation

**Comment by jeffreynelson** [comment]
I used the link you sent and removed the validateion parm option.  Then added a try catch block to validate the email address using the system.net.mail.mailaddress class.  It is working for me for now.  I would be glad to retest once an update is available.

try {
    $ValidEmailAddress = New-Object -type System.Net.Mail.MailAddress -ArgumentList $EmailAddress
    $EmailAddress = $ValidEmailAddress.Address
} catch {
    throw "An invalid email address was entered."
}

Thanks

**Comment by seanmcne** [comment]
👍 we'll get this updated soon and out with our next release (hopefully as soon as the v3 xrm tooling dlls ship).

**Comment by seanmcne** [comment]
#255 
I found a better pattern, however, I think we should probably let the platform decide if it's a valid email or not (for now). 

If we need validation in the future we should do something like this:  https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format
