### ISSUE TITLE
Feature: return the status of the server side synchronization

### ISSUE THREAD

**Issue by kenakamu** [seanmcne/Microsoft.Xrm.Data.PowerShell#25]
It will be great to have a powershell script which can return the status of the server side synchronization.

In particular the error logs on failures

Idea from ;venkatkrk

**Comment by andrescolodrero** [comment]
agree @kenakamu :)

**Comment by seanmcne** [comment]
@kenakamu, let's get a list of entities and attr's that are open to retrieveMultiple and contain data that is interesting to gauging status of the mailbox being enabled or disabled along with grabbing the trace/alert info for a given users mailbox (which may require impersonation).  I have this on my list of things to do as well, let me know where you're at with this so we don't duplicate efforts :)

**Comment by kenakamu** [comment]
For this one, I need your idea. For "Alert" log, we can get it by using following code.

```powershell
$trace = Get-CrmRecords tracelog level eq 3 -AllRows -Fields *
```
We can also filter by mailbox
```powershell
$mailbox = Get-CrmRecords mailbox ownerid eq (Get-MyCrmUserId) -Fields *
$t = Get-CrmRecords tracelog regardingobjectid eq $mailbox.CrmRecords[0].mailboxid -AllRows -Fields *
```

So my question is, what kind of data we want to get? and any good function name candidate?
For example, Get-CrmAlerts and params could be Get-CrmAlerts -conn $conn -Level Error | Warning | Information | All -MailboxId -$MailboxId
or Get-CrmServerSideSynchronizationStatus -conn $conn and returns status and succeeded and failed mailboxes as list?

**Comment by seanmcne** [comment]
there is new reporting available for this and dashboards that I think resolve this, at least for now.  Reopen if needed or desired.  Thx!
