### ISSUE TITLE
How to save Get-CrmRecords result as a file for later import using Set-CrmRecords?

### ISSUE THREAD

**Issue by gazzzmo** [seanmcne/Microsoft.Xrm.Data.PowerShell#250]
Hi. I'm attempting to use Get-CrmRecords / Set-CrmRecord to move data between instances. Is this possible? The following code I have doesn't work:

```
## Export
if ($CrmEntities.Length -gt 0){
    # Export the entity records
    foreach ($CrmEntity in $CrmEntities)
    {
        Write-Host "Exporting all records from the $CrmEntity entity to XML files"
        $CrmRecords = Get-CrmRecords -EntityLogicalName $CrmEntity -AllRows -conn $conn -Fields *
        $OutPath = Join-Path -Path $FilePath -ChildPath ($CrmEntity + ".xml")
        Export-Clixml -InputObject $CrmRecords -Path $OutPath
    }
}
## Import
if ($CrmEntities.Length -gt 0){
    # Import the crm entity files
    foreach ($CrmEntity in $CrmEntities)
    {
        Write-Host "Importing all records from the $CrmEntity entity XML file"
        $InPath = Join-Path -Path $FilePath -ChildPath ($CrmEntity + ".xml")
        $CrmRecords = Import-Clixml -Path $InPath
        foreach ($CrmRecord in $CrmRecords.Crmrecords)
        {
            Set-CrmRecord -conn $CrmConnection -CrmRecord $CrmRecord -Upsert
        } 
    }
}
```

I'd really appreciate any help you could offer on how to get this working.
Thanks - Gareth

**Comment by seanmcne** [comment]
try this: 

NOTE: One bummer is that the id won't be the same unless you set the new records contactid attribute equal to the source id.  The reason for this originally was for cloning records within a single instance - you could expand it locally (for now) and add a switch parameter to preserve the id maybe.  In either case, the code below functions with v2.6 (I just tested it). 

```powershell
$connSource = connect-crmonline -ServerUrl sourceOrg.crm.dynamics.com
$connDest = Connect-CrmOnline -ServerUrl destOrg.crm.dynamics.com
$contacts = Get-CrmRecords -conn $connSource -EntityLogicalName contact -Fields firstname,lastname -TopCount 1
$newContactGuid = New-CrmRecord -conn $connDest $contacts.CrmRecords[0]

get-crmrecord -conn $connDest -entitylogicalname contact -id $newContactId
```

**Comment by seanmcne** [comment]
I tried adding a new switch now to preserve the existing id - you can get the psm1 in this branch: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/tree/seanmcne-PreserveExistingid 

give it a try by replacing the psm1 with the above branches psm1 (as a test) and use the modified snip of code here: 
```powershell 
$newContactGuid = New-CrmRecord -conn $connDest $contacts.CrmRecords[0] -PreserveCrmRecordId
```

**Comment by seanmcne** [comment]
Had a few extra minutes and tried it out, seems to work well with the PreserveCrmRecordId switch
