### ISSUE TITLE
Add a new cmdlet for Publishing Duplicate Detection Rules

### ISSUE THREAD

**Issue by pmalecka** [seanmcne/Microsoft.Xrm.Data.PowerShell#257]
Hi Sean,

would it be possible to add a new cmdlet that would allow for publishing all/selected duplicate detecion rules in the system?

I'm thinking that it might be helpful if the script could optionally block until all the rules are published.

Thanks,
Peter

**Comment by seanmcne** [comment]
I could look to do that, the code is pretty trivial (using a: [Un]PublishDuplicateRuleRequest).  If we did a new wrapper/cmdlet we could integrate a retrieveMultiple to find the rule by entity type and/or name and issue the following requests: 

```powershell
$DuplicateRulePublishRequest = New-Object Microsoft.Crm.Sdk.Messages.PublishDuplicateRuleRequest
$DuplicateRulePublishRequest.DuplicateRuleId = "duplicationdetectionruleId" 
$conn.ExecuteCrmOrganizationRequest($DuplicateRulePublishRequest)
if($conn.LastCrmException -ne $null)
{
        throw LastCrmConnectorException($conn)
}
```

Likewise the unpublish would be: 
```powershell
$DuplicateRuleUnPublishRequest = New-Object Microsoft.Crm.Sdk.Messages.UnPublishDuplicateRuleRequest
$DuplicateRuleUnPublishRequest.DuplicateRuleId = "duplicationdetectionruleId" 
$conn.ExecuteCrmOrganizationRequest($DuplicateRuleUnPublishRequest)
if($conn.LastCrmException -ne $null)
{
        throw LastCrmConnectorException($conn)
}
```

**Comment by seanmcne** [comment]
Closing due to limited engagement - if this works and you would like us to proceed in the main module let me know.  Otherwise please use, test, and send us a PR to the sample repo to share with others.  Thanks!

**Comment by DarrenSmallwood** [comment]
I have tested both of the solutions above and can confirm that they work. IT would be nice if they could be put into a cmdlet.
