### ISSUE TITLE
Get-CrmRecordsByFetchXml does not return null columns

### ISSUE THREAD

**Issue by NickPl** [seanmcne/Microsoft.Xrm.Data.PowerShell#258]
This issue is very specific. I am requesting to add a -IncludeNull to the Get-CrmRecordsByFetchXrml function. I will add the feature whenever I have the time. Here's the reason.

I used the function to build a script that export data into a csv file. The view I used contained a lot of columns and to export I used the Export-Csv command. It work great in test and was quite simple to make.

I discovered a problem after some time when some columns were randomly missing from the output file. After debuging I concluded that the function is returning the data correctly but it does not return a column if it's empty. So, in the array all objects are not created equal. Thus, to determine the columns to create in the file, Export-Csv checks ONLY the first object of the list. Which cause the instability in the output file. 

I traced the root of the problem to Dynamics itself. But still, I'd like the script to auto complete the objects it's creating based on the fetchXml used. I solved the problem on my end by doing that in the module. I will share the fix soon.

**Comment by seanmcne** [comment]
Thanks for sharing Nick!  @kenakamu recently put a similar fix in for get-crmrecord if you want to reference that as well.

**Comment by kenakamu** [comment]
I will add this to next version.

**Comment by kenakamu** [comment]
Actually this issue should have been addressed in previous version. Could you double check or let me know the repro steps.

**Comment by seanmcne** [comment]
@NickPl please let us know if this is working now in 2.6 - I'll close this for now but please re-open if you're still able to reproduce this (and if you could include a simple scenario/sample that would help as well).
