### ISSUE TITLE
Disable workflow through Set-CrmRecord

### ISSUE THREAD

**Issue by andrewbright** [seanmcne/Microsoft.Xrm.Data.PowerShell#259]
When I set values for 2 fields to deactivate my workflow, using this script. 
` ` `powershell
$workflowTest = Get-CrmRecord workflow <Guid> statecode, statuscode
$workflowTest.statecode = 0
$workflowTest.statuscode = 1 
Set-CrmRecord $workflowTest
Get-CrmRecord workflow <Guid> statecode, statuscode, name
` ` `
I get this error:
> Cannot update a published workflow definition.
> C:\Users\username\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.6\Microsoft.Xrm.Data.Powershell.psm1:745 sign:9
> +         throw $conn.LastCrmException
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], FaultException`1
>     + FullyQualifiedErrorId : Cannot update a published workflow definition.

How do I get disable workflow without  error, using powershell script?

**Comment by smithia30** [comment]
Try using `Set-CrmRecordState` instead of `Set-CrmRecord`.

**Comment by andrewbright** [comment]
When I use Set-CrmRecordState, I'll get this error:
```
Set-CrmRecordState $workflowTest Inactive Inactive
ScriptHalted
C:\Users\username\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.6\Microsoft.Xrm.Data.Powershell.psm1:2376 sign:4
+             throw $conn.LastCrmException
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by smithia30** [comment]
It looks like you are going the right direction.

Workflows can only be in Draft or Activated statecode/statuscode:
```
statecode: 0 (Draft)
statecode: 1 (Activated)

statuscode: 1 (Draft)
statuscode: 2 (Activated)
```

Since StateCode and StatusCode are required and positional, any of the following should work:

```
Set-CrmRecordState $workflowTest 0 1
Set-CrmRecordState $workflowTest Draft Draft
Set-CrmRecordState $workflowTest -StateCode 0 -StatusCode 1
Set-CrmRecordState $workflowTest -StateCode Draft -Statuscode Draft
```

**Comment by yash27gupta** [comment]
Hi smithia30,

This code is not working for workflow entity. could you pls run the script and upload the result.

**Comment by amitvirendra** [comment]
Function Deactivate-Workflow{
	param
    (
        [String]$Id,
        $conn
    )
	try {
		#Create-ConnectionToCRM
		$id = [guid]$Id
        $workflow = Get-CrmRecord workflow $id statecode, statuscode -conn $conn
		$fields = @{
				"statecode" = [Microsoft.Xrm.Sdk.OptionSetValue]0;
		}
        Set-CrmRecordState $workflow -StateCode 0 -StatusCode 1 -conn $conn

	} catch {
		$err = $Error[0].Exception
		Write-Host "Error: $err"
	}
}

**Comment by 10eggs** [comment]
Why this issue is closed if there is no valid solution here?

Same as @andrewbright, I'm getting the following exception:

$conn.LastCrmException.

Any ideas will be more than welcome!
