### ISSUE TITLE
Set-CRMRecord does not allow for updating the mailbox 

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#260]
**Command:**
set-crmrecord -EntityLogicalName mailbox -id $Record.mailboxid -fields @{processanddeleteemails = $true} 

**Response**
The Delete Emails after Processing option cannot be set to Yes for user mailboxes.

**Question:** Does anyone know how we can update a mailbox the email is deleted once it is processed by CRM 2016?

**Comment by seanmcne** [comment]
What this setting does is: when an email is tracked in CRM it will be deleted from the mailbox. 

This feature should only apply to queues and forward mailboxes and not user mailboxes.
