### ISSUE TITLE
Any nuget package for this module ?

### ISSUE THREAD

**Issue by carfup** [seanmcne/Microsoft.Xrm.Data.PowerShell#263]
Hello Sean,

I'm using your module to deploy webresources / plugins via CI in VSTS.
I wanted to know if it would be possible to package your module into a nuget one so i wouldn't have to embedded the entire module in my source repository as it's currently done.
(I don't have the possibility to install the module in the GAC with the agent, that's the issue).
I saw there were 2 nuget packages : Microsoft.CrmSdk.XrmTooling.CrmConnector.PowerShell and Microsoft.CrmSdk.XrmTooling.CoreAssembly but i'm not able to make it works properly.

Thanks a lot,
Clément

**Comment by seanmcne** [comment]
Clement, would you be able to install the package from the powershell gallery?   Using install-module Microsoft.xrm.data.powershell -Scope CurrentUser 

https://www.powershellgallery.com/packages/Microsoft.Xrm.Data.Powershell/

**Comment by carfup** [comment]
Hello Sean,
If i'm not mistaken the Install-Module pushed the module to the local user modules or GAC.
I can't do that.
All i'm able to do with my "special scenario" is to download the files from the module and put them in my drop artifact during the build step and then Import-Module with the relative path during the execution of my powerhsell script in the release step.

**Comment by carfup** [comment]
My bad, i guess i can make it work with the Save-Module command.

I will figure this out, this way!

Thanks a lot Sean

**Comment by seanmcne** [comment]
Install module should be allowed if type scope it locally - it uses a local user only store. I haven’t had a min to test but I believe that should work.

**Comment by seanmcne** [comment]
Here's an example of how to install-module using currentUser scope: https://twitter.com/seanmcne/status/958192903867813888
