### ISSUE TITLE
MapFieldTypeByFieldValue error when creating new system user

### ISSUE THREAD

**Issue by jonckhje** [seanmcne/Microsoft.Xrm.Data.PowerShell#264]
Hey guys,
I'm very, véry happy to finally have found a way to add system users from a specific OU in AD. All seems to be working fine, up to the error below.
Anything I can do to get this up and running?

thanks in advance,
Jeroen
Holland

Creating CRM User mydomain\JSmith
MapFieldTypeByFieldValue : Cannot bind argument to parameter 'Value' because it is null.
At C:\Users\me\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell
.psm1:257 char:62
+             $newfield.Type = MapFieldTypeByFieldValue -Value $field.Value
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [MapFieldTypeByFieldValue], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,MapFieldTypeByFieldValue

Object reference not set to an instance of an object.
At C:\Users\me\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell
.psm1:273 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : Object reference not set to an instance of an object.

**Comment by seanmcne** [comment]
Are you using a specific sample or script when doing this?  I suspect you're setting some parameter in a set-crmrecord command supplied by some value in your script and that value is Null for some reason.  Are you getting this on every user?  One tip would be to print/log (in your script) each command when you create the new user along with the parameter values to figure out what might be Null.

**Comment by seanmcne** [comment]
Could you try again with the latest commit to the repo?  Ken's PR #266 I hope will address this issue.  Thanks!

**Comment by jonckhje** [comment]
Aced that, Sean! Sorry for my late response, but with this repo, troubles seem to be over.
Thanks!

**Comment by seanmcne** [comment]
👍  Thanks for the quick response!
