### ISSUE TITLE
Export-CrmSolution - needs the $MaxWaitTimeInSeconds variable...

### ISSUE THREAD

**Issue by dtate22** [seanmcne/Microsoft.Xrm.Data.PowerShell#265]
Please consider adding a parameter to the Export-CrmSolution for session timeouts.
- Currently, I can Import with a TimeOut set, but I cannot Export with a TimeOut set
- As a consequence, solutions that take more than 2 minutes cannot be exported with this tool.

**Comment by seanmcne** [comment]
the timeout is based on the connection (XRM Tooling) to increase the timeout try this: 
- Connect to CRM 
- Run: Set-CrmConnectionTimeout and set the timeout to 5 minutes 
- Now run your export - the export will wait on the service call to time out (It isn't something we can control on a request by request basis when using xrm tooling). 

let me know if this work - thanks!

**Comment by dtate22** [comment]
Thanks for the additional insight.

**Comment by segovof** [comment]
I'm using version 2.8.1.3, the Set-CrmConnectionTimeout is not working on the Export-CrmSolution, it stay on the 2 minutes, is there another way to force or set the Timeout for the Solution Export?

**Comment by dtate22** [comment]
I'm sorry for the delay...
- If I remember how I resolved this last year...

The PowerShell didn't seem to respond like I needed it to, so if I remember correctly.
- I wrote a Console app using the Export-CrmSolution command from the SDK (message from SDK)
- I then could control all aspects of time and timeout using the SDK
- I set the timeout in the app.config of the connection and everything else worked just fine.

Also, I remember looking at the SDK and running the SDK project that will allow you to import and export solutions - I think the timeout worked on that as well - it just seemed like PowerShell BACK THEN didn't or wasn't honoring it.

..Derrick Tate..

**Comment by ryanlraines** [comment]
@seanmcne @dtate22  Was this ever really addressed? I'm experiencing this behavior on 2.8.5.  

This suggestion isn't working for me either. 

> the timeout is based on the connection (XRM Tooling) to increase the timeout try this:
> 
> * Connect to CRM
> * Run: Set-CrmConnectionTimeout and set the timeout to 5 minutes
> * Now run your export - the export will wait on the service call to time out (It isn't something we can control on a request by request basis when using xrm tooling).
> 
> let me know if this work - thanks!

**Comment by dtate22** [comment]
Sorry for the delay…

The problem you are experiencing could be because of 2 or 3 timeouts if I remember correctly…


  *   If you are on Premises – SQL Server  / database timeout
     *   SQL Timeout

Other than that, there are 2 other timeouts

  *   API/Connection Timeout (cloud only) – 30 secs to 2 mins
  *   Web service timeout (cloud only) – 1 to 2 mins

I played with all 3 timeout periods until I got the desired behavior
If you play with all 3 until you get the desired affects you should be happy.

In order to get at the API – Connection, I played with the C# code.
In order to get at the Web Service timeout – I had to play with .config files

I hope this helps,
..Derrick Tate..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ryanlraines** [comment]
@dtate22 Thanks for the reply. 

I'm connecting via the Powershell Module.  How would I increase the timeout value there?

**Comment by dtate22** [comment]
I took a quick look to see if I had the solution on hand…

  *   I don’t have it here with me.

Sorry – what you have is the best I could do on short notice.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jeffreynelson** [comment]
We have a solution that takes some time to import.  Right before we import that solution we are executing the following.  Then after the solution is imported we are resetting the timeout back to 5 minutes.

write-host "Setting the max timeout to 3600 for the $solution.name solution."
[int]$maxWaitTimeInSeconds = 3600
Set-CrmConnectionTimeout -TimeoutInSeconds $maxWaitTimeInSeconds

**Comment by jeffreynelson** [comment]
For completeness here is our connection to CRM and setting the timeout

$global:conn = Get-CrmConnection -Credential $creds -ServerUrl $CRMWebSite -OrganizationName $CRMOrginazation -verbose:$Verbose -ErrorVariable $errmsg -WarningVariable $warnmsg -ErrorAction Stop -WarningAction SilentlyContinue -MaxCrmConnectionTimeOutMinutes ([timespan]$CRMTimeOut).TotalMinutes

#increase the CRM Connection timeout to the passed in time-out or 30 minutes
Set-CRMConnectionTimeout -conn $Global:conn -TimeoutInSeconds ([timespan]$CRMTimeOut).TotalSeconds -Verbose

**Comment by seanmcne** [comment]
Please see #421

**Comment by Srinivas-avarad** [comment]
Still the above issue exists, if I set timeout connection, then the export-crmSolution command gets hanged until it gets time out(whatever custom timeout I am setting) but not exporting the zip file

Any solutions which are getting finished in lesser than 2 minutes are working absolutely fine.

Any workaround have found on this, please share, would be a great help..
