### ISSUE TITLE
is it possible to remove team membership from a user

### ISSUE THREAD

**Issue by cotralis** [seanmcne/Microsoft.Xrm.Data.PowerShell#269]

**Comment by seanmcne** [comment]
Yep, it's pretty easy by following a pattern similar to the sample on adding marketing list members.  Here's a quick example I created by following that pattern: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/tree/master/Microsoft.Xrm.Data.PowerShell.Samples/TeamMembership

**Comment by cotralis** [comment]
Thanks for the quick reaction. but i can ADD  memberships i ment ho to REMOVE memberschips from teams. do you know a solution?

**Comment by cotralis** [comment]
@cotralisThanks for the quick reaction. but i can ADD memberships i ment ho to REMOVE memberschips from teams. do you know a solution?

**Comment by seanmcne** [comment]
Yep it should be exactly the opposite: https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.removemembersteamrequest.aspx 

I'll copy and paste this into a second sample - i used the marketing list add as a template and must have got 'add' vs remove stuck in my head :) 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/TeamMembership/RemoveMemberFromTeam.ps1 

```powershell
Import-Module Microsoft.Xrm.Data.Powershell

#ID of the team you want to remove members from (or remove a single member)
$TeamId = "107E563B-7D21-40A5-AF6B-C8975E9C3860"

$teamMembers = @(); 
$teamMembers += @("C69F9B23-F3B2-403F-A1CF-C81FEF71126F")
$teamMembers += @("E563BB21-E3E4-A1CF-40A5-C8975E9C3860" )

$AddMember = new-object Microsoft.Crm.Sdk.Messages.RemoveMembersTeamRequest
$AddMember.TeamId = $TeamId
$AddMember.MemberIds = $teamMembers 

$conn.ExecuteCrmOrganizationRequest($AddMember)
```
