### ISSUE TITLE
Errors converting Microsoft.Xrm.Tooling.Connector.CrmServiceClient to Microsoft.Xrm.Tooling.Connector.CrmServiceClient

### ISSUE THREAD

**Issue by georged** [seanmcne/Microsoft.Xrm.Data.PowerShell#27]
After I create a connection, any attempt to use it ends up with an error "Cannot convert object of type Microsoft.Xrm.Tooling.Connector.CrmServiceClient to type Microsoft.Xrm.Tooling.Connector.CrmServiceClient"

I traced it down to the line in the function VerifyCrmConnectionParam:

$conn = $connobj.Value

$conn is declared as [Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn and simply removing [Microsoft.Xrm.Tooling.Connector.CrmServiceClient] from the parameter declaration seems to fix the problem. 

I'm still unsure what's causing it - is it one of the idiosyncrasies of Powershell?

**Comment by kenakamu** [comment]
Thanks for feedback.

From the error message, I doubt you have 2 or more assemblies with different versions loaded. Could you try to start new PowerShell window and try ?

I got same issue when I loaded v1.8 and v2.0

**Comment by georged** [comment]
Yes, spot on. Turns out I have the Microsoft.Xrm.Tooling.CrmConnector.Powershell snapin from 2016 SDK registered and adding it to the script via Add-PSSnapin is causing the issue because the snapin is using v2.0 of Microsoft.Xrm.Tooling.Connector while your module comes with v1.7 of the same.

The solution is to either avoid adding the snapin or, if that is required, remove the Tooling assemblies from the module folder.
