### ISSUE TITLE
Cannot connect to MS CRM 365 online (9th version) 

### ISSUE THREAD

**Issue by shulhachvitali** [seanmcne/Microsoft.Xrm.Data.PowerShell#270]
Hello all
Today suddenly appeared I couldn't connect to ms crm online:

PS > $conn = Get-CrmConnection -OrganizationName 'someorganizationname' -ServerUrl 'https://disco.crm4.dynamics.com' -Credential $cred

WARNING: Failed to connect to CRM: Unable to Login to Dynamics CRM
Get-CrmConnection : The pipeline has been stopped.
At line:1 char:9
+ $conn = Get-CrmConnection -OrganizationName 'someorganizationname' -ServerUrl 'ht ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (:) [Get-CrmConnection], PipelineStoppedException
    + FullyQualifiedErrorId : -9,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand
 
Get-CrmConnection : Failed to connect to CRM: 
At line:1 char:9
+ $conn = Get-CrmConnection -OrganizationName 'someorganizationname' -ServerUrl 'ht ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Get-CrmConnection], Exception
    + FullyQualifiedErrorId : -3,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand

Organization location: Europe,
The connection to on-premice and 8th versions of CRM online are ok
Credentials are well, online access via browser is ok too

Could anybody to chack the issue, please?

**Comment by seanmcne** [comment]
I'm not exactly a fan of using get-crmconnection directly and using discovery, definitely make 100% sure you're on the latest version of the Xrm.Data.Powershell - we don't maintain the xrm connector here we just use it to create the connection.  The latest 2.6 build (and when we release 2.7) will have the latest libraries.  If you're on an old version the auth may not be compatible with new 8.2 and v9 orgs. 

```powershell
Connect-CrmOnline -ServerUrl someorganizationname.crm4.dynamics.com
```

**Comment by ksulikow** [comment]
Hi,

I have the same issue, upgraded all SDK dlls to the latest version 9.0.0.7 - and tried different ways of creating CrmServiceClient object - always getting the same error: Unable to Login to Dynamics CRMOrganizationServiceProxy is nullOrganizationWebProxyClient is nullOrganizationServiceProxy is nullOrganizationServiceProxy is nullOrganizationWebProxyClient is nullOrganizationServiceProxy is nullOrganizationWebProxyClient is null

It was working a few days ago with version 9 !

**Comment by ksulikow** [comment]
I found solution, add this line to your script on the top:
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 

It will enforce to use Tls 1.2 - looks as Microsoft has already updated all CRM v9 instances to use Tls 1.2 !

**Comment by seanmcne** [comment]
Ahhh good call, yes you can also download our current Main branch and use that (this has the latest DLLs that use .net 4.6 and TLS 1.2).  We'll have a release queued up shortly (2.7) that will use these libraries and support tls 1.2.  Thanks for the update!

**Comment by shulhachvitali** [comment]
Thanks for TLS 1.2, it works
Yes, I do not use discovery url, it was a bad example, sorry for misunderstanding 
waiting for 2.7 version)

**Comment by seanmcne** [comment]
Excellent - take a look at the Main repo as well for 2.7 - i just added some script that will set the service point manager to use TLS 1.2 in addition to TLS (I was still seeing issues with the latest library).

**Comment by fleep** [comment]
Trying to get this working in my env.  Doing this doesn't work:

> [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;

When I try to install from master repo's files, I get this error:

```
C:\Windows\system32> Import-Module Microsoft.Xrm.Data.Powershell
Import-Module : Could not load file or assembly 'file:///C:\Users\fmedeiro\Documents\WindowsPowerShell\Modules\Microsof
t.Xrm.Data.Powershell\2.6\Microsoft.Crm.Sdk.Proxy.dll' or one of its dependencies. Operation is not supported.
(Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module Microsoft.Xrm.Data.Powershell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

What's the correct stopgap until the 2.7 release?

**Comment by seanmcne** [comment]
Yep this happens when the module dll's are 'blocked' as they were downloaded from a zip file in a web browser. 

Delete the files for the module that you've downloaded and follow these steps here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell#alternative-how-to-file-copy-or-manually-deploy-this-module 

Make 100% sure to follow step3 and mark the zip as "safe"/unblock it, otherwise you'll get the error you have gotten above.

**Comment by seanmcne** [comment]
2.7.1 released just now - feel free to update from the gallery and it should connect (I've tested myself and it's working).
