### ISSUE TITLE
Error - The script  failed due to call depth overflow

### ISSUE THREAD

**Issue by d4hines** [seanmcne/Microsoft.Xrm.Data.PowerShell#276]
Hello,
I'd like to thank you guys for creating this set of high-quality tools. However, I'm running into an issue with the call stack limit. I'm trying to create scripts to automate the export of advanced finds for our data analysts to work with (if you can suggest a better way to do this, I'll take it!). One of our views is huge (several hundred thousand rows and many columns), and on that view I hit the following error:
```
 Get-CrmRecordsByFetch : System.Management.Automation.RuntimeException: The script failed due to 
call depth overflow. ---> System.Management.Automation.ScriptCallDepthException: The script 
failed due to call depth overflow.
   at System.Management.Automation.ExecutionContext.CheckStackDepth()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object 
input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at Get-CrmRecordsByFetch(Closure , FunctionContext )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
funcContext, Exception exception)
   at Get-CrmRecordsByFetch(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\2.6\Microsoft.Xrm.Data
.Powershell.psm1:1558 char:34
```
I've omitted the rest of the log file is it's very long and repetitive, but I'll include it on request.
Here's my environment:
``` 
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.1944                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.1944                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

Any ideas on how I can get around this? 
Let me know if I can provide any more information.

Many thanks,
Daniel Hines

**Comment by seanmcne** [comment]
This is interesting, it's definitely a recursion issue as the function calls itself. Later versions of powershell are limited by the amount of local resources so a PC with less ram or system resources would have a lesser depth.  

We could potentially consider avoiding recrusion and using a helper function to do the retrieves instead (inside of a while loop for instance). I believe you could use the fetch to query using the queryByFetch and get an upper limit of rows and read the next page info to pull the next page inside of a for/while loop yourself - I can't think of any easy ways to avoid this off hand unfortunately without actually taking control of the paging.

**Comment by d4hines** [comment]
I solved my issue for now by just breaking up the massive query into 10 smaller ones. That won't be fun to maintain, but is proving a lot easier to work with in every other way. Thanks for looking into it!

**Comment by seanmcne** [comment]
Based on the reference we could look at a pattern like this https://weblogs.asp.net/jongalloway/working-around-a-powershell-call-depth-disaster-with-trampolines

However I’m not seeing many situations where we are having users require 100+ pages of 5000 returned rows. That said it might be good to shed the recursion and go with a trampoline approach to avoid this scenario.
