### ISSUE TITLE
Install-Module does not seem to be working correctly with 2.7.1

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#281]
The following command appear to work OK and the module is installed in "C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell".  I installed both V2.6 and V2.7.1.

install-module -Name Microsoft.Xrm.Data.Powershell -requiredVersion 2.6 -
install-module -Name Microsoft.Xrm.Data.Powershell -requiredVersion 2.7.1

Import-module Microsoft.Xrm.Data.Powershell -requiredVersion 2.6
Get-Command -module Microsoft.Xrm.Data.Powershell 

At this point you can see all  of the exported commands. 

remove-module Microsoft.Xrm.Data.Powershell 
Import-module Microsoft.Xrm.Data.Powershell -requiredVersion 2.7.1
Get-Command -module Microsoft.Xrm.Data.Powershell 

At this point no commands are show. 

I have verified that the execution policy as follows. 
PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    RemoteSigned
   UserPolicy    RemoteSigned
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted

Do you have any ideas of why 2.7.1 does not show any of the commands? 

Thanks

**Comment by seanmcne** [comment]
Very strange - I wonder if the way I’m building the package is somehow leading to this. I’ll look into it tonight if I get a chance - thanks for letting me know!

**Comment by seanmcne** [comment]
Ok I think it's all fixed now, I created a Build/Release process to try and automate things more so we can get bug fixes released faster and more reliably.  An unintended consequence was re-writing the manifest which somehow messed up the exported cmdlets list - I'll work on getting it fixed longterm but in the meantime I did things the good 'ole fashioned manual way.  Sorry for the confusion! :)

**Comment by jeffreynelson** [comment]
Thanks, that seems to have fixed the issue.  I am able to install and see the imported commands now.
