### ISSUE TITLE
Unable to set timeout

### ISSUE THREAD

**Issue by devbeard** [seanmcne/Microsoft.Xrm.Data.PowerShell#282]
**Issue:** 
Set-CrmConnectionTimeout does not seem to set timeout

**Cause:** 
The if-statement in line 4422 does not evaluate to true, and the timeout is not set

**Additional details:** 
On a test machine with version 2.7.2, the statement `$conn.OrganizationServiceProxy.getType().BaseType.Name` evaluates to ``ServiceProxy`1``, not the expected `OrganizationServiceProxy`. 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/479f49928048f574c3bf182b24cf0dd22c55c0c0/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L4422

**Comment by seanmcne** [comment]
Bugger...

**Comment by seanmcne** [comment]
Hmm I just checked with this version (2.7.2) as well i'm not exactly sure why yours is showing a shortened result.  Can you try this after you connect? 

```powershell
$conn.OrganizationServiceProxy.getType().BaseType.Name
```

![image](https://user-images.githubusercontent.com/2292260/35833902-c85cbf16-0a98-11e8-9d6c-8e1ae5702c20.png)

**Comment by WellerPShell** [comment]
![image](https://user-images.githubusercontent.com/36198381/36024294-3b9ed554-0d87-11e8-90db-0f538c2a7c50.png)

Same for myself, cannot set a timeout.

**Comment by seanmcne** [comment]
Ok I removed the base type name checks as they were just mainly there for a backstop in case the types changed - the checks in there should be sufficient now though, I also made sure to update all 4 timeouts for the WebProxy so timeouts work as expected w/ the webapi proxy as well as the soap service. Thanks for reporting this!

**Comment by seanmcne** [comment]
Please see #421
