### ISSUE TITLE
Issues resolving cases via Microsoft.XRM.Data.Powershell

### ISSUE THREAD

**Issue by PvilleStang** [seanmcne/Microsoft.Xrm.Data.PowerShell#288]
Long story short, we have a ton of cases to resolve due to errant workflows.  Trying to use:

set-crmrecord -EntityLogicalName incident -id 80bc74d9-c118-e811-80f5-005056bb0f02 -Fields @{
    statuscode = (New-CrmOptionSetValue -value 5) #Case Solved
    statecode = (New-CrmOptionSetValue -value 1) #Resolved 
    }

This gives me the error:
"This message can not be used to set the state of incident to Closed.  In order to set state of incident to Closed, use the CloseIncidentRequest message instead."

Is there a way to resolve these using XRM.data.powershell, or do I have to fall back into the C# or service call methodology?

**Comment by seanmcne** [comment]
Added sample here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/EntityOperations/IncidentClose.ps1
