### ISSUE TITLE
Trying to create a new user account

### ISSUE THREAD

**Issue by MumpekPumpa** [seanmcne/Microsoft.Xrm.Data.PowerShell#289]
I'm trying to automate the creation of new user accounts. I perform the following actions:

```
 .\RegisterXRMTooling.ps1
Add-PSSnapin Microsoft.Xrm.Tooling.Connector
Import-Module .\Microsoft.Xrm.Data.Powershell.psd1
$Cred = Get-Credential
Connect-CrmOnPremDiscovery -ServerUrl https://crm.server.com -Credential $Cred -OrganizationName CRM
New-CrmRecord -conn $conn -EntityLogicalName systemuser -Fields @{"fullname"="Test User"}
```

I receive the following:
```
An unexpected error occurred.
At C:\Users\user\Desktop\Microsoft.Xrm.Data.PowerShell 2.5\Microsoft.Xrm.Data.Powershell.psm1:328
char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : An unexpected error occurred. 
```

I tried with 2.72., 2.6 and 2.5, the same error is received.

**Comment by PvilleStang** [comment]
You need to define the domainname, (login) and assign it to a default business unit.   Try:

$businessUnitId = (Get-CrmRecords -EntityLogicalName businessunit -FilterAttribute name -FilterOperator eq -FilterValue ($Global:conn.ConnectedOrgFriendlyName) -Fields businessunitid,name).CrmRecords.businessunitid.guid

New-CrmRecord -EntityLogicalName systemuser -Fields @{
                "domainname"=$DomainName;
                "firstname"=$Given;
                "lastname"=$Sur;
                "businessunitid"=(New-CrmEntityReference -EntityLogicalName businessunit -Id $businessUnitId);}

Also, you may need to define your connection to "$Global:Conn = Connect-CrmOnPremDiscovery -ServerUrl https://crm.server.com -Credential $Cred -OrganizationName CRM"

**Comment by PecnikMiha** [comment]
Thank you for this information. Now I'm trying to populate $businessUnitId, although $Global:Conn is defined, it comes up with WARNING: No Result.

I tried listing the Business Unit ID's in other ways, also tried with the name of the BU, but no luck.

**Comment by seanmcne** [comment]
@MumpekPumpa you'll want to spend some time making sure you understand, the problem (most likely) is that you're searching for a businessunit with a different name if you change that you'll get a result. Otherwise you can try this but be advised this will just grab the first BU returned.  Also, don't forget to try using -verbose on some of these cmdlets as they'll print out what they're doing. 

```powershell
$businessUnitId = (Get-CrmRecords -EntityLogicalName businessunit -Fields businessunitid,name -topcount 1).CrmRecords.businessunitid.guid
```
