### ISSUE TITLE
Get-CrmSolutions would be perfect

### ISSUE THREAD

**Issue by SashaSidorenko** [seanmcne/Microsoft.Xrm.Data.PowerShell#290]
In my case I need to export all CRM solutions but using Export-CrmSolution I only able to export solution specified in -SolutionName parameter. I guess it would be very useful to make -SolutionName paremeter not mandatory so Export-CrmSolution cmdlet used without it will export all solutions.
Another way is to get all solutions and use Export-CrmSolution cmdlet for each solution name. However Get-CrmSolution cmdlet does not exist.

Maybe I miss something?
Thanks

**Comment by Atili0** [comment]
as far as I know you can export all your solution with Get-CrmRecords and Export-CrmSolution

**Comment by SashaSidorenko** [comment]
@Atili0 you mean I can get all solutions using Get-CrmRecords? Could you please describe with more details?
Thanks

**Comment by Atili0** [comment]
Oops sorry, You can use (something like this)

Get-CrmRecords -conn $conn -EntityLogicalName solution -FilterAttribute uniquename -FilterOperator "not-null"

then when you have all your solutions, you can do a foreach and export each one with Export-CrmSolution

this is a workaround till our friends or somebody create this function 👍

**Comment by SashaSidorenko** [comment]
@Atili0 Thanks a mil! it works for me like that:
To get all unmanaged solution's names i've use
$solutionXml = Get-CrmRecords -conn $conn -EntityLogicalName solution -FilterAttribute ismanaged -FilterOperator "eq" -FilterValue $false -Fields uniquename
$solutions = $solutionXml.Values.Uniquename
