### ISSUE TITLE
trying to create new team

### ISSUE THREAD

**Issue by Frederik36** [seanmcne/Microsoft.Xrm.Data.PowerShell#292]
Hi,
I'm trying to create a new team and receive an unexpected error:

New-CrmRecord -EntityLogicalName team -fields @{"name"="test";"administratorid"="46439f9c-9ca5-e611-80e6-5065f38aea11";"businessunitid"="$($orgid)"} -conn $connection

An unexpected error occurred.
At C:\windows\system32\windowspowershell\v1.0\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:273 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : An unexpected error occurred.

**Comment by seanmcne** [comment]
Check $conn.lastcrmexception 

I suspect $orgid is your orgid and not the bsuinessUnitID 

You can get your users businessUnitId by running a invoke-CrmWhoAmI

**Comment by Frederik36** [comment]
hi,
i changed the businessID Still the same error. 
PS C:\Windows\system32> New-CrmRecord -EntityLogicalName team -fields @{"name"="test";"administratorid"="46439f9c-9ca5-e611-80e6-5065f38aea11";"businessunitid"="71eacc72-239e-e611-80e6-5065f38aea11"} -conn $connection
An unexpected error occurred.
At C:\windows\system32\windowspowershell\v1.0\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:273 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : An unexpected error occurred.

unless i need to add the teamtype to, but then i receive following error:

PS C:\Windows\system32> New-CrmRecord -EntityLogicalName team -fields @{"name"="test";"administratorid"="46439f9c-9ca5-e611-80e6-5065f38aea11";"businessunitid"="71eacc72-239e-e611-80e6-5065f38aea11";"teamtype"="Owner"} -conn $connection -Verbose
Incorrect attribute value type System.String
At C:\windows\system32\windowspowershell\v1.0\Modules\Microsoft.Xrm.Data.PowerShell\Microsoft.Xrm.Data.Powershell.psm1:273 char:9
+         throw $conn.LastCrmException
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FaultException`1
    + FullyQualifiedErrorId : Incorrect attribute value type System.String

**Comment by Frederik36** [comment]
had to add a New-CrmEntityReference for both administratorid and businessid and then it worked.
