### ISSUE TITLE
Can't import CRM solution 

### ISSUE THREAD

**Issue by alenzurfluh** [seanmcne/Microsoft.Xrm.Data.PowerShell#294]
Hi,

I'm trying to import a solution into a CRM2013 on prem instance using "Import-CrmSolution".

When doing so I get a timeout after 2mins and the ImportID will be 00000000-0000-0000-0000-000000000000.  See screenshot below. I've tried to increase the Timeout by using Set-CrmConnectionTimeout.  But this does not help either. Is this a bug fixed by #284 ?
If yes, how can get this fix? If not - is there another way how I can import the solution?

![2018-03-20_09-46-47](https://user-images.githubusercontent.com/37574827/37718485-116fe802-2d23-11e8-83d7-840f09891f2b.jpg)

Many thanks
Alen

**Comment by seanmcne** [comment]
Can you try to import using the async import method please?

**Comment by seanmcne** [comment]
To clarify - either add the "-AsyncOperationImportMethod" switch parameter, or you can use the "Import-CrmSolutionAsync" function as this won't have to hold a connection open.  Instead, it will use a method of uploading the solution to the platform and having it import, the cmdlet will loop and track the progress and result of the import.  This would allow the import to go on for 10 minutes (for instance) and you don't need to stay 'connected' waiting for a response. 

Hope that helps!

**Comment by seanmcne** [comment]
Please see #421
