### ISSUE TITLE
Get-CRMConnection results in Method Not Found

### ISSUE THREAD

**Issue by dark7622** [seanmcne/Microsoft.Xrm.Data.PowerShell#296]
HI Everyone,

So I downloaded the source code and tried to run the "Get-CRMConnection" with -interactiveMode and got an error.

"Get-CrmConnection : Method not found: 'System.string System.String.format(System.iFormatProvider,System.String,System.object)'. 

Can't seem to find anything online, even if I use the organization and server url parameters I get the same thing. 

Yes I'm running the script on the CRM server. This is CRM 2016.

**Comment by nkyyc** [comment]
Install it using PowerShell (no need to download code)
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/master/README.md#preferred-install-the-module-via-powershell-gallery

On your Windows 10 client:
`PS C:\Users\nkyyc> Install-Module Microsoft.Xrm.Data.PowerShell -Scope CurrentUser`

**Comment by dark7622** [comment]
Update, so it seems to only be a problem on the server that is running CRM. In my development environment I figured to run it on the server. With SharePoint the modules are only installed on the SPS servers. So figured that would be a requirement. My bad, but now working from a different machine.

**Comment by seanmcne** [comment]
👍 thanks for the update - glad to hear it's working. My best guess would be that an older version of the assembly mat have made its way into the GAC - either way I'm happy to hear it's working!
