### ISSUE TITLE
Update CRM Record issue for SystemUser

### ISSUE THREAD

**Issue by dark7622** [seanmcne/Microsoft.Xrm.Data.PowerShell#297]
Ok, so simple one: 

Set-CRMRecord -conn $conn -EntityLogicalName systemuser -id $systemId -fields @{"isdisabled"=1}

This doesn't seem to update the user object at all. It still says it's enabled, as if nothing has happened. 

ideas?

**Comment by seanmcne** [comment]
https://msdn.microsoft.com/en-us/library/jj602914.aspx

Try using Set-CrmRecordState

**Comment by dark7622** [comment]
Yea I kept getting an error that the Status must be between -1 and -1.

I ended up writing another function that follows the same logic, where I set the status code to -1, as it seemed with with the Set-crmrecordstate I could not, kept complaining with the above, even when I passed a -1 it said I didn't provide the status.
