### ISSUE TITLE
Get List of actions, invoke action

### ISSUE THREAD

**Issue by dark7622** [seanmcne/Microsoft.Xrm.Data.PowerShell#298]
Ok, in the Mailbox entity, I'm trying to invoke the "Apply Default Email Settings". I need to programmatically apply them. 

Though I guess I could just have the values as parameters and apply the fields directly, but that requires the script or parameters to be changed each time. 

I see there is the invoke-CRMAction but I need to know the name of the action.

**Comment by seanmcne** [comment]
Applying default settings doesn't use a CRM Action - you can use the function built right into this module.  Set-CrmUserMailbox which allows you to apply the defaults. 

Hope this helps!
