### ISSUE TITLE
Apply Solution Upgrades

### ISSUE THREAD

**Issue by sanjaya-yapa** [seanmcne/Microsoft.Xrm.Data.PowerShell#305]
Hi Sean,

I am in the process of extending the current release automation process of my client. In the current process we use the Import-CrmSolution command. This used to work with CRM Solutions.

But now, the internal development team of the client, has started using Solution Patches and Solution Upgrades. Primary reason to reduce the number of solutions being released to the target environment. 

The "Import-CrmSolurtion" works with Solution Patching. But when I do a Solution Upgrade, it just upload the Solution Upgrade to the target environment and does not apply the upgrade automatically. Could you please let me know whether there is any specific parameter that I should send to the command. Following is the script that I am using to deploy the package to the target environment.

Import-CrmSolution `
	-SolutionFilePath $releaseZipFileName `
	-PublishChanges:$publishChanges `
	-ActivatePlugIns:$activatePlugIns `
	-ImportAsHoldingSolution:$importAsHoldingSolution `
	-MaxWaitTimeInSeconds 900

Thanks
Sanjaya

**Comment by seanmcne** [comment]
This should handle the Import process, however the apply solution upgrade isn't part of this process (as far as I know).  

What I think you'll need to do is execute a: DeleteAndPromoteRequest: 

``` powershell
$solutionUniqueName = "solUniqueName"

$UpgradeSolutionRequest = new-object Microsoft.Crm.Sdk.Messages.DeleteAndPromoteRequest

$UpgradeSolutionRequest.UniqueName= $solutionUniqueName

$response= $conn.ExecuteCrmOrganizationRequest($UpgradeSolutionRequest)

#the unique identifier of the promoted solution
write-output $resposne.SolutionId
```

**Comment by seanmcne** [comment]
Reference: https://stackoverflow.com/questions/41364576/dynamics-crm-dynamics-365-apply-solution-upgrade-programmatically

**Comment by sanjaya-yapa** [comment]
Hi Sean,
Thank you so much for your response. I will try out this today and let you know the outcomes by EOD. 

Thanks
Sanjaya

**Comment by sanjaya-yapa** [comment]
Hi Sean,

The power shell solution works for the solution upgrades. As per my client requirements, after importing the Solution Upgrade to the target environment through powershell, I used the solution you provided and it worked. 
Thanks for your help.

Thanks
Sanjaya

**Comment by seanmcne** [comment]
Excellent!  Thanks for taking the time to test this out.  I've captured the sample here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/Solutions/ManagedSolutionUpgrade.ps1

**Comment by minumulasri** [comment]
$response=$connection.ExecuteCrmOrganizationRequest($UpgradeSolutionRequest)
When I run this statement , getting response is null
