### ISSUE TITLE
Support for German Cloud

### ISSUE THREAD

**Issue by petrroda** [seanmcne/Microsoft.Xrm.Data.PowerShell#306]
Currently the URL is validated against standard layout in all regions except Germany.

In the German cloud the url is like this:

*.crm.microsoftdynamics.de

**Comment by seanmcne** [comment]
Thanks for pointing this out! I’ll look into a fix for that soon.

**Comment by petrroda** [comment]
Just change the validation to

[ValidatePattern('([\w-]+).crm([0-9]*).(dynamics|crm[\w-]*).(com|de)')]

**Comment by seanmcne** [comment]
the new validation pattern has been added, if you can confirm by testing that it works for german cloud url's that'd be great.  It will make into the next release.  Thanks!

**Comment by seanmcne** [comment]
This should be fixed as of a long while back, but I forgot to close it - thx!
