### ISSUE TITLE
Test-CrmViewPerformance retrieving all rows

### ISSUE THREAD

**Issue by sanjint** [seanmcne/Microsoft.Xrm.Data.PowerShell#307]
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/28848618eccac50f78f3e702546dfe045559a845/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L5191

Would it not be more logical to retrieve the user settings (Records per Page) and then limit retireval to this number? Does this go against the intention of the Cmdlet?

**Comment by seanmcne** [comment]
I suppose we could add that option - in its current form it should retrieve all rows over multiple pages since the -AllRows switch is specified. If another retrieved option (users page size) is pulled it will take additional time and we would probably add this as an option vs a default.

**Comment by seanmcne** [comment]
Hey Sanjin, is this still an outstanding request (feel free to re-open).  If you want to work on this, we would appreciate the help :)
