### ISSUE TITLE
Sync Import Timeout

### ISSUE THREAD

**Issue by tbienvenu** [seanmcne/Microsoft.Xrm.Data.PowerShell#308]
Import-To-Crm method failed with Timeout after 20 minutes whereas the solution is correctly imported in the CRM in 6 minutes.

The $result variable stays at guid.empty

**Comment by seanmcne** [comment]
I suggest using the async import method - as far as I know based on the previous research done the import via the UI and the API is largely the same.  To guard yourself against timeouts is the reason we have the async import process.  What can happen, with a sync import that's taking an exceedingly long time.  Please refer to the samples and lookup the import you got a timeout from (the webserver timeout is 5 minutes, anything longer than 5 minutes with a sync import should ultimately fail). 

To troubleshoot the import that failed or timed out please look here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/tree/master/Microsoft.Xrm.Data.PowerShell.Samples/Troubleshooting 

Thanks for reaching out!
