### ISSUE TITLE
Need to query CRM users and return ActiveDirectoryGUID

### ISSUE THREAD

**Issue by PvilleStang** [seanmcne/Microsoft.Xrm.Data.PowerShell#311]
Sean,

Noticed in the CRM SystemUserBase (where much of the information retrieved in the systemuser record query) has a field, ActiveDirectoryGuid, but is not retrievable via the get-crmrecord(s) function, nor the underlying $conn.GetEntityDataById(... piece.  This would be EXTREMELY helpful as we are having issues with user SamAccountName changes that aren't being reflected in CRM.  I had been using DomainName / SamAccountName as unique identifiers between AD and CRM, but there have been more and more instances of our AD team changing IDs as employment status changes.  The only thing I can see that really is a constant is the AD GUID.  

Any possibility of adding that functionality to a future release?

**Comment by PvilleStang** [comment]
I've found a work-around using a SQL query, but don't like this as a long term solution.

$Users = Invoke-Sqlcmd -ServerInstance <SQLServerName> -Database PRD1_MSCRM -Query "SELECT * FROM PRD1_MSCRM.dbo.SystemUser"  | select ActiveDirectoryGuid,@{n="SamAccountName";e={$_.DomainName.replace("<domain>\","").replace(",DOMAIN>\","")}},internalemailaddress,firstname,lastname,@{n="telephone";e={$_.address1_telephone1}},systemuserid,@{n="IsCrmDisabled";e={$_.isdisabled}} | ?{$_.SamAccountName -like "<XXX>*" -or $_.SamAccountName -like "<XXX>*"}

**Comment by seanmcne** [comment]
Yep, this attribute is not even readonly in onprem.  I'd suggest logging a product request (aka.ms/crmideas) to read the activeDirectoryGuid from the systemuser entity.
