### ISSUE TITLE
Support for Powershell Linux

### ISSUE THREAD

**Issue by chrismarkovic** [seanmcne/Microsoft.Xrm.Data.PowerShell#312]
Is there capacity to compile a release without the graphical components of interactive sign on so the module can be supported by Powershell on Linux?

**Comment by seanmcne** [comment]
Excellent question!  Unfortunately we have a hard dependency on the XRM Tooling powershell dll/connector which is not .NET core compatible today which I believe would be rquired to run on PowerShell for linux.  If it was just the UI bits that isn't a problem (as we'd just not be able to support interactive mode) but it's probably going to be quite a bit more complicated than that given what is going on in XRM Tooling today (which is a lot).
