### ISSUE TITLE
Add function that allows use of ExecuteBatch to create records. 

### ISSUE THREAD

**Issue by RIKIKU** [seanmcne/Microsoft.Xrm.Data.PowerShell#315]
I have some code that uses the ExecuteBatch method to send multiple create requests at the same time. I would like to try and add that to this module.

**Comment by seanmcne** [comment]
Sure - please feel free to first add it as a sample maybe and then lets see if it's applicable for inclusion in the module. 

Thanks @RIKIKU!

**Comment by seanmcne** [comment]
@RIKIKU let me know if you want to work on this, please reopen and feel free to share the code you might have around this - thx!

**Comment by RIKIKU** [comment]
Hi @seanmcne 
I added it as a sample and created a pull request over on the samples repo as requested:
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/pull/28
