### ISSUE TITLE
Export-CrmSolution : Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support:  #7E88F51E

### ISSUE THREAD

**Issue by venkyk56** [seanmcne/Microsoft.Xrm.Data.PowerShell#317]
Hi,
Getting null reference issue when i try to to export a solution as managed/unmanged .

Error:
Export-CrmSolution : System.Management.Automation.RuntimeException: An unexpected error occurred. => System.NullReferenceException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: 
#7E88F51E

Thanks,
Venky

**Comment by seanmcne** [comment]
Hi Venky - can you provide more information as to what command you ran, was it online or onprem, what version you're using, etc? 

Thanks!

**Comment by seanmcne** [comment]
Hi Venky can you please try using v2.8.1.1 on the gallery - thanks!

**Comment by venkyk56** [comment]
Hi Sean,
Sorry for the late reply. I was out of station and did not get time.

I have used v2.8.1.1 module to export the solution but still getting error. Please find the attached screensho.

FYI, we are using CRM 365  v8.2 online and using export-solution command.

Export-CrmSolution -conn $crmConnDev -SolutionName "Entities" -SolutionZipFileName (Get-Date -UFormat "%Y_%m_%d_Entities_unmanaged_0_1_0.zip") -SolutionFilePath "C:\VENKY\solution_back" -Verbose


![solution_export_error](https://user-images.githubusercontent.com/11367105/45965976-f56a1e80-bff7-11e8-83b7-fa723a7e67a7.png)

Thanks,
Venky

**Comment by venkyk56** [comment]
FYI Sean, We are able to export the solution through crm portal  in browser.

Thanks,
Venky
