### ISSUE TITLE
how to view attribute values ?

### ISSUE THREAD

**Issue by John-ow** [seanmcne/Microsoft.Xrm.Data.PowerShell#318]
I m using this command:

`Get-CrmEntityAttributes contact | Select-Object -First 1`

Output is:
![image](https://user-images.githubusercontent.com/43082697/45249352-7374c700-b362-11e8-9caa-915b800cb81a.png)

For some properties instread of value is shows:

- System.Runtime.Serialization.ExtensionDataObject
- Microsoft.Xrm.Sdk.Metadata.AttributeRequiredLevelManagedProperty
- Microsoft.Xrm.Sdk.BooleanManagedProperty
- Microsoft.Xrm.Sdk.Label
- 

Please guide how to view readl data as a text ?

**Comment by seanmcne** [comment]
Do you just want the logical and schema names or these fields you've highlighted specifically?  If it's the fields you've highlighted you'll need to query the object for the value as it's an object that doesn't have a toString() method and, instead, just prints the object type.  

Another potential way is to do something like: 
````
(Get-CrmEntityAttributes -EntityLogicalName contact).Description|select -ExpandProperty UserLocalizedLabel |select Label

**Comment by seanmcne** [comment]
Let me know if you have any other questions - thanks!
