### ISSUE TITLE
How to access fields with sub-fields

### ISSUE THREAD

**Issue by sunilred** [seanmcne/Microsoft.Xrm.Data.PowerShell#321]
Hi,

I am using the Microsoft.XRM.Data.PowerShell to export CRM records from the Account entity. It works great except not all data fields are exported.

In the attached image (JSON extract from using CRM Web API and C#) how do I get access to fields that have sub-fields/child fields such as:
- parentaccount.id
- parentaccount.logicalname
- parentaccount.name
- fus_branch.id
- fus_branch.logicalname
- fus_branch.name
- fus_branch.keyattributes

![image](https://user-images.githubusercontent.com/37816928/45324643-d18fed00-b5a2-11e8-9ad2-39254b8b105d.png)

Kind regards,
Sunil

**Comment by seanmcne** [comment]
Here's an example of how to get the entity references of lookup attributes: 

```
$res=Get-CrmRecords -EntityLogicalName account -Fields * -FilterAttribute parentaccountid -FilterOperator not-null

#parentaccountid value/tostring
$res.CrmRecords[0].parentaccountid 

#parentaccountid underlying object 
$res.CrmRecords[0].parentaccountid_Property

#ObjectType: 
$res.CrmRecords[0].parentaccountid_Property.GetType()

#value ObjectType: 
$res.CrmRecords[0].parentaccountid_Property.Value.GetType()

#parentaccountid object value (an entity reference to the parentaccountid) 
$res.CrmRecords[0].parentaccountid_Property.Value

```

**Comment by sunilred** [comment]
Great thanks!
