### ISSUE TITLE
Get-CrmRecordsByFetch Count property sometimes not filled

### ISSUE THREAD

**Issue by Nreall** [seanmcne/Microsoft.Xrm.Data.PowerShell#327]
Hi,

In the last update 2.8.1 (maybe earlier didn't test yet) there seems to be a bug.

When i do a Get-CrmRecordsByFetch sometimes the Count property isn't filled. The weird thing is that it has results when it does.

![image](https://user-images.githubusercontent.com/18572509/45476797-359be800-b740-11e8-97a0-6f23cfd69bd0.png)

Please advise.

With kind regards,

Nreall

**Comment by seanmcne** [comment]
Hi @Nreall - thanks so much for reaching out!  You are correct, this is a bug and is fixed in the patch I published this morning (v2.8.1.1). Thanks for taking the time to report this, it should be fixed now in the update.
