### ISSUE TITLE
Version 2.8.1 in PowerShell Gallery?

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#328]
Seems like version 2.8.1 is not published to the Gallery: https://www.powershellgallery.com/packages/Microsoft.Xrm.Data.Powershell

**Comment by seanmcne** [comment]
Hey @thuld - i had to pull the listing temporarily due to a bug in get-crmrecordsbyfetch

I just published 2.8.1.1 as a patch today
