### ISSUE TITLE
cant update duplicate detection rule owner 

### ISSUE THREAD

**Issue by John-ow** [seanmcne/Microsoft.Xrm.Data.PowerShell#331]
I m trying to update duplicate detection rule owner but my script is not updating it at all. 

Please help, here is my code:
``

$systemUser = Get-CrmRecords -EntityLogicalName systemuser -Fields * -FilterAttribute fullname -FilterOperator eq -FilterValue "SYSTEM" 
Write-Host "System User Got is: " +  $systemUser.CrmRecords[0].fullname + $systemUser.CrmRecords[0].systemuserid

$ddr = Get-CrmRecord -EntityLogicalName duplicaterule -Fields * -id '4e396448-6fb4-4dab-9ace-af6aef4f0977' 
Write-Host "DDR Existing Owner" + $ddr.ownerid

$userOwnerToAssign =New-CrmEntityReference -Id $systemUser.CrmRecords[0].systemuserid -EntityLogicalName systemuser  
 
$userOwnerToAssign.Name + 'ok'
$ddr.ownerid_Property =  $userOwnerToAssign
#ddr.ownerid = $tsUser.fullname
Write-Host "before updat" + $ddr.ownerid + $ddr.ownerid_Property
Update-CrmRecord($ddr)
 
Write-Host "after updat" + $ddr.ownerid

**Comment by seanmcne** [comment]
are the dup detection rules in an unpublished state? 

If so try (i may have the entity name wrong): 
```
update-crmrecord -entitylogicalname "duplicatedetectionrule" -id $id -fields @{"ownerid"=$userOwnerToAssign}
```

**Comment by yaweriqbal** [comment]
Module has Set-CrmRecordOwner, try using that.
