### ISSUE TITLE
publish duplicate detection rules

### ISSUE THREAD

**Issue by yaweriqbal** [seanmcne/Microsoft.Xrm.Data.PowerShell#332]
I recently have used Microsoft.Xrm.Data.PowerShell for a few tasks. One of the things I did was publishing duplicate detection rules using PowerShell.

I m willing to contribute in the further development of this useful module. Hope Publish duplicate detection rule can be considered as part of the functionality. Will make a pull request for this soon.

**Comment by yaweriqbal** [comment]
@seanmcne please let me know if there is a question.

**Comment by seanmcne** [comment]
Thanks so much for your contributions!
