### ISSUE TITLE
Error in Get-CrmSystemSettings

### ISSUE THREAD

**Issue by DarrenSmallwood** [seanmcne/Microsoft.Xrm.Data.PowerShell#336]
**I'm running the following:**
$settings = Get-CrmSystemSettings -conn $conn

**Error message:**
Add-Member : Cannot bind argument to parameter 'Name' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.2\Microsoft.Xrm.Data.Powershell.psm1:3521 char:71
+ ... mber -InputObject $psobj -MemberType NoteProperty -Name $name -Value  ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
 
Add-Member : Cannot bind argument to parameter 'Name' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.2\Microsoft.Xrm.Data.Powershell.psm1:3521 char:71
+ ... mber -InputObject $psobj -MemberType NoteProperty -Name $name -Value  ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand

It seems to be getting to the 'Original' SchemaName then fails. The value of original seems to be a list instead of a single value.

**For example:**
{[initialversion_Property, [initialversion, 9.0.2.761]], [initialversion, 9.0.2.761], [negativecurrencyf...]}

This has been working fine until yesterday.

**Comment by seanmcne** [comment]
Thanks for the report @DarrenSmallwood  confirmed it's a bug that's probably been around for quite a while, got it all fixed up and will include this in the next build.  Thanks!
