### ISSUE TITLE
Unable to connect to 9.1 CRM Organizations

### ISSUE THREAD

**Issue by tgradu** [seanmcne/Microsoft.Xrm.Data.PowerShell#339]
Hello,

When i want to connect to my CRM Online 9.1 Organization, the connection fails with:

Connect-CrmOnline -Credential $cred -ServerUrl $serverUrl

IsReady                        : False
IsBatchOperationsAvailable     : False
Authority                      :
OAuthUserId                    :
ActiveAuthenticationType       : Office365
OrganizationServiceProxy       :
OrganizationWebProxyClient     :
LastCrmError                   : Unable to Login to Dynamics CRMOrganizationServiceProxy is nullOrganizationWebProxyClient is null
LastCrmException               :
ConnectionLockObject           : System.Object
ConnectedOrgVersion            : 9.1.0.288
CallerId                       : 00000000-0000-0000-0000-000000000000
SdkVersionProperty             :

If i connect t my 8.2 Org ( same username & password, only different URL)
Connect-CrmOnline -Credential $cred -ServerUrl $serverUrl

IsReady                        : True
IsBatchOperationsAvailable     : True
Authority                      :
OAuthUserId                    :
ActiveAuthenticationType       : Office365
OrganizationServiceProxy       : Microsoft.Xrm.Tooling.Connector.CrmWebSvc+ManagedTokenOrganizationServiceProxy
OrganizationWebProxyClient     :
LastCrmError                   : OrganizationWebProxyClient is null
LastCrmException               :
ConnectionLockObject           : System.Object
ConnectedOrgVersion            : 8.2.2.2464
CallerId                       : 00000000-0000-0000-0000-000000000000
SdkVersionProperty             :

Is there an issue with the tool? 

Later Edit: I replaced locally on my machine ...\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3 the Microsoft.Xrm.Tooling.Connector.dll build 3.0.0.945 with 3.0.0.951 and now it works fine

Connect-CrmOnline -Credential $cred -ServerUrl $serverUrl

MaxRetryCount : 3
RetryPauseTime : 00:00:01
IsReady : True
IsBatchOperationsAvailable : True
Authority :
OAuthUserId :
ActiveAuthenticationType : Office365
OrganizationServiceProxy : Microsoft.Xrm.Tooling.Connector.CrmWebSvc+ManagedTokenOrganizationServiceProxy
OrganizationWebProxyClient :
LastCrmError : OrganizationWebProxyClient is null
LastCrmException :
ConnectionLockObject : System.Object
ConnectedOrgVersion : 9.1.0.288
DisableCrossThreadSafeties : False
CallerId : 00000000-0000-0000-0000-000000000000

So i guess a NuGet package update is needed.

**Comment by seanmcne** [comment]
I’ll test the current released version against a v9.1 instance quick and see if I can repro - I don’t know of any reason we would ship a breaking change requiring a library update so closely in versions. Do you have the exception generated?

**Comment by seanmcne** [comment]
Here is a test I just did locally on my machine - is it possible you had a much older version of this module that maybe didn't have TLS 1.2 forced in it yet? 

Can you run 
```
get-module -name Microsoft.xrm.data.powershell
```
![image](https://user-images.githubusercontent.com/2292260/48103174-a668f900-e1f3-11e8-8301-068e8e11a466.png)


![image](https://user-images.githubusercontent.com/2292260/48103117-73266a00-e1f3-11e8-8e24-a2f767513084.png)

**Comment by tgradu** [comment]
Hi Sean,
​
Thank you for looking into this. ​
​
I've deleted and reinstalled the module and now it seems to work:​
​
PS C:\WINDOWS\system32> Connect-CrmOnline -Credential $cred -ServerUrl $serverUrl​
IsReady                        : True​​
IsBatchOperationsAvailable     : True ​
​
If I run the Get-Module command I get Version  2.8.1.3.​
​
Connects now to both 9.1 and 8.2 and the Xrm.Tooling dll is build 3.0.0.945.​
​
The behavior is odd. Originally, when I tried, I had an old version of the PowerShell module and therefore I tried to update it running Update-Module -Force. The 2.8.1.3 version was installed and yet it still failed until I swapped the Xrm.Tooling.dll.

In Fiddler I noticed that there was a connection towards the Discovery Service - which returned the correct endpoint, however it didn't connect to the Organization Service afterwards.

The only error that I had was the LastCrmError: OrganizationWebProxyClient is null.

I guess there was something wrong on my machine - maybe some caching?

I can confirm that it works fine now.

Thanks for your help!
Radu


________________________________

**Comment by seanmcne** [comment]
Thanks Radu!  I wonder if the older version of the client was loaded or loading by default - glad to hear things are working now though!
