### ISSUE TITLE
Question:  Enable/Disable user accounts?

### ISSUE THREAD

**Issue by mjzagorsk** [seanmcne/Microsoft.Xrm.Data.PowerShell#340]
I have been unable to update a CRM record or use Set-CrmRecordState to update enable or disable a user account.  Please confirm that this is not possible currently.

**Comment by seanmcne** [comment]
For which platform - online or onPrem?  It absolutely is possible but it differs between the two platforms.

**Comment by mjzagorsk** [comment]
On Prem

**Comment by seanmcne** [comment]
I would model this after: https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/jj602914(v=crm.8) 

```powershell
Import-Module Microsoft.Xrm.Data.PowerShell
Connect-CrmOnline -ServerUrl <URL>
$DisableUser= new-object Microsoft.Crm.Sdk.Messages.SetStateRequest
$DisableUser.EntityMoniker=(New-CrmEntityReference -EntityLogicalName systemuser -Id "9c51c0ff-f998-4232-92ba-2faf1c9f65a5")
$DisableUser.State = New-CrmOptionSetValue -Value 1
$DisableUser.Status = New-CrmOptionSetValue -Value -1
$conn.ExecuteCrmOrganizationRequest($conn) 
if($conn.LastCrmException -ne $null){
            throw $conn.LastCrmException
}
elseif($conn.LastCrmError -ne ""){
            throw $conn.LastCrmError
}
else{
            Write-Output "Success"
}
```

**Comment by mjzagorsk** [comment]
Do you mind looking more into this.  I tried a method like this before and it was not successful, also the code you posted would not disable a user when I tried it.
