### ISSUE TITLE
Question: Storing CRMRecords on Disk

### ISSUE THREAD

**Issue by Kunter-Bunt** [seanmcne/Microsoft.Xrm.Data.PowerShell#341]
I'm trying to leverage this great project for moving certain Records to instances with every deployment, so they are in a correct (and source controllable) state after every deployment, e.g. important Organization-Queues. 

Technically this was already asked in #250 however the answer only talks about moving the records directly like this:
```
$c = Get-CrmRecord -conn $srcConn $logicalname $id $fields
New-CrmRecord -conn $destConn $c
```
And that works just fine, however storing to disk is harder:
```
Export-Clixml "$($_)/$($logicalname)/$($id).xml" -InputObject $c -Depth 10
$n = Import-Clixml "$($_)/$($logicalname)/$($id).xml"

#Alternative:
#$j = ConvertTo-Json -InputObject $c -Depth 10
#$n = ConvertFrom-Json -InputObject $j

New-CrmRecord -conn $destConn $n
```
That always throws serialization errors that seems connected to Powershell serialization:
```
The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter schemas.microsoft.com/.../Services:request.
The InnerException message was 'Error in line 1 position 8374. Element 'schemas.datacontract.org/.../System.Collections.Generic:value' contains data from a type that maps to the name 'System.Management.Automation:PSObject'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'PSObject' and namespace 'System.Management.Automation'.'.  Please see InnerException for more details.
```

As I think I cannot be the first one stumbling into this, I just wanted to ask if you have seen something similar and know an approach how to (de)serialize the Records properly.

Thanks in advance. 
(I know this is technically not an issue of this project, but I did find help anywhere else :/)

**Comment by Kunter-Bunt** [comment]
And a slight correction: It works for simple types like String and Int. Even for DateTime. The aliased ones like Lookup and OptionsetValue are problematic as they are deserialized as PSObject.

Greetings 
Kunter

**Comment by Kunter-Bunt** [comment]
```
    $n = Import-Clixml "$($_)/$($logicalname)/$($id).xml" 

    $props = $n.original.PSObject.BaseObject
    foreach ($key in $props.Keys) {
        if ($props[$key].Value.Id.Guid) { #Lookup
            $x = New-Object Microsoft.Xrm.Sdk.EntityReference
            $x.Id = $props[$key].Value.Id 
            $x.LogicalName = $props[$key].Value.LogicalName 
            $x.Name = $props[$key].Value.Key
            $props[$key].Value = $x #Replace PSObject with EntityReference
        }

        if ($props[$key].Value.Value -ne $null) { #Optionset Value
            $y = New-Object Microsoft.Xrm.Sdk.OptionSetValue
            $y.Value = $props[$key].Value.Value
            $props[$key].Value = $y #Replace PSObject with OptionsetValue
        }
    }

    New-CrmRecord -conn $srcConn $n -PreserveCrmRecordId
```
I decided to go for the ugly solution and hack it: I just reconstruct the complex types from the PSObjects after Deserialization. 
The pattern is simple: Look at the type of the Property before Serialization and replace the Value of the property by a hand constructed object of that specific type. 
You will need to do this for MultiselectOptionsets (and maybe some types I've missed) as well, I just do not have any in my solutions yet.

From my point of view this issue is solved, its just not solved beautifully...

**Comment by seanmcne** [comment]
Hey @Kunter-Bunt, I've been wracking my brain and debugging this, it looks like powershell is marking up the resulting imported object with some special object types/wrappers which is conflicting with wcf when sending in the request. 

I would agree, it's not super elegant unfortunately but unless I can better figure out how to serialize and deserialize in a more cleanly way I think this may be the only option, a close second might be to actually write an Export-CrmEntityRecord and Import-CrmEntityRecord (or something like that).  Another option for config data would be to use the configuration migration tool (although I can understand why it would be easier to do this via powershell as it's familiar and easy).  

Sorry that we've hit the wall on this one - let me know if you find anything else promising or something on the right track and I'll see if I can find anything else.  Thanks!

**Comment by Kunter-Bunt** [comment]
Well since only the "original" property seems to be important for the import, a custom serialization would just have to iterate the hashmap, switch on the attribute type and add the attributes to an xml (with type information), the same switching could then be done on import. 
If I have to much free time, I will implement that one.

One thing I would like to ask you @seanmcne: Is there a way to filter records on export with the Configuration Migration Tool? Because this was my main Painpoint with this tool, if I would want to one Contact for Deployment, that would be a mess with Configuration Migration Tool...
(I would actually like to move a special anonymous Contact that can be chosen by for Incidents, however exporting Contacts from a Production System with the Configuration Migration Tool would be silly, this Project on the other hand would allow me to export only that specific Contact by Guid.)

**Comment by seanmcne** [comment]
Ah, I see, I don't know of a way to filter the configuration migration tool as it's designed for config data that needs to be sync'd.  Honestly, what I've done in the past is exported the schema and some test data then edited the data XML by hand and checked that into source control so that no data would ever change in a CRM instance and, instead, it would be imported by the tooling and changed inside of the source.

**Comment by ashlega** [comment]
Hi Sean,

  just thought I'd mention this.. was struggling with this same error on my own PowerShell script for almost two days - finally figured I'd just bypass the boxing/unboxing by using a helper .NET class:

$HelperSource = @”
public class Helper
{
public static void SetAttribute(Microsoft.Xrm.Sdk.Entity entity, string name, object value)
{
entity[name] = value;
}
}
“@

So, then, instead of assigning entity references directly to the entity attributes, I'm now calling a helper class:
[Helper]::SetAttribute($entity, $name, $value)

Not 100% sure of the mechanics, but it does fix the problem - I can call Update/Create on the connection using an entity populated that way without any issues.

That's the bulk of it, though I had a few more details here: https://www.itaintboring.com/dynamics-crm/powershell-and-dynamicspowerapps/
