### ISSUE TITLE
Ability to install non-standard templates

### ISSUE THREAD

**Issue by TheBoosterPL** [seanmcne/Microsoft.Xrm.Data.PowerShell#347]
Hello,

First of all, I'd like to thank you for your hard work on this module, It's great and very usefull. I wonder if there is a possibility to install non-standard solution which is not included in the template list - D365_ProjectServiceAutomation, but in beta version 3. Right now I use:

`$NewCrmInstanceInfo = New-CrmInstanceInfo -TemplateList "D365_Sales","D365_CustomerService", "D365_ProjectServiceAutomation" (...)`

and then:

`New-CrmInstance -NewInstanceInfo $NewCrmInstanceInfo`

...but I'm not able to install version 3 which is required in my project. Is there any way to automate this and get rid of tedious installation in admin panel everytime I want to create a new instance? I can install it manually here:

![crm](https://user-images.githubusercontent.com/46132691/50423640-52c07680-0858-11e9-8972-befeca5448a8.png)
![crm3](https://user-images.githubusercontent.com/46132691/50426271-4e14b600-088a-11e9-95d6-9850b5079b8a.PNG)

**Comment by TheBoosterPL** [comment]
Thank you for your answer.
The problem is that there is no way to do this with Microsoft.Xrm.OnlineManagementAPI and Microsoft.Crm.PowerShell either. Selenium would be a dirty workaround... but the web administration panel is slow and unreliable. Sometimes it can't even list the installed solutions which is frustrating. I found that automating all my processes with scripts saves me tons of time. Your knowledge of Microsoft's 365 APIs is much grater than mine so I'd like to ask if there is any possible solution to actually automate this?

**Comment by seanmcne** [comment]
I'd recommend filing a product suggestion for inclusion in the new power platform admin api that's hopefully coming soon.
