### ISSUE TITLE
Import-CrmSolutionAsync -BlockUntilImportComplete does not work on its own.

### ISSUE THREAD

**Issue by tyler-hogsett-microsoft** [seanmcne/Microsoft.Xrm.Data.PowerShell#350]
The Import-CrmSolutionAsync function does not use the BlockUntilImportComplete parameter unless the MaxWaitTimeInSeconds parameter is supplied.

MaxWaitTimeInSeconds should probably be defaulted to "-1" (which, in this context, means "wait indefinitely") if BlockUntilImportComplete is present.

I will add this in a PR.

**Comment by tyler-hogsett-microsoft** [comment]
#351 Created PR

**Comment by seanmcne** [comment]
Hey Tyler, 
Aync shouldn't block - it was a stretch to put a 'block' capability in at all but was done so that import-crmsolution could import using the async import and wait until it was completed.  If there isn't a max time to wait it should just import asynchronously.  I'm open to discussing further, but assuming it's titled async then forcing it to be sync (or block) doesn't seem right.

**Comment by tyler-hogsett-microsoft** [comment]
I can understand the contention over whether or not the -BlockUntilImportComplete (or at that point, the -MaxWaitTimeInSeconds) parameter should exist; it does contradict with the "Async" portion of the name of the function. If a user wants to use the async & poll method, they can use the -AsyncOperationImportMethod parameter on the Import-CrmSolution function. This serves more as a way to instruct the function on how to execute, as opposed to calling a function and then telling it not to operate as its name describes.

However, at the very least, if the parameter is going to be ignored unless the -MaxWaitTimeInSeconds parameter is supplied, that should probably be documented. In fact, at that point, the parameter should probably be removed entirely. In its current state, it is not actually doing anything, as the blocking behavior is determined completely by -MaxWaitTimeInSeconds. This caused some confusion for me, as I assumed -BlockUntilImportComplete would make the function wait indefinitely, when in fact to do that you need to supply a value of -1 to -MaxWaitTimeInSeconds.

Let me know what you think. I'd be happy to modify the pull request to remove the -BlockUntilImportComplete parameter and update the documentation. While I'm at it, I can update it to describe the behavior when supplying a value of -1 to the -MaxWaitTimeInSeconds parameter.

Or we can take it even further and remove both parameters and provide documentation pointing the user to "Import-CrmSolution -AsyncOperationImportMethod," but of course, that would be introducing a breaking change.

**Comment by seanmcne** [comment]
Hey Tyler, I'm just going through doing a little cleanup today and noticed this.  Let me know if this is still a concern/issue and we can chat about it. Now that the timeout function is actually working in service client, I'm hoping this is less of a concern, but let me know. Thanks!
