### ISSUE TITLE
Get-CrmRecordsByFetch not working as expected

### ISSUE THREAD

**Issue by maerger** [seanmcne/Microsoft.Xrm.Data.PowerShell#354]
Hi there,
I'm wtrying to execute a fetch xml against an on-prem instance of D365 (Version 1612 8.2.1.176) and unexpected errors (unfortunately messages are in german):

Get-CrmRecordsByFetch : Die Argumenttransformation für den Parameter "AllRows" kann nicht verarbeitet werden. Der Wert "System.Char" kann nicht in den Typ "System.Management.Automation.SwitchParameter" 
konvertiert werden. Boolesche Parameter akzeptieren nur boolesche Werte oder Zahlen wie "$True", "$False", "1" oder "0".
In ...\ImportBusinessUnits.ps1:25 Zeichen:62
+ $rootBusinessUnit = Get-CrmRecordsByFetch -conn $conn -Fetch @fetch
+                                                              ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-CrmRecordsByFetch], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-CrmRecordsByFetch
 
Here is my code:
```
$conn = Connect-CrmOnPremDiscovery  -ServerUrl $CrmServerUri -OrganizationName $CrmOrganizationName -Credential $credential

$fetch = @"
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="businessunit">
    <attribute name="name" />
    <attribute name="address1_telephone1" />
    <attribute name="websiteurl" />
    <attribute name="parentbusinessunitid" />
    <attribute name="businessunitid" />
    <order attribute="name" descending="false" />
    <filter type="and">
      <condition attribute="parentbusinessunitid" operator="null" />
    </filter>
  </entity>
</fetch>
"@

$rootBusinessUnit = Get-CrmRecordsByFetch -conn $conn -Fetch @fetch
```

**Comment by kenglover** [comment]
In your last command to get-crmrecordsbyfetch @fetch should be $fetch

`$rootBusinessUnit = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch`
