### ISSUE TITLE
Import-Module fails on non-English machine caused by mis-encoded  Microsoft.Xrm.Data.PowerShell.psm1

### ISSUE THREAD

**Issue by yukurata-MS** [seanmcne/Microsoft.Xrm.Data.PowerShell#356]
`Import-Module Microsoft.Xrm.Data.PowerShell` version 2.8.1.1 or above fails on a machine of which System Locale is Japanese. From looking at the error message, it is caused by mis-encoded `Microsoft.Xrm.Data.PowerShell.psm1` in the Nuget package. The file is probably ISO8859-1 or something and therefore gets garbled when opened as UTF-8.
It is blocking the use of this PowerShell module for our customer. Repro'ed on more than one machine whose System Locale is Japanese.

**Comment by seanmcne** [comment]
Thanks for reporting, you're correct the file needs to be encoded in UTF-8.  Not sure how this changed exactly but i'll take a look at it for our next release.  Thanks for reporting this!

**Comment by seanmcne** [comment]
Thanks @kenakamu for the info on this. 

@yukurata-MS, yes, this happens after update 2.8.1.1.
![image](https://user-images.githubusercontent.com/2292260/55973770-d8bbce00-5c4b-11e9-92cf-125efd00198b.png)

The solution we need to take here is to save the file as UTF-8 in the next release - thank you for reporting!

**Comment by seanmcne** [comment]
Thanks for reporting this!  This is now fixed in the master branch, please download and test and let me know if it's 100% resolved (although I'm fairly confident a simple conversion to UTF-8 should have fixed it).
