### ISSUE TITLE
Error when trying to change account owner

### ISSUE THREAD

**Issue by MickaSecureIT** [seanmcne/Microsoft.Xrm.Data.PowerShell#358]
Hi
I have a script I launch to bulk modify account owner in CRM 2016 from a csv file with 2 column CompteID (ID of the account in CRM 2016) and Owner (Display name of the user in CRM 2016).
It looks like :

Function Get-FileName($initialDirectory)
{
    [System.Reflection.Assembly]::LoadWithPartialName("System.windows.forms") | Out-Null
    
    $OpenFileDialog = New-Object System.Windows.Forms.OpenFileDialog
    $OpenFileDialog.initialDirectory = $initialDirectory
    $OpenFileDialog.filter = "CSV (*.csv)| *.csv"
    $OpenFileDialog.ShowDialog() | Out-Null
    $OpenFileDialog.filename
}

$inputfile = Get-FileName "C:\CreationUsers"
$compteamodifier = Import-Csv $inputfile -Delimiter ";"
foreach ($comptecrm in $compteamodifier){
$CTM = Get-CrmRecord -EntityLogicalName account -Id $comptecrm.CompteID -Fields *
$ownercompte = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute fullname -FilterOperator eq -FilterValue $comptecrm.owner -Fields systemuserid
$ownercompteID = $ownercompte.CrmRecords[0].systemuserid.Guid
$CTM.ownerid = (New-CrmEntityReference -EntityLogicalName systemuser -Id $ownercompteID)
Set-CrmRecord -conn $conn -CrmRecord $CTM

}

It works until 2-3 months when I got an error 
System.InvalidCastException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #F1E0E00C

Indeed it seems that there is a format issue but I cannot solve it.
Can you help me ?

Regards

**Comment by seanmcne** [comment]
I would suggest logging out the data in powershell, my guess is that one of the inputs might be null or an invalid format for a GUID, etc. 

Also, you may want to consider only updating the fields that you expect to change (ie: owner).  Example may be something like: 

```powershell
foreach ($comptecrm in $compteamodifier){
    #is this really needed? From the code below it doesn't appear to be necessary and this should speed things up. 
    #$CTM = Get-CrmRecord -EntityLogicalName account -Id $comptecrm.CompteID -Fields *

    #if you already know the owner you could potentially just skip this and use the guid you already have
    $ownercompte = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute fullname -FilterOperator eq -FilterValue $comptecrm.owner -Fields systemuserid

    $ownercompteID = $ownercompte.CrmRecords[0].systemuserid.Guid

    #$CTM.ownerid = (New-CrmEntityReference -EntityLogicalName systemuser -Id $ownercompteID)
    #Set-CrmRecord -conn $conn -CrmRecord $CTM
    Set-CrmRecord -EntityLogicalName "new_entityname" @{"ownerid"=(New-CrmEntityReference -EntityLogicalName systemuser -Id $ownercompteID)}
}
```

**Comment by MickaSecureIT** [comment]
Hi
Thanks for your answer.
I was ill so I cannot answer before, sorry.
In the code you sent me, I don't get where I select the account to modify.
Otherwise, if I look at the field ownerid in my $CTM variable before changing the ownerid, I obtain this :
ownerid_Property                         : [ownerid, Microsoft.Xrm.Sdk.EntityReference]
ownerid                                  : SUISSA Michaël

After I got this
ownerid_Property                         : [ownerid, Microsoft.Xrm.Sdk.EntityReference]
ownerid                                  : Microsoft.Xrm.Sdk.EntityReference
I expected the full name of the new owner. 

Regards

**Comment by seanmcne** [comment]
I added the -Id param into my previous comment as an edit in the Set-CrmRecord, this is where the ID of the entity you want to update should be placed, I had forgotten that parameter before.  

Regarding your second question, the owernid attribute is an entityreference (pointer) to which record the owner is and what entity it's in, it would have an entitytypecode of 8 (systemuser, unless it were a team) and the ID of the systemuser or team who is the owner.  

The fullname of the owner can be found by querying the systemuser entity, or you can also get the fullname from the entity your querying, usually.  To do this you query for the owneridname attribute (which is a virtual attribute that simply passes the name value across from the related entity).  You can find the attributes for a given entity by using this command: 
```powershell
Get-CrmEntityAttributes -EntityLogicalName account |Select logicalname |sort logicalname
```

Hope this helps - thanks!

**Comment by MickaSecureIT** [comment]
Hi
It works !
Thanks a lot !

Regards
