### ISSUE TITLE
update org details for bulk system users

### ISSUE THREAD

**Issue by daraar** [seanmcne/Microsoft.Xrm.Data.PowerShell#364]
I am new to XRM Powershell.
I am trying to update Organization Information like Strategic Business Unit, Global Business Line, Legacy Division, Region,
Country for bulk users.

So, far I am able to update business unit using below

#Get all business Unit and store it in variable
$businessUnit = Get-CrmRecords -EntityLogicalName businessunit -FilterAttribute name -FilterOperator eq -FilterValue 'abc' -Fields businessunitid
$businessUnitId = $businessUnit.CrmRecords[0].businessunitid.Guid

#Set the system user business unit
Set-CrmRecord -EntityLogicalName systemuser `
-id $systemId -Fields @{ "businessunitid"=(New-CrmEntityReference -EntityLogicalName systemuser -Id $businessUnitId)}

How can I update Organization Information like Strategic Business Unit, Global Business Line in similar way?
Any help is appreciated.

**Comment by seanmcne** [comment]
Duplicate issue logged here: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/issues/31
