### ISSUE TITLE
CrmServiceClient.Execute w/ SetStateRequest

### ISSUE THREAD

**Issue by jrobiii** [seanmcne/Microsoft.Xrm.Data.PowerShell#365]
I had created an issue before, but the recommendation didn't work, [the issue was closed](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/357), and I'm still having trouble.  

It looks like the only difference in the example (provided in #357) is that
- It calls New-CrmOptionSetValue, and I was using New-Object Microsoft.Xrm.Sdk.OptionSetValue
- It calls ExecuteCrmOrganizationRequest on the connection where I was calling Execute.

I've modified my script to the following, but I get the same result (_Cannot find an overload for "ExecuteCrmOrganizationRequest" and the argument count: "1"._):
```
Import-Module Microsoft.Xrm.Data.Powershell

Connect-CrmOnPremDiscovery -InteractiveMode

$user   = "domain\jwalker"
$State = 1 
$Status = -1

$CRMusers = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq -FilterValue $user -Fields systemuserid,fullname,domainname,isdisabled

$systemuserid = $CRMusers.CrmRecords.systemuserid

$request = New-Object Microsoft.Crm.Sdk.Messages.SetStateRequest;
$SystemUser = New-Object Microsoft.Xrm.Sdk.EntityReference('SystemUser', $SystemUserId);
      
$request.EntityMoniker   = $SystemUser;
$request.State  = New-CrmOptionSetValue -Value 1;
$request.Status = New-CrmOptionSetValue -Value -1;

$conn.ExecuteCrmOrganizationRequest($request)
```

I'm pretty sure that I'm doing something correct with $request (Microsoft.Crm.Sdk.Messages.SetStateRequest), I just have no idea what it could be.

**Comment by seanmcne** [comment]
If you look at the module and how it finds failures, it looks at $conn's LastError/LastException (Unfortunately, I can't control this pattern/behavior as it's the way the xrm tooling connector works (I have no clue why it doesn't just throw exceptions, that would make things much easier for these helpers - but it's what we've got to work with). 

Looking at the exception using the script you've provided, I see: 
_The entity with a name = 'SystemUser' with namemapping = 'Logical' was not found in
the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True,
IsLoadedInStagedContext = False, Timestamp=617499,_

The first issue is just a casing issue, entity names have to be lower case: SystemUser should be systemuser. 

Second, I traced out the function call to disable a user in the webclient of the VM we had to build out to test this and adjusted the script below. This is working the newly created v9 VM I'm using.

```powershell
$user   = "domain\jwalker"

$CRMusers = Get-CrmRecords -EntityLogicalName systemuser -FilterAttribute domainname -FilterOperator eq -FilterValue $user -Fields systemuserid,fullname,domainname,isdisabled

$systemuserid = $CRMusers.CrmRecords[0].systemuserid

$request = New-Object Microsoft.Crm.Sdk.Messages.SetStateRequest;
$request.EntityMoniker   = New-Object Microsoft.Xrm.Sdk.EntityReference('systemuser', $SystemUserId);
$request.State  = New-CrmOptionSetValue -Value 1;
$request.Status = New-CrmOptionSetValue -Value -1;

$conn.ExecuteCrmOrganizationRequest($request)
```

And to enable the user - you can change the script to this: 
```powershell
$request = New-Object Microsoft.Crm.Sdk.Messages.SetStateRequest;
$request.EntityMoniker   = New-Object Microsoft.Xrm.Sdk.EntityReference('systemuser', $SystemUserId);
$request.State  = New-CrmOptionSetValue -Value 0;
$request.Status = New-CrmOptionSetValue -Value -1;
```

Note: tested on v9.0.2.3034 onprem build

**Comment by seanmcne** [comment]
Once tested and confirmed please feel free to add a PR with a new sample in the samples repo so others can also benefit from this.  Thanks!
