### ISSUE TITLE
Get-CrmConnection requires elevated rights

### ISSUE THREAD

**Issue by cfz42** [seanmcne/Microsoft.Xrm.Data.PowerShell#368]
I cannot login to my organization with my corporate computer which has limited rights.

The same powershell command runs fine on the azure devops pipeline.

```
PS X:\> $connection = Get-CrmConnection -ConnectionString `
>>           ("AuthType=Office365; " + `
>>           "Username=xxxxxxxx@customer.onmicrosoft.com; " + `
>>           "Password=xxxxxxx; " + `
>>           "Url=https://organization-url.crm4.dynamics.com")

Get-CrmConnection : Failed to connect to CRM: Unable to Login to Dynamics CRM
Au caractère Ligne:1 : 15
+ ... onnection = Get-CrmConnection -ConnectionString ("AuthType=Office365; ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Get-CrmConnection], Exception
    + FullyQualifiedErrorId : -10,Microsoft.Xrm.Tooling.CrmConnector.Powershell.Commands.GetCrmConnectionCommand
```

I doubt this is to be expected, especially when the same connection string works fine in a c# console project compiled and run on the same machine.

**Comment by seanmcne** [comment]
Try connect-crmonline -serverurl <url> -forceOAuth

**Comment by seanmcne** [comment]
To be clear, the module does not require any elevation.  Please be sure to install it from the gallery 

install-module "Microsoft.Xrm.Data.PowerShell" -scope CurrentUser

Also, I would recommend using connect-crmonline so it uses a connection string which behaves the way we expect.  Service Client has a nasty habit of completely changing, at times, based on different parameters - using this cmdlet helps make sure it behaves consistently.

**Comment by cfz42** [comment]
I installed it from the gallery, using the exact same command you provided.

Also, using connect-crmonline isn't really an option since I need the connection to be done automatically and from the few tests I've done with connect-crmonline, a popup appears and prompts for my username/password.

I really think Get-CrmConnection requires elevated rights (whether it be the command itself or one of its dependencies, no idea, haven't checked the code) since when I run the same command on my personal computer (with no restrictions at all) it works fine.

**Comment by seanmcne** [comment]
The prompt is only when incomplete parameters are given, the following won't prompt for a user input credential, 
```
Connect-CrmOnline -ServerUrl {url} -Cred $credential -ForceoAuth 
```
Also, connect-Crmonline does use get-crmconnection but it does so in a way I've tested with the connection string to offer consistent results. I'm unaware of any code that specifically requires elevation with CrmServiceClient, it's possible there is some kind of powershell policy with unsigned scripts at your workplace or some unique configuration that would force it to relaunch in admin mode or request elevation but I've not experienced that before myself or with other customers so far.

**Comment by MaxGress** [comment]
Hi, I had the exact same issue. Somehow I found a way to make it work. I changed the connection string to following:

```
-ConnectionString `
        ("AuthType = Office365;" + `
        "Domain = $env:EnvironmentName;" + `
        "Username = $env:ServiceAccountUpn;" + `
        "Password = $env:ServiceAccountPassword;" + `
        "Server = https://$env:EnvironmentName.crm4.dynamics.com")
```
