### ISSUE TITLE
Set-CrmUserMailbox runs as the target user id?

### ISSUE THREAD

**Issue by Diego-Saavedra-San-Juan** [seanmcne/Microsoft.Xrm.Data.PowerShell#369]
Hi!

First of all, thanks for this great module, it works great!

Now to the beef of the issue. I'm trying to approve and schedule mailboxes in Dynamics, however,  set-crmusermailbox gives me this error:

`
PS C:\dev\dynamics-powertools> Set-CrmUserMailbox -UserId cb18726d-bd9c-e911-a874-000d3ab54bd2 -StateCode Active -StatusCode Active -ScheduleTest -MarkedAsPrimaryForExchangeSync -ApproveEmail
User cb18726d-bd9c-e911-a874-000d3ab54bd2 should be a global administrator or exchange administrator to approve mailbox in organization 502d6af9-b927-4d42-aa27-71ed0b6da102. => User cb18726d-bd9c-e911-a874-000d3ab54bd2 should be a global administrator or ex
change administrator to approve mailbox in organization 502d6af9-b927-4d42-aa27-71ed0b6da102.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.1.3\Microsoft.Xrm.Data.Powershell.psm1:787 char:3
         throw LastCrmConnectorException($conn)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : OperationStopped: (User cb18726d-b...7-71ed0b6da102.:String) [], RuntimeException
    + FullyQualifiedErrorId : User cb18726d-bd9c-e911-a874-000d3ab54bd2 should be a global administrator or exchange administrator to approve mailbox in organization 502d6af9-b927-4d42-aa27-71ed0b6da102. => User cb18726d-bd9c-e911-a874-000d3ab54bd2 should  
   be a global administrator or exchange administrator to approve mailbox in organization 502d6af9-b927-4d42-aa27-71ed0b6da102. `

Which doesn't make too much sense since the user I'm running it from is a global administrator for exchange, and the user id it is using in the error message is the same as the user id for the user i'm trying to activate the mailbox for.

PS C:\dev\dynamics-powertools Get-MyCrmUserId
Guid                                
                        
46b53ad8-5ab9-e711-810b-5065f38aea11

PS C:\dev\dynamics-powertools>

**Comment by seanmcne** [comment]
Thanks! 
It looks like this users email address isn't approved. As you are an o365 global admin either press the approve email button on the users record in d365, or have run the cmdlet to approve it (approve-crmemailaddress) via powershell.  After that you should be able to test & enable the mailbox. 

PS: By default all new users email addresses are automatically approved now and are only unapproved if their primary email address is altered by someone in the system.  Hope this helps!

**Comment by Diego-Saavedra-San-Juan** [comment]
Thanks! It turns out even though I was running the powershell console as administrator it wasn't enough, it had to be logged in in a windows session.  Then it works.
