### ISSUE TITLE
Delete CRM Solution

### ISSUE THREAD

**Issue by sierrapeaks** [seanmcne/Microsoft.Xrm.Data.PowerShell#373]
Is there any mechanism to Delete or Uninstall or Remove a CRM Solution with Microsoft.Xrm.Data.PowerShell.  thanks

**Comment by seanmcne** [comment]
Great question! 

We don't have any specific function to help this, however if you have the solution ID you can easily delete it via a direct delete request - here is a sample I created quickly to show how delete a solution: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/Solutions/DeleteSolution.ps1

**Comment by sierrapeaks** [comment]
Great, thank you for quick response, just what i was looking for.
