### ISSUE TITLE
Question: How do you create a bulk delete task?

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#374]
We have a fetchXML that has the query that we want to use to bulk delete data.  How would we do this using the XRM.Data.PowerShell module?

**Comment by seanmcne** [comment]
Yep, there is already a sample for that: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/Microsoft.Xrm.Data.PowerShell.Samples/BulkDeleteJob/BulkDeleteJobCreate.ps1

**Comment by seanmcne** [comment]
Keep in mind, there is now some parallelism when deleting with this method but not a whole lot. It’s faster than deleting one after the other but it can still take quite a bit of time.
