### ISSUE TITLE
Add Microsoft.Xrm.Data.PowerShell to Chocolatey

### ISSUE THREAD

**Issue by mwolfaardt** [seanmcne/Microsoft.Xrm.Data.PowerShell#375]
Add the package to Chocolatey package manager  for easy install.

**Comment by seanmcne** [comment]
Hi, just an FYI it's already on the powershell gallery where it can be quite easily installed
```powershell
install-module Microsoft.Xrm.Data.Powershell -scope CurrentUser 
```
