### ISSUE TITLE
Get-CRMInstances Fails

### ISSUE THREAD

**Issue by achaganti** [seanmcne/Microsoft.Xrm.Data.PowerShell#376]
I am trying to connect to Dyn365 Online V9 via powershell and retrieve the list of all CRM instances however it fails with the following error:

# Get-CrmInstances -ApiUrl "https://admin.services.crm.dynamics.com"

Error Message: 
Get-CrmInstances : Unable to deserialize the response.
At line:1 char:1
+ Get-CrmInstances -ApiUrl "https://admin.services.crm.dynamics.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CrmInstances], SerializationException
    + FullyQualifiedErrorId : Microsoft.Rest.SerializationException,Microsoft.Xrm.OnlineManagementAPI.GetCrmInstances

Any ideas? I am on the most recent version of XRM module 3.8.2

**Comment by seanmcne** [comment]
Please file a support incident with Microsoft support, this module (code) does not provide this function.

Thanks!
