### ISSUE TITLE
Auth failures for some 2FA enabled accounts

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#383]
Starting in this release there's an adal conflict when connecting (under certain specific circumstances).  A fix is in the process, but if you receive the error it might look something like this: 

![image](https://user-images.githubusercontent.com/2292260/67440606-6eeb8c00-f5bf-11e9-9f7c-bc4b6b0902c0.png)

**Comment by jorge-martinez-v** [comment]
Hello!
I got the same error... :-(

When rolling back to version 2.8.1.3 I got this error:

![image](https://user-images.githubusercontent.com/57148054/67787910-236a2f80-fa50-11e9-9942-790f744f0919.png)

**Comment by jorge-martinez-v** [comment]
I got the same error, and rolling back to version "2.8.1.3" resolved my issue

**Comment by seanmcne** [comment]
Agreed, there was a fix shipped this weekend to the core connector and I need to get that packaged and updated hopefully in the next day or two.  Thanks for the update and confirmation!

**Comment by seanmcne** [comment]
@jorge-martinez-v in included the update and fix this evening and updated it on powershell gallery - I also took the time to get a true build & deploy process wired up so updates should be easier to push out in the future. Let me know if you see any issues with 2.8.4 (which only includes the xrm tooling connector update) - thanks!
