### ISSUE TITLE
Get-CrmRecords - ValidateSet Operator "like"

### ISSUE THREAD

**Issue by ryanlraines** [seanmcne/Microsoft.Xrm.Data.PowerShell#385]
Hello Sean, 

I'm wanting to return a filtered list of soltuions from my instance. 

I'm using `Get-CrmRecords -conn $conn -EntityLogicalName solution -Fields uniquename,publisherid,version -FilterAttribute uniquename -FilterOperator "like" -FilterValue $FOO -Verbose`

I know that I have solutions with uniquenames wherein $FOO exists, but no objects are returned.  Do I need to include wildcards?  

Thanks for your time.

**Comment by kenglover** [comment]
Hello @ryanlraines 
Yes, you need to include wildcards when using the "like" operator.
Ken

**Comment by ryanlraines** [comment]
@kenglover  Thanks for the reply. 

I tired the following, but I'm getting the same result. 

`$FOO = *<value>*`

`Get-CrmRecords -conn $conn -EntityLogicalName solution -Fields uniquename,publisherid,version -FilterAttribute uniquename -FilterOperator "like" -FilterValue $FOO -Verbose`

**Comment by seanmcne** [comment]
The problem is most likely due to the uniquename filter - if you pull the filter off can you see your solution? 

Get-CrmRecords -conn $conn -EntityLogicalName solution -Fields uniquename,publisherid,version -Verbose

**Comment by seanmcne** [comment]
Ok - the issue is using asterisks instead of percent signs, percent signs are generally used in sql with a "LIKE" operator but *'s are usually used by users and other wildcard patterns which is where the confusion comes in.  

Try this instead:
```powershell 
$FOO = "%<value>%"

Get-CrmRecords -conn $conn -EntityLogicalName solution -Fields uniquename,publisherid,version -FilterAttribute uniquename -FilterOperator "like" -FilterValue $FOO -Verbose
```
![image](https://user-images.githubusercontent.com/2292260/68884062-f2d4f780-06d7-11ea-8491-c1513011e0ab.png)

**Comment by ryanlraines** [comment]
@seanmcne using `%` characters worked.  

Thanks all!

**Comment by ryanlraines** [comment]
@seanmcne using % characters worked.

Thanks all!
