### ISSUE TITLE
***Change Proposal*** Connect-CrmOnline moving Default authentication to oAuth

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#387]
I'm considering a move which would Default the connection for Connect-CrmOnline to oAuth. 

Change proposal: 
- Connect-CrmOnline would default to using oAuth
- An optional switch parameter would be added called -ForceO365Auth 

I'm curious if there are concerns about this approach or possible issues. 

**Concerns list so far** with answers inline: 
- Why on earth would you even consider changing this!?  
  - oAuth is going to become the norm in the near future, also basic auth today is being shut off by customers forcing script writers to update their scripts just to add the -ForceoAuth switch.  By doing this by default, it should actually be more compatible for all online customers and it **will** follow MFA prompts for customers who use and enforce MFA. 
- Do I need to create and consent to a custom app?  
  - No, not today, a custom app would be optional, as it is today
- Do I need to change my code?  
  - No, this is only for the connection and auth flow, I anticipate no changes needed if this were to be the default. 
- How can I test this before?  
  - Connect-CrmOnline -ForceoAuth would be a valid test today  
- What if I use another auth behind AAD like Okta? 
  - That's Ok this will function with that configuration as it did before.

**Comment by thuld** [comment]
Sound like a very good idea to me!

**Comment by abvogel** [comment]
Sounds good to me. That's a flag I always use now and I imagine most companies are going that way as well.

We may also want to consider adding the ability to take certificates or client/secrets for authentication in the Connect-CrmOnline call to work with service accounts better.

**Comment by seanmcne** [comment]
For now I think I'll wait for a change to the CrmConnector - if that change doesn't appear to be coming soon then I'll see what moving our default to oAuth would look like (my biggest concern is somehow breaking any scripts).

**Comment by seanmcne** [comment]
Reference link: https://docs.microsoft.com/en-us/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-common-data-service

**Comment by seanmcne** [comment]
Linking to #473
