### ISSUE TITLE
How To: Support cloning and importing a solution when the major or minor version number changes

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#390]
Can you use the toolkit to clone and then import a new major/minor version of a solution?  If so how would we do this?  We are currently importing solutions using the Import-CrmSolutionAsync -MaxWaitTimeInSeconds $maxWaitTimeInSeconds -SolutionFilePath $ZipFile -OverwriteUnManagedCustomizations:$true -PublishChanges:$true -SkipDependancyOnProductUpdateCheckOnInstall:$true -ActivateWorkflows:$true -BlockUntilImportComplete:$true -verbose:$true

**Comment by seanmcne** [comment]
Yes there are cloneAsSolution and CloneAsPatch requests that can be used to create patches and solutions. 

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-patches-simplify-solution-updates

You can follow the request/response pattern and checking for errors like in this sample (you’ll need to add the parameters which I can also dig up or you can find in this module or find in this repo: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples). 

$request = new-object Microsoft.Crm.Sdk.Messages.{requestType}
$conn.ExecuteCrmOrganizationRequest($request)
if("" -ne $conn.LastCrmException)
{
    throw $conn.LastCrmException
}
