### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by jamescregg** [seanmcne/Microsoft.Xrm.Data.PowerShell#394]
Thanks for this module. It has been brilliant for automating tasks and deployments. 

One thing we would like to do it publish email templates. Can anyone advise how email templates can be imported. We have them in HTML format?

**Comment by seanmcne** [comment]
I don’t have any specific examples but you can simply create the records for that given entity. One tip is to use get-CRMrecords to inspect the rows for email templates for the format and values.

**Comment by seanmcne** [comment]
feel free to add something on the samples site (https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples)  hope you were able to figure this out.  Thanks !
