### ISSUE TITLE
Invoke-CrmRecordWorkflow: cannot use WorkflowId

### ISSUE THREAD

**Issue by auitz** [seanmcne/Microsoft.Xrm.Data.PowerShell#396]
Hello,

due to a problem with the if clause it is executed and this leads to an error.
if have replaced:
`if($WorkflowName -ne $null){`
with
`if(![string]::IsNullOrEmpty($WorkflowName)){ `
After that the error did not occur again.

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/765c97c080fa64a8fdfeef8372d909e541eb6be9/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L1306

**Comment by seanmcne** [comment]
can you share how you're calling the cmdlet which leads to the error?

Thanks!

**Comment by auitz** [comment]
I have just shortened it and reduced it to the essential but the call is as follows:
```
foreach( $entity in $entityListQuote ){
	$entity_data = Get-CrmRecords -EntityLogicalName $entity.entityName -FilterAttribute
$entity.entityField -FilterOperator eq -FilterValue $dataAccountSourceId -Fields "statecode", "statuscode"
	foreach( $item in $entity_data.CrmRecords ){
		#...
		$workflowId = "833d05d3-54d8-4435-8cbc-ae2e4c320690"
		#...
		Invoke-CrmRecordWorkflow -WorkflowId $workflowId -EntityId $item.ReturnProperty_Id
		#...
	}
}
```

I have also tried it completely without variables, but only the adjustment in the module brought the desired success
`Invoke-CrmRecordWorkflow -WorkflowId ec1043c1-dc5a-4739-9e2b-3a638de5b5f7 -EntityId f06fb8f9-58ba-4e62-8f02-60f2a3a0c521`

I also tried the workflow name and it worked great, but using the name was not in my interest as it can change without my knowledge.

**Comment by seanmcne** [comment]
Ok I figured out what the issue is, I think, it looks like the workflowname parameter has a blank value (not null) by default.  To accommodate both scenarios I switched to if(-not [string]::IsNullOrEmpty($WorkflowName)) instead of if($WorkflowName -ne $null).
