### ISSUE TITLE
File path specified in dataMapXml is not found

### ISSUE THREAD

**Issue by gashupl** [seanmcne/Microsoft.Xrm.Data.PowerShell#398]
Hello. 
I'm trying to import solution (XXX.zip) into Dynamics online instance using the following command: Import-CrmSolution -SolutionFilePath ..\Solutions\XXX.zip -conn $connection -ActivatePlugins $false

Unfortunately  I'm getting the following error message:

Importing solution file ..\Solutions\XXX.zip into: https://XXX.api.crm4.dynamics.com/XRMServi
ces/2011/Organization.svc/web?SDKClientVersion=9.0.41.1023
Import-CrmSolution : System.Management.Automation.RuntimeException: ************ Exception on ImportSolutionToCrm,
File path specified in dataMapXml is not found: ..\Solutions\XXX.zip
************ Exception on ImportSolutionToCrm, File path specified in dataMapXml is not found:
..\Solutions\XXX.zip
At line:1 char:1
+ Import-CrmSolution -SOlutionFilePath ..\Solutions\XXX ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution

When I'm importing the same XXX.zip file using manual import - everything goes well. 
Any idea?

**Comment by seanmcne** [comment]
Strange, is it a solution you've created or one from an ISV, maybe one that should be used with package deployer?

**Comment by seanmcne** [comment]
ah I was able to reproduce using an xml file that isn't compatible - i wonder if your zip file is in the correct format to be imported? 

![image](https://user-images.githubusercontent.com/2292260/75742809-6bd27c00-5cd4-11ea-957e-6c644519f1f8.png)

**Comment by gashupl** [comment]
Hey. 
The solution is a custom one and it was created using with SolutionPackager.exe tool from the latest version of SDK. 
When I'm importing it using Dynamics Web UI - the import operation is completed sucessfully. The problem happens only when I'm using Import-CrmSolution command line tool.

**Comment by sergeytunnik** [comment]
@gashupl could you check that it works fine with full path (i.e. d:\deploy\SomeFolder\Solutions\XXX.zip)?

**Comment by gashupl** [comment]
That's a valid clue!

When I'm using absolute path everything works. Example:
**Import-CrmSolution -SolutionFilePath "C:\Users\piog\Source\MPH\Scripts\XXX.zip" -conn $connection -ActivatePlugIns $false**

However when I'm trying to use relative one - I'm getting reported error. I've tried the following one. None of them is working for me:
**Import-CrmSolution -SolutionFilePath XXX.zip -conn $connection -ActivatePlugIns $false
Import-CrmSolution -SolutionFilePath .\XXX.zip -conn $connection -ActivatePlugIns $false
Import-CrmSolution -SolutionFilePath ".\XXX.zip" -conn $connection -ActivatePlugIns $false**

The solution file is stored inside the same folder as the script running the Import-CrmSolution command.

**Comment by gashupl** [comment]
Ok. It seems that Import-CrmSolution has some problem when the solution path is not a absolute one. In case of using relative path - I'm getting reported error every time. 

My workaround was something like that: 

$solution1FileName = "XXX.zip"
$currentLocation = Get-Location
$exportLocation = $currentLocation.tostring().Replace("Scripts", "Solutions")
Import-CrmSolution -SolutionFilePath $exportLocation\$solution1FileName -conn $connection

**Comment by seanmcne** [comment]
@gashupl - I think this is the way that the connector works, for some reason.  It might be worth reporting this as a product bug/issue (since it appears to be the call into "$conn.ImportSolutionToCrm($SolutionFilePath.." that's failing).
