### ISSUE TITLE
Set Polling Period when using Import-CrmSolutionAsync

### ISSUE THREAD

**Issue by tgradu** [seanmcne/Microsoft.Xrm.Data.PowerShell#399]
Hi Sean,

When using the Import-CrmSolutionAsync there is a polling period of 5 seconds ($pollingDelaySeconds = 5). 

When importing large solutions where the import takes more than an hour this can result in 720 requests / hour. 

I think it might help if it would be possible to pass the PollingDelaySeconds as an optional parameter to the Import-CrmSolutionAsync method, so that people can configure the polling interval and reduce the number of generated requests. Else if not specified, then it can default to 5 seconds. 

I know it's not much but given the service API call limits, I think it might help.

Thanks,
Radu

**Comment by seanmcne** [comment]
This makes sense, though the per user api limits are relatively high as opposed to these few calls - but this addition does make sense to me regardless.

**Comment by seanmcne** [comment]
Should be completed now in #406
