### ISSUE TITLE
Request for Get-CrmRecordAssociation cmdlet

### ISSUE THREAD

**Issue by fuentej** [seanmcne/Microsoft.Xrm.Data.PowerShell#400]
Would be nice to have a "Get-CrmRecordAssociation"

I am trying to see what field security profiles a given user is associated with...

If there is another way, please share.

Thanks!

**Comment by seanmcne** [comment]
Can you do a get-crmrecords against the securityprofile entity where any given record is associated to it. 

Alternatively, can you outline how you’d go about this with fetch or a api call?

**Comment by fuentej** [comment]
Not sure what you mean.  

I can get the FSP, using this command....
(Get-CrmRecords -EntityLogicalName fieldsecurityprofile -FilterAttribute name -FilterOperator eq -FilterValue "All Users" -Fields * -AllRows).CrmRecords

But I don't know how to get the users that have been added to that FSP.

**Comment by sergeytunnik** [comment]
@fuentej you can query systemuserprofiles intersection entity. It has mapping between users and FLPs.

**Comment by fuentej** [comment]
NICE, thanks!
