### ISSUE TITLE
Changing Meta-Data of an entity

### ISSUE THREAD

**Issue by Dolph-Dragon** [seanmcne/Microsoft.Xrm.Data.PowerShell#401]
Hello,

I am trying to change the meta data attribute " IsAuditEnabled " of an entity. 

So the command i am running is:

< Get-CrmEntityMetadata >

which gives me the meta data of the entity.

...
IsActivity                              : False
IsActivityParty                      : False
IsAuditEnabled                     : Microsoft.Xrm.Sdk.BooleanManagedProperty
...

So my question is, if the Module provides any functionality to change the "IsAuditEnabled" attribute. 

I am thankfull for every hint. 
Any further readings solving or helping with this issue are appreciated.

Best regards

Dolph

**Comment by seanmcne** [comment]
Checkout this sample - it might work to adjust this over to using the audit enabled property. 


https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/91c53fef16f14755135f5a4d2fa8d416af11246b/Metadata/ToggleChangeTracking.ps1

**Comment by Dolph-Dragon** [comment]
Hello Sean,

Thank you for your fast response! 

I used your sample code and modified it for my purpose. Here is the code i use: 
```
function EnableIsAuditEnabled($EntityName){ 
       write-output "Finding entity: $EntityName" 
       $entityRetrieve = new-object Microsoft.Xrm.Sdk.Messages.RetrieveEntityRequest 
       $entityRetrieve.EntityFilters = 1 
       $entityRetrieve.LogicalName = $EntityName 
       $response = $conn.ExecuteCrmOrganizationRequest($entityRetrieve) 
       write-output "Current value for IsAuditEnabled on $EntityName is:    $($response.EntityMetadata.IsAuditEnabled)" 
       $response.EntityMetadata.IsAuditEnabled=$true 
       $entityUpdate = new-object Microsoft.Xrm.Sdk.Messages.UpdateEntityRequest 
       $entityUpdate.Entity = $response.EntityMetadata 
       write-output "Setting IsAuditEnabled to: True on $EntityName" 
       $response = $conn.ExecuteCrmOrganizationRequest($entityUpdate) 
       if("" -ne $conn.LastCrmException) 
       { 
         throw $conn.LastCrmException     
       }
 }
```

This gives me the following Error:

PS H:\>  EnableIsAuditEnabled account
Finding entity: account
Current value for IsAuditEnabled on account is: Microsoft.Xrm.Sdk.BooleanManagedProperty
Setting IsAuditEnabled to: True on account
ScriptHalted
In C:\harmsdo Workspace\Powershell\changeAuditenabled.ps1:58 Zeichen:10
+          throw $conn.LastCrmException
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

Maybe the Error is caused by trying to change "Microsoft.Xrm.Sdk.BooleanManagedProperty" to a boolean value? 

Do u have any ideas on this error? 
Any help is appreciated. 

Best regards 
Dolph

**Comment by sergeytunnik** [comment]
You should probably change next line:
`$response.EntityMetadata.IsAuditEnabled=$true`
to
`$response.EntityMetadata.IsAuditEnabled = New-Object -TypeName Microsoft.Xrm.Sdk.BooleanManagedProperty -ArgumentList $true`

**Comment by seanmcne** [comment]
If you've sorted this out please feel free to add it to the samples repo for this module - thanks! 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples

**Comment by Dolph-Dragon** [comment]
Thank you @sergeytunnik! 
It worked for me :) 

@seanmcne I will try to do this :)
