### ISSUE TITLE
Support MultiThreading?

### ISSUE THREAD

**Issue by WellerPShell** [seanmcne/Microsoft.Xrm.Data.PowerShell#408]
I am attempting to run a large update across approx 400 entities
Using On Premise SSL Get-CRMConnection to connect
I then run some metadata checks to get the entity list and then run a fetchxml to get the records I want to update

    $i=0
    foreach ($Entity in $New){
    $i++

    $FetchXML = @"
    <fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
      <entity name="$($Entity.logicalname)">
        <filter type="and">
          <condition attribute="xcor_colour" operator="ne" value="#09a592" />
        </filter>
      </entity>
    </fetch>
    "@
         Write-Progress -Activity "Checking If Colour Exists" -Status "$($Entity.EntityName) : $i of $($New.Count)" -PercentComplete (($i / $($new.Count)) * 100) -CurrentOperation OuterLoop
    $EntityMetadata = Get-CrmEntityAttributeMetadata -conn $conn -EntityLogicalName $entity.LogicalName -FieldLogicalName xcor_colour -ErrorAction SilentlyContinue

    if ($EntityMetadata){
        Write-Host "EntityMetadata Found"
        Write-Host "Fetching Records"
        $Records = Get-CrmRecordsByFetch -conn $conn -Fetch $FetchXML -AllRows
        $O = 0
        foreach ($Record in $Records.CrmRecords){
        $O++
        Write-Host "Transforming $($Record.ReturnProperty_Id)" -ForegroundColor Cyan
        Write-Progress -Activity "Setting Link Colour $($Entity.EntityName)" -Status "$O of $($Records.Count)" -PercentComplete (($O / $($Records.Count)) * 100) -CurrentOperation InnerLoop
            Set-CrmRecord -conn $conn -EntityLogicalName $Entity.LogicalName -Id $Record.ReturnProperty_Id -Fields @{"xcor_colour" = "#09a592"}
            Write-Host "Record Transformed"
        }
    }
    else{Write-Host "$($Entity.EntityName) Does Not Contain Colour Attribute)"}
    }

This in itself works however it is taking a very long time to complete
Each entity has approx 500k records inside of it
I believe it is because it is running single threaded opposed to multi threaded
Is there anything that can be done to increase the throughput of the sets?

Thanks

**Comment by sergeytunnik** [comment]
Hi.
Since it's on-prem and the logic of data modification is very straightforward, I would do direct SQL updates. SQL will be several orders of magnitude faster. Plus no bothering with multithreading.

If you really don't want to go SQL way. Just split your list of entities on 2,3,5,10 whatever parallelism you want. And run your script in several PowerShell windows at the same time with different parts of entities list.
KISS - keep it simple stupid :)

**Comment by seanmcne** [comment]
Powershell is great for scripting and quick fixes, etc, but it isn't super well suited for multi-threading/high performance (at least not with this connector and the way it's scripted today).  You could use a function which keeps all operations in it's scope and clones the service proxy (each operation needs it's own) and you'll probably need to dispose of each one, etc.  It's certainly possible, but by the time you put the time into it you might be best off using the new alpha/beta .NET core SDK and code or some lib's like the xrm core designed for massively parallel operations.  Hope that helps!
