### ISSUE TITLE
issue passing varible with space in it.

### ISSUE THREAD

**Issue by fuentej** [seanmcne/Microsoft.Xrm.Data.PowerShell#409]
This works
$Roleobj = (Get-CrmRecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue "_Role Name" -Fields * -AllRows).CrmRecords

This does not
$Role = "_Role Name"
$Roleobj = (Get-CrmRecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue $Role -Fields * -AllRows).CrmRecords

$Roleobj = (Get-CrmRecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue "$Role" -Fields * -AllRows).CrmRecords

$Roleobj = (Get-CrmRecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue "$($Role)" -Fields * -AllRows).CrmRecords

$Roleobj = (Get-CrmRecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue $($Role) -Fields * -AllRows).CrmRecords

Would prefer not to have to hardcode the role name in the command.

**Comment by seanmcne** [comment]
I just tried to reproduce the problem and cannot, are you able to use the same script I did and reproduce the problem? 
```
get-crmrecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue "Schedule Manager"   
$name = "Schedule Manager" 
get-crmrecords -EntityLogicalName role -FilterAttribute name -FilterOperator eq -FilterValue $name  
```
![image](https://user-images.githubusercontent.com/2292260/77027840-45b00b80-6965-11ea-952a-f399f80de86b.png)
