### ISSUE TITLE
Can you get the the SID of the systemuser?

### ISSUE THREAD

**Issue by jeffreynelson** [seanmcne/Microsoft.Xrm.Data.PowerShell#410]
The get-crmrecord does not seem to be able to return the SID of the system user entity.  Is there a way to return this in the list of attributes?  We have a case where the use in AD has been disabled, renamed, then re-enabled. and need to update the system user entity with the updated login id from AD.

**Comment by seanmcne** [comment]
Assuming this is for on premise: Unfortunately, the ActiveDirectoryGuid is an internal attribute which isn’t enabled for read operations via the supported APIs which this library uses (at least as of CRM 8.2, I assume it still is that way). The best I could offer is getting the info from the the systemuserbase table to get the adguid of the user, which isn’t “supported” but would get the info - or if you use claims Auth in Orem you can just use the system users UPN which is accessible via the APIs.
