### ISSUE TITLE
Set-CRM Record fails on setting Value of Type "Decimal Number"

### ISSUE THREAD

**Issue by danielsevinc** [seanmcne/Microsoft.Xrm.Data.PowerShell#412]
When using the Set-CrmRecord -CrmRecord $record and trying to set a value for field in Dynamics 365 of type "Decimal Number" and parsing the variable to decimal:
$branch.brn_branchindex = [decimal]::Parse($accFreeBranchNumber)
 it fails with following error:

Failed when casting CrmDataTypeWrapper wrapped objects to the CRM Type. Field : new_brn_branchindex2
Specified cast is not valid.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.8\Microsoft.Xrm.Data.Powershell.psm1:820 char:3
throw LastCrmConnectorException($conn)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed when cas...t is not valid.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed when casting CrmDataTypeWrapper wrapped objects to the CRM Type. Field : new_brn_branchindex2
Specified cast is not valid.

**Comment by seanmcne** [comment]
I noticed this in the call stack --> "Failed when cas...t is not valid.:String"

Have you tried updating this field as a string datatype? 

Also, if you execute a get-crmrecords for this type and get a sample record, what type is the attribute on the resulting record?

**Comment by danielsevinc** [comment]
I receive it as empty, cause it is an empty field which i want to fill in data for the first time.
How can I receive the type of the attribute?

**Comment by seanmcne** [comment]
Apologies, this fell off my radar somehow, is this still something you're struggling with?
