### ISSUE TITLE
Import-CrmSolution  sdkmessageprocessingstep With Id =  XYZ Does Not Exist

### ISSUE THREAD

**Issue by alenzurfluh** [seanmcne/Microsoft.Xrm.Data.PowerShell#413]
We are using Import-CrmSolution to a import solution files into a target organization. This worked fine for more than a year. Now we have new solution which is failing the error we get is:

VERBOSE: Calling .ImportSolutionToCrm() this process can take minutes...
VERBOSE: ImportId: 00000000-0000-0000-0000-000000000000
Import-CrmSolution : System.Management.Automation.RuntimeException: sdkmessageprocessingstep With Id = 
f392bf3f-ca78-ea11-9101-005056b80b10 Does Not Exist
At C:\Dynamics\PowerShellProjects\ExportImport\TestExportImport365.ps1:94 char:1
+ Import-CrmSolution -conn $BuildConnection -SolutionFilePath $SolutionImportFile  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution

Import-CrmSolution : System.Management.Automation.RuntimeException: sdkmessageprocessingstep With Id = 
67e0fa13-cc78-ea11-9101-005056b80b10 Does Not Exist
At C:\Dynamics\PowerShellProjects\ExportImport\TestExportImport365.ps1:94 char:1
+ Import-CrmSolution -conn $BuildConnection -SolutionFilePath $SolutionImportFile  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

We tried the following
* We searched the database (on both the source and target organization for an SDKmessageprcessingstep with that GUID) ==> Nothing found
* Also checked the solution file ==> Nothing found
* Removed all plugins/SD steps from the solution. But the import still fails.

When using the frontend to import the SAME solution file all works fine? That's very strange.

The GUID displayed in the error message seems to be changing for every time your run the import-CrmSolution command.

Please advise.

Thanks
Alen

**Comment by seanmcne** [comment]
What command and parameters are you running?  

Import-CrmSolutionAsync?  And if so, which switch params are you setting when importing? The connector used is the connector provided to execute import messages using the SDK - if there is some kind of difference my best suggestion would be to first verify the attributes/params and second, look at opening a ticket.

**Comment by alenzurfluh** [comment]
Hi

We are using:

Import-CrmSolution -conn $BuildConnection -SolutionFilePath $SolutionImportFile -Verbose

No other params are set. 

Is there a way to enable more tracing/logging? I've checked the CRM trace files....and couldn't find any usefully information.

Thanks
Alen

**Comment by seanmcne** [comment]
you can check the connector logs which I think is in this path: 
%AppData%\Roaming\Microsoft Corporation\Microsoft® Windows® Operating\

Can you try: 

```powershell
Import-CrmSolution -conn $BuildConnection -SolutionFilePath $SolutionImportFile  -ActivatePlugIns -OverwriteUnManagedCustomizations 
```
Additionally, you can try import using the async cmdlet - hopefully a combination of the switches will emulate what you're seeing better in the UI.

**Comment by alenzurfluh** [comment]
thanks Sean. Using the -ActivatePlugIns switch solved the issue.

**Comment by seanmcne** [comment]
Awesome, this is good to know in case anyone else runs into it!  Thanks for the follow up!
