### ISSUE TITLE
Create new record with activityparty field

### ISSUE THREAD

**Issue by HamEv** [seanmcne/Microsoft.Xrm.Data.PowerShell#414]
I want to create a new record, where one of the field is an activityparty field (from). 

Creating the activityParty List:
```
$activityParties = New-Object Microsoft.Xrm.Sdk.EntityCollection       
[Microsoft.Xrm.Sdk.Entity]$from = New-Object Microsoft.Xrm.Sdk.Entity
$from.LogicalName = 'activityparty'
$from.Attributes['partyid'] = $fromUserRef 
$activityParties.Entities.Add($from)  
```
Creating the new record:
 ```
$portalCommentId = New-CrmRecord -conn $conn -EntityLogicalName my_comment -Fields @{
                               "regardingobjectid"= New-CrmEntityReference -EntityLogicalName "incident" -Id $IncidentId;
                               "description" = "xxx";
                               "from" = $activityParties;
                               "ownerid" = $currentUserRef;   
                               "actualend" = $CommentCreated; 
                               "directioncode" = New-CrmOptionSetValue -Value 1   

```
Unfortunately there is an error thrown
_|=> The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize 
parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:request. The InnerException message was 'Error in line 12 position 1199. Element 
'http://schemas.datacontract.org/2004/07/System.Collections.Generic:value' contains data from a type that maps to the name 'System.Management.Automation:PSObject'. The deserializer has no 
knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'PSObject' and 
namespace 'System.Management.Automation'.'.  Please see InnerException for more details._

Does anyone know, how I can pass an activity field to my record?

Thanks!

**Comment by seanmcne** [comment]
Check this out for a pattern of how to create an activity:

https://stackoverflow.com/questions/23389031/create-activityparty-in-crm-without-early-bound-entities

**Comment by HamEv** [comment]
Hi,
thanks for the response. I tried to to this with powershell, but unfortunately it's not working and fails wehen creating the entity. 

```
[Microsoft.Xrm.Sdk.Entity]$from = New-Object Microsoft.Xrm.Sdk.Entity("activityparty")
   $from["partyid"] = $fromUserRef   

   [Microsoft.Xrm.Sdk.Entity]$portalComment = New-Object Microsoft.Xrm.Sdk.Entity("my_comment")
   $portalComment["regardingobjectid"] = New-CrmEntityReference -EntityLogicalName "incident" -Id $IncidentId
   $portalComment["description"] = "xxx"
   $portalComment["from"] = $from
   $portalComment["ownerid"] = $currentUserRef
   $portalComment["actualend"] = $CommentCreated
   
   $portalCommentId = $conn.Create($portalComment)
```
Exception:
Exception calling "Create" with "1" argument(s): "The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter 
http://schemas.microsoft.com/xrm/2011/Contracts/Services:request. The InnerException message was 'Error in line 1 position 8378. Element 
'http://schemas.datacontract.org/2004/07/System.Collections.Generic:value' contains data from a type that maps to the name 'System.Management.Automation:PSObject'. The deserializer has no 
knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'PSObject' and 
namespace 'System.Management.Automation'.'.  Please see InnerException for more details."
At xxxx.ps1:409 char:4
+    $portalCommentId = $conn.Create($portalComment)
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FaultException
 

Do you have any idea?

Thanks

**Comment by seanmcne** [comment]
Sorry for the delay. I'm thinking the default entity object must be having some property set on it that's a PSObject, new-crmrecord should build up the new record in a way that a create should work.
