### ISSUE TITLE
Looking for Set-CrmUserSecurityRoles 

### ISSUE THREAD

**Issue by saeid-adz** [seanmcne/Microsoft.Xrm.Data.PowerShell#415]
I want to use this module to manage some onboarding automation process. Is there any command to set the user role? 
Also, it seems we can not fetch the other users Id? right?

Thanks!

**Comment by seanmcne** [comment]
check out: add-CrmSecurityRoleToUser, that will allow you to assign roles. 

Check this out - the scenario is different, it's removing roles but hopefully it helps you a bit: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/c2440dff11bf75c62cb5a9aee386152fbb3990fe/UserOperations/Role_RemoveRoleFromAllUsers.ps1

**Comment by saeid-adz** [comment]
Thanks man! 
You helped me a lot, I don't know why I didn't see the add-CrmSecurityRoleToUser!
