### ISSUE TITLE
assign a security role to a D365 user using Windows Powershell, 

### ISSUE THREAD

**Issue by mikushin** [seanmcne/Microsoft.Xrm.Data.PowerShell#417]
I am trying to assign a security role to a D365 user using Windows Powershell, with Microsoft.Xrm.Data.Powershell module.
Is there a way or a command to do it?

**Comment by seanmcne** [comment]
Hi - yes, absolutely!  

I recommend using the following: 
```
Add-CrmSecurityRoleToUser
```
to get a dump of all the cmdlets/functions available, after you install/import the module, you can also use 
```
gcm -Module microsoft.xrm.data.powershell
```
This will dump a full list of all cmdlets inside of the Microsoft.xrm.data.powershell module.

Finally, you can always check out the powershell script source here, in this file you'll find all the code & functions used in the module where you can find out how it works or how it was built:
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/master/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1

Thanks!
