### ISSUE TITLE
Set-CrmConnectionTimeout not working after connecting

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#421]
After a lot of various issues logged, I've finally figured out the inconsistencies on connection timeouts.  For various reasons, once you connect to a CDS instance the timeout is locked and cannot be changed (apparently it is a WCF _issue_ or limitation or design flaw, etc).  

If you're struggling with a timeout, please try this: 

```
Import-Module Microsoft.Xrm.Data.PowerShell

#use this or change the 600 seconds to whatever your timeout is 
Set-CrmConnectionTimeout -TimeoutInSeconds 600

#now reconnect to d365/CDS using connect-CrmOnline ... etc...  
#once reconnected then try the operation again 
```
For net new connections, you can run the two lines of code prior to connecting in the first place, this can be verified (if using oAuth with the following code after connecting): 

```
$conn.OrganizationWebProxyClient.Endpoint.Binding.SendTimeout.TotalMinutes
```

**Comment by dylanberry** [comment]
Thanks for this @seanmcne!

**Comment by seanmcne** [comment]
I'm also looking at adding a timeout parameter to the connect-CrmOnline cmdlet

**Comment by qdi-jeffd** [comment]
The new integer parameter for connect-crmonline, ConnectionTimeoutInSeconds, does not seem to work. The timeout still reports 2 minutes when I connect with that. My connect line in my script is as follows:

Connect-CrmOnline -ConnectionTimeoutInSeconds 300 -Credential $cred -ServerUrl "https://redsdev.crm3.dynamics.com" -ForceOAuth

I was able to get it working via use the Set-CrmConnectionTimeout command first then connecting. After that the timeout reports 5 minutes as desired in my case.

**Comment by seanmcne** [comment]
@qdi-jeffd - yep looks like a bug where the parameter mapping to setting the timeout got missed, i'll get it corrected.

**Comment by seanmcne** [comment]
All fixed in #435 - it's also live on the gallery now as well - thanks for reporting this!

**Comment by qdi-jeffd** [comment]
Sweet! Thanks for the speedy turn around, I can confirm it now works for me!

**Comment by PoojaBansal-maker** [comment]
hey can you tell me at which place we need to add Set-CrmConnectionTimeout -conn $conn -TimeoutInSeconds 1200 to increase time @improving-jeffd

**Comment by improving-jeffd** [comment]
@PoojaBansal-maker 
If you're on the latest version you only need "Connect-CrmOnline -ConnectionTimeoutInSeconds 300" plus whatever other options you need for your specific connection (ie ServerUrl, Credential).

If you're not on the latest version of this PowerShell Module and for some reason cannot update, then just add the Set-CrmConnectionTimeout call right before you connect.

Also you can log out the connection timeout with a line similar to the following to ensure it took:
Write-Host "Connection Timeout in Minutes:" $conn.OrganizationWebProxyClient.Endpoint.Binding.SendTimeout.TotalMinutes

Hope that helps!
