### ISSUE TITLE
Add-CrmSecurityRoleToUser fails

### ISSUE THREAD

**Issue by edee209** [seanmcne/Microsoft.Xrm.Data.PowerShell#423]
Hi, I'm having problems with Add-CrmSecurityRoleToUser in my script and the issue is reproducible using one of the Get-Help examples.
If I add the role using the GUI it works and running '$sysuserroles = Get-CrmRecords' from #168 afterwards shows the same guids as used in the examples below.

Below is with version 2.8.8 :
>$user = Get-CrmRecord systemuser d67dcf6d-9cad-e711-80e8-0050569a1daf fullname
>$role = Get-CrmRecord role b5908975-c721-43df-9759-a6afb9a2688a name
>Add-CrmSecurityRoleToUser $user $role
>At C:\myPath\WindowsPowerShell\Modules\microsoft.xrm.data.powershell\Microsoft.Xrm.Data.Powershell.psm1:1108 char:9
+         throw LastCrmConnectorException($conn)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:String) [], RuntimeException
    + FullyQualifiedErrorId :

**Comment by seanmcne** [comment]
Can you try this? And reference the examples for help as well
‘’’
#help 
Get-Help Add-CrmSecurityRoleToUser -Full

$user = d67dcf6d-9cad-e711-80e8-0050569a1daf

$role = b5908975-c721-43df-9759-a6afb9a2688a 

Add-CrmSecurityRoleToUser $user $role
‘’’

**Comment by edee209** [comment]
It's failing in Add-CrmRecordAssociation at
$AssociateRequest = [Microsoft.Xrm.Sdk.Messages.AssociateRequest]::new();

It looks like I'll have to arrange an upgrade from PS4.
Version 2.8.1.3 also appears to be an option until then.
Thanks for your help!
