### ISSUE TITLE
Connect-CrmOnline fails to connect with ClientSecret method

### ISSUE THREAD

**Issue by agupta-au** [seanmcne/Microsoft.Xrm.Data.PowerShell#427]
## Issue
The `Connect-CrmOnline` cmdlet is failing when using a Service Principal to connect.

## Error
`Unable to Login to Dynamics CRM OrgnizationWebProxyClient is null`

## Expected Outcome
Successful connection.

## Steps to reproduce
1. Run the following PS command:
    `$conn = Connect-CrmOnline -ClientSecret ***** -OAuthClientId $ApplicationId -OAuthRedirectUri $CrmInstanceUrl`

2. The resulting `$conn` object shows the error.

## Likely cause
It seems the issue was likely introduced in: #402  on [Line 127](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/master/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L127)

## Workaround
Currently, I'm using:
    `$conn = Get-CrmConnection -ConnectionString "AuthType=ClientSecret;Url=https://[instanceUrl].crm[n].dynamics.com;ClientId=$ApplicationId;ClientSecret=*****"` to override the global `$conn` variable.

Using this, the rest of my scripts work fine.

## Recommendations
OAuth is suitable for interactive sessions only. I think the CmdLet should be modified to explicitly differentiate between OAuth and `ClientSecret` methods.

Additionally, the cmdlet prompts me to provide a value for the mandatory `$OAuthRedirectUri` which I do not have set up - this is optional for the App Registration and should not be required when using the `ClientSecret` method.

I also feel that users may benefit from from being able to supply a ConnectionString directly:
    `$conn = Connect-CrmOnline -ConnectionString "AuthType=ClientSecret;Url=https://[instanceUrl].crm[n].dynamics.com;ClientId=$ApplicationId;ClientSecret=*****"`

**Comment by seanmcne** [comment]
You could supply a connection string directly using the underlying xrm tooling module.  When a user takes their own connectionstring and passes it in, there can be wild differences in behavior of xrm toopling so the concept behind connect-crmonline was to bring a bit more structured approach to connecting that would, hopefully, behave in a more predictable way and provide better consistency/reliability for troubleshooting and specific to online (whereas connection strings can be used for both online and onprem). 

That said, passing it through with no checking is somewhat trivial, what circumstances are you seeing where having a totally open connection string would be advantageous as opposed to a parameterized / consistent experience (outside of either a bug or gap like this)?

**Comment by agupta-au** [comment]
So, in my particular usecase: I'm using [Wael Hamze's Power DevOps Tools](https://marketplace.visualstudio.com/items?itemName=WaelHamze.xrm-ci-framework-build-tasks) in a DevOps pipeline. My PowerShell script runs at the end of my pipeline, and I'd like to be able to use the same connection string that I'm using in my pipeline (supplied via variable groups).

Semi-related note, I seem to receive a PermissionDenied when I run the `Get-CrmConnection` cmdlet in the DevOps pipeline with a connection string. The same works outside of Azure DevOps with no issues.

**Comment by seanmcne** [comment]
I was also able to reproduce this myself, I think, I have found a permission issue as well with certain auth flows.  I believe this is due to the tokenpath being hard coded in various flows or the log directory being hard coded.  There is likely a workaround by adding a tokenpath and I just need to find the time to implement that in the latest auth branch that's sync'd up here on github: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/tree/oAuthWithNoWindowsCredentialPrompt

**Comment by seanmcne** [comment]
Coming soon (hopefully) I'm adding a switch to bypass the token cache path which should address your issue - thanks for reporting this! 
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/pull/428/commits/3aeead2998900f616d3420f1cbfc9aa090014335#diff-b3587c1090e6c2bcbac2f6d0d7963f18R178 #428

**Comment by agupta-au** [comment]
That's great! Thanks, Sean!
And, please keep up the great work!
