### ISSUE TITLE
Unable to use PreserveCrmRecordId switch

### ISSUE THREAD

**Issue by andrew-sumner** [seanmcne/Microsoft.Xrm.Data.PowerShell#430]
My goal is to add a new record and specify the id.  

I can create the record using the fields argument, however that isn't supported by the PreserveCrmRecordId switch. 

Unfortunately I'm not able to retrieve a CRM record so I have been attempting to create one as follows:

```
        $endpoint = New-Object PSObject -Property @{
            logicalname       = "serviceendpoint"
            serviceendpointid = $ServiceEndpointId
            name              = $ServiceName
            namespaceaddress  = $ServerUrl
            saskeyname        = $ServiceBusSasKeyName
            saskey            = $ServiceBusSasKey
            path              = $QueueName
            authtype          = (New-CrmOptionSetValue 2)
            contract          = (New-CrmOptionSetValue 6)
        }

        $id = New-CrmRecord -conn $Connection -CrmRecord $endpoint -PreserveCrmRecordId
```

The output I'm getting is 

```
C:\Work\RegisterD365EndPoint.ps1 : Cannot bind argument to parameter 
'EntityLogicalName' because it is an empty string.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,RegisterD365EndPoint.ps1
```

Is there any way to either programmatically build a CRM record object, or use the PreserveCrmRecordId switch with the fields argument?

**Comment by seanmcne** [comment]
endpoint isn't actually a CrmRecord which is why it's most likely not working, I'd suggest using this format instead - this will create a new record with whatever values you pass in including the ID. 

```
New-CrmRecord serviceendpoint @{"serviceendpointid"="{GUID}";"name"="ServiceName"}
```

**Comment by andrew-sumner** [comment]
Yep, just twigged to that about 5 minutes ago then read your post. Must have been user error when it failed the first time.

Thanks for the update.
