### ISSUE TITLE
Override CreatedBy?

### ISSUE THREAD

**Issue by WellerPShell** [seanmcne/Microsoft.Xrm.Data.PowerShell#431]
Evening,

I am creating new records using the following:

$Record = New-CrmRecord -conn $conn -EntityLogicalName $entityname-Fields @{"f1" = "Automated Upload From Backlog"
                                                                                    "ownerid" = $BCREF
                                                                                    "createdby" = $BCREF
                }

The record creates successfully
The ownerID populates with the EntityReference
However the createdby populates as my own User
Is there an overridecreatedby or anything I can use to get around this issue?

Regards
Weller

**Comment by seanmcne** [comment]
You'd have to impersonate the user you want to create the record as by setting the impersonation ID, you can override the createdon date using overriddencreatedon field, but as far as I know you can't set the createdby field directly without using impersonation.
