### ISSUE TITLE
Authentication failing when password contains semicolon

### ISSUE THREAD

**Issue by sanjint** [seanmcne/Microsoft.Xrm.Data.PowerShell#437]
Using the CmdLets to connect will fail, when the password contains a semicolon.

The generation of the connection string [here](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/0d571982a21cfd3872088394757d52cc5ded8623/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L227) and [here](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/0d571982a21cfd3872088394757d52cc5ded8623/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L218) is causing it.

Interactive logon (Connect-CrmOnlineDiscovery -InteractiveMode) is not affected.

**Comment by seanmcne** [comment]
Fixed in #434 I'll try to get this released to the gallery either this week or next - thanks!
