### ISSUE TITLE
Export-CrmSolution command hangs even though solution export completed

### ISSUE THREAD

**Issue by mwebster5589** [seanmcne/Microsoft.Xrm.Data.PowerShell#439]
When running the Export-CrmSolution command, sometimes it hangs even though I can see the export operation completed successfully in the Solution History in CRM. 

My script:
Write-Host "Installing PowerShell Module..."
Install-Module -Name “Microsoft.Xrm.Data.Powershell” -MinimumVersion 2.7.2 -Force

Write-Host "Connecting to CRM..."
$c = Connect-CrmOnline -ServerUrl $DynamicsUrl -ClientSecret $ClientSecret -OAuthClientId $ClientId -ConnectionTimeoutInSeconds 3600

Write-Host "Exporting solution..."
Export-CrmSolution -SolutionName "SolutionName" -Managed -SolutionFilePath "directory\Managed.Solutions" -SolutionZipFileName "Solution_managed.zip"

I'm running this script as part of an ADO pipeline.

**Comment by seanmcne** [comment]
This appears to possibly be related to the auth login issue taking place this afternoon: 
https://twitter.com/MSFT365Status/status/1310696819135901696

Let me know if this continues to happen after this issue clears - also are you installing the latest version 2.8.11?

**Comment by mwebster5589** [comment]
It seems this may have been due to the login issue. My pipeline has run twice now and I did not see this issue. Thank you for your quick response!

**Comment by mwebster5589** [comment]
Just ran into this again today, so reopening the issue; it's seems to be intermittent though. To answer the question about versioning from your last comment, with using the MinimumVersion parameter in Install-Module, it's my understanding it gets the version indicated unless a newer version is available; therefore, the newest should have been installed. I can remove that parameter, though, to hopefully not cause any confusion when installing the module and ensure the latest version is being installed.

I also want to note, our solution is rather large (2-3MB) and takes close to 10 minutes to export at times. Not sure if that could be related.

**Comment by seanmcne** [comment]
Can you send me part of the log where it shows the exception in azure dev ops? I'm curious how it's throwing the timeout exception - or is the actual pipeline timing out when running and just never exporting the solution?

Thanks!

**Comment by ryanlraines** [comment]
> I also want to note, our solution is rather large (2-3MB) and takes close to 10 minutes to export at times. Not sure if that could be related.

We have a similarly sized solution, and a 10min export time from the GUI is a common experience.  We've just become conditioned to it.

**Comment by mwebster5589** [comment]
The actual pipeline is timing out while the Export-CrmSolution command is still running. 
Reviewing the Solution History in the environment, the solution export completed successfully at 12:03PM but the Export-CrmSolution command kept running till the pipeline timed out at 12:17PM.

**Comment by seanmcne** [comment]
This is quite odd, can you ensure you add the -verbose parameter to see if it proceeds past this line? 
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/master/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L2928 

If a response is never coming back, then it's likely the crmserviceclient that's not getting a response back at all (possibly)?

**Comment by mwebster5589** [comment]
I've added the -Verbose parameter. I'll keep you posted with what I see. Thank you!

**Comment by seanmcne** [comment]
@mwebster5589 one other tip, when you use the -verbose parameter I've got a log file automatically enabled - this log file should be stored locally and named "Microsoft.Xrm.Tooling.Connector.Verbose.log" if you are able to grab that as well, that _might_ be helpful as well.
