### ISSUE TITLE
Bad Gateway when importing Solution

### ISSUE THREAD

**Issue by cedmor** [seanmcne/Microsoft.Xrm.Data.PowerShell#446]
Hello,

When using an import scripts as below :
`$connectionString = $connectionString + ";Timeout=00:30:00;"`
`Set-CrmConnectionTimeout -conn $connection -TimeoutInSeconds 3600`
`Import-CrmSolution -conn $connection -SolutionFilePath $solutionPath -OverwriteUnManagedCustomizations -ActivatePlugIns -PublishChanges -Verbose`

I get sometimes the following error :
> ImportSolution : RequestID=87a8f030-49ee-4275-bba5-fc6dda07e7c9 : Executing 
ImportSolutionRequest for ImportSolutionToCrm duration=00:20:02.3604761 ExceptionMessage = The remote server returned an unexpected response: (502) Bad Gateway.
The remote server returned an unexpected response: (502) Bad Gateway. => The remote server returned an error: (502) Bad Gateway.************ FaultException`1 - ImportSolution : 
Executing ImportSolutionRequest for ImportSolutionToCrm |=> A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b
A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b => A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b => Cannot insert 
duplicate key.[TerminalFailure] Failed to Execute Command - ImportSolution : RequestID=87a8f030-49ee-4275-bba5-fc6dda07e7c9 : Executing ImportSolutionRequest for ImportSolutionToCrm 
duration=00:00:05.3522593 ExceptionMessage = A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b
A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b => A duplicate import job id already exists : 1c757c85-04c0-4d03-9854-4b5a56ba504b => Cannot insert 
duplicate key.

After getting this error message and wait few seconds, I can go in my Organisation and see that the solution version has increased so it seems imported but not published.
It seems that when the import process take less than 20 minutes, I do not have the issue. 

Is there a default timeout configuration that I did not catch and that could help me prevent this behavior ?
Thanks a lot for your help.

**Comment by seanmcne** [comment]
HI can you please try using the async import method, the async upload method allows you to upload and wait for the solution to complete as opposed to having to hold open a persistent network connection (which can be shutdown/closed and subject to networktimeouts). 

If it's a managed solution you shouldn't need to publish but unmanaged solutions do need to be published when completed.

**Comment by cedmor** [comment]
Hi Sean, thanks a lot for your answer, it seems to work with Async indeed ! :)
