### ISSUE TITLE
Import-CRMSolution Fails but same solution works through front end

### ISSUE THREAD

**Issue by AzureWeller** [seanmcne/Microsoft.Xrm.Data.PowerShell#447]
Hi,

So I have wrote a script which checks if the solution exists in another env 
If not it essentially just imports it
However when I export the solution and import it using the XRM SDK the script fails and I get:

PS H:\>        import-crmsolution -conn $targetconn -SolutionFilePath $SP.FullName -ActivatePlugIns $true -Verbose

    Importing solution file D:\Solutions\MYSOLUTION_managed_4_1_9.zip into: 
    http://SERVER:5555/ORG/XRMServices/2011/Organization.svc
    VERBOSE: OverwriteCustomizations: True
    VERBOSE: SkipDependancyCheck: False
    VERBOSE: ImportAsHoldingSolution: False
    VERBOSE: Maximum seconds to poll for successful completion: 900
    VERBOSE: Calling .ImportSolutionToCrm() this process can take minutes...
    VERBOSE: ImportId: 00000000-0000-0000-0000-000000000000
    import-crmsolution : System.Management.Automation.RuntimeException: Plugin Assemblies import: FAILURE. Error: Plugin: 
    Infrastructure.Plugins.MYPLUGIN, Version=1.0.0.0, Culture=neutral, 
    PublicKeyToken=f3d55c4038318ed1 caused an exception. => Plugin Assemblies import: FAILURE. Error: Plugin: 
    Infrastructure.Plugins.MYPLUGIN, Version=1.0.0.0, Culture=neutral, 
    PublicKeyToken=f3d55c4038318ed1 caused an exception. => Action failed for assembly 'Infrastructure.Plugins.MYPLUGIN, 
    Version=1.0.0.0, Culture=neutral, PublicKeyToken=f3d55c4038318ed1': Assembly must 
    be registered in isolation.

However if I take the exact same solution (the one exported using the script) and manually import it into my target organization, the import is successful?

Any help would be appreciated
Thanks

**Comment by seanmcne** [comment]
Use an async import, otherwise your script has to sit connected and waiting until it completes which can be problematic. 

As for the import, are you wanting to import the plugin as full trust (not sandbox)?  Let me know if the async import helps or not, I would expect the same result and same exception/error uniformly across the api imports as well as the UI import.  What version of the product are you using (I assume this is onprem)?
