### ISSUE TITLE
Add-CrmSecurityRoleToUser Missing Parameter

### ISSUE THREAD

**Issue by mjfara** [seanmcne/Microsoft.Xrm.Data.PowerShell#449]
The SecurityRoleName parameter seems to be missing from the Add-CrmSecurityRoleToUser method
This following should be added after **Line 4334** in **Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1**
```
        [parameter(Mandatory=$false, Position=2)]
        [string]$SecurityRoleName
```

**Comment by seanmcne** [comment]
@mjfara great catch - this appears to have been a typo/bug introduced with some other cleanup.  Thanks!

**Comment by mjfara** [comment]
If anyone needs a workaround in the mean time, you can just assign a global variable with the same name before the call:
```
    $global:SecurityRoleName = "System Administrator"
    Add-CrmSecurityRoleToUser -conn $conn -UserId $appUser -SecurityRoleId $roleid
```

**Comment by seanmcne** [comment]
#451
