### ISSUE TITLE
Cmdlet "Add-CrmSecurityRoleToUser" &  var. "SecurityRoleName"

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#450]
Code in cmdlet `Add-CrmSecurityRoleToUser` is using variable `SecurityRoleName` but this variable is not correctly handled in the logic.

Calling `Add-CrmSecurityRoleToUser` with the following parameters does not associate the role

````
Add-CrmSecurityRoleToUser -UserId $targetUser.systemuserid -SecurityRoleId $_.roleid
````

The code checks if the value is not an empty string - which is true, becaue the value is NULL.

````
if($SecurityRoleName -ne "")
    {
        if($UserRecord -eq $null -or $UserRecord.businessunitid -eq $null)
        {
            $UserRecord = Get-CrmRecord -conn $conn -EntityLogicalName systemuser -Id $UserId -Fields businessunitid
        }

````

**Comment by seanmcne** [comment]
Nice catch @thuld! Do you want to submit a PR for this issue?

**Comment by mjfara** [comment]
If anyone needs a workaround in the mean time, you can just assign a global variable with the same name before the call:
```
    $global:SecurityRoleName = "System Administrator"
    Add-CrmSecurityRoleToUser -conn $conn -UserId $appUser -SecurityRoleId $roleid
```

**Comment by seanmcne** [comment]
#451
