### ISSUE TITLE
Calendar Rules

### ISSUE THREAD

**Issue by lohith903** [seanmcne/Microsoft.Xrm.Data.PowerShell#453]
Hi,

Does this module supports updating calendarrules in customer service calendars. I tried retrieving and updating calendarrules using calendar ID but was unsucessfull doing so and got below errors.

 ExceptionMessage = The 'Update' method does not support entities of type 'calendarrule'.
 ExceptionMessage = The 'Retrieve' method does not support entit  
 ies of type 'calendarrule'.

Any suggestions would help and thanks in advance.

**Comment by seanmcne** [comment]
Any supported XRM/dataverse api call supported by xrmtooling can be executed via the module (as it contains the xrm tooling module).  

One example using C# (which could be adapted to powershell) is documented here: https://thusithasblog.blogspot.com/2017/02/creating-calendar-rules-with-breaks-in.html 

A second, more recent, article outlines more aspects of working with calendars and calendarrules: https://mscrm16tech.com/2019/04/13/calendar-and-calendar-rules-in-ms-crm/ 

I hope this helps!
