### ISSUE TITLE
Set-CRMQueueMailBox errors with a valid email address

### ISSUE THREAD

**Issue by OmnipotentOwl** [seanmcne/Microsoft.Xrm.Data.PowerShell#456]
When the following commands execute I am getting a validation error on the email address. The passed-in email address is a valid email address and reviewing the previous bug reports this looks to be the same case as #246 with the same resolution most likely as they appear to have used the same validation code.

```
$MailboxEmailAddress = "example@tenantname.onmicrosoft.com"
Set-CrmQueueMailbox -QueueId $QueueId -EmailAddress $MailboxEmailAddress -ApplyDefaultEmailSettings -ScheduleTest -ApproveEmail
```

##[error]Cannot validate argument on parameter 'EmailAddress'. The argument "example@tenantname.onmicrosoft.com" does not match the "/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/" pattern. Supply an argument that matches "/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/" and try the command again.
##[error]PowerShell exited with code '1'.

**Comment by seanmcne** [comment]
Thanks for the contribution!
