### ISSUE TITLE
Add-CrmSecurityRoleToUser parameter SecurityRoleName reports as not found with the latest module version

### ISSUE THREAD

**Issue by OmnipotentOwl** [seanmcne/Microsoft.Xrm.Data.PowerShell#457]
I have a script that leverages the Add-CrmSecurityRoleToUser function to add an application user to a security role. When version 2.8.12 came out this broke due to the removal of the SecurityRoleName parameter. While this parameter was returned in version 2.8.13 it looks like it still does not get recognized. The only thing looking between the 2.8.11 and 2.8.13 implementations that I can see that are different is that the position changed to be 3 instead of 2 which looks like it might be causing PowerShell to not detect the parameter properly.

`Add-CrmSecurityRoleToUser -UserId $user.ReturnProperty_Id -SecurityRoleName $AppUserRoleName`

v2.8.13
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/532a0138b44c454579fdc55eb1a559dfd4db33b3/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L4335-L4336
v2.8.11
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/blob/0d571982a21cfd3872088394757d52cc5ded8623/Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1#L4362-L4363

**Comment by seanmcne** [comment]
thanks for reporting, apologies for this, will get an update to the codebase here today.
