### ISSUE TITLE
Get-CrmOrganizations  WARNING: Failed to connect to CRM: No Orgs Found, Searched Online. Region Setting = GCCHIGH

### ISSUE THREAD

**Issue by ryanlraines** [seanmcne/Microsoft.Xrm.Data.PowerShell#465]
Wanting to return the list of orgs in our tenant using the Get-CrmOrganizations cmdlet. 

The following error is returned:  

`WARNING: Failed to connect to CRM: No Orgs Found, Searched Online. Region Setting = GCCHIGH`

Maybe I have the wrong Region Setting value?

**Comment by seanmcne** [comment]
Hi Ryan, Get-CrmOrganizations cmdlet is provided directly from the SDK and can be logged with support.  If you're looking to just connect to an environment (regardless of the cloud) you can use the following command: 

```
#This connects to a GCC environment (not GCC High) but you can alter your orgurl to connect to a gcc high url or any other environment. 
#adding the verbose param will log the connection string format and additional details which should be helpful 
connect-crmonline -Username "user@domain.com" -ServerUrl <orgurl>.crm9.dynamics.com -verbose
```

Once you connect there is a $conn object available that all the cmdlets will use this automatically (or you can assign it to a variable and use it yourself).  An example is: once you connect above you can then run the following command to execute a whoami: 

```
Invoke-CrmWhoAmI
```

**Comment by ryanlraines** [comment]
Thanks @seanmcne  for the reply. 

I was looking for an output of **_ALL_** the orgs in my GCCH tenant.  I've seen it work in Commercial tenants, but using the same commands in GCCH tenants fails. 

I was looking to get clarification on what the valid "DeploymentRegion" would be for GCCH orgs. https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.tooling.crmconnector.powershell/get-crmorganizations?view=pa-ps-latest#parameters

**Comment by seanmcne** [comment]
Makes sense, can you try using "USG" as the deployment region?

**Comment by ryanlraines** [comment]
@seanmcne that worked.  Thanks!
