### ISSUE TITLE
Import of Solution with Import-CrmSolutionAsync does not remove Option Set Values

### ISSUE THREAD

**Issue by Nafferty** [seanmcne/Microsoft.Xrm.Data.PowerShell#466]
Hey @seanmcne. Hope all is well!

We've noticed an issue where we use Import-CrmSolutionAsync with a (managed) solution against an environment and it's not removing (global) option set values. If we manually import the solution, the option set values get removed. The version of the existing solution in the environment is 1.0.2 and the version we are importing is going up to 1.0.7, so the version is higher and it should be staging it as an upgrade.

`Import-CrmSolutionAsync -conn $conn -SolutionFilePath $solutionFilePath -MaxWaitTimeInSeconds 3600 -OverwriteUnManagedCustomizations -ActivateWorkflows -PublishChanges -BlockUntilImportComplete -Verbose`

Do you know if this is an issue with the PowerShell here, or if this is an issue with the underlying CrmSdk that needs to be addressed?

Steps to recreate:

1. Create 2 environments
2. In environment A, create an unmanaged solution with a global Option Set (Choice) with multiple choices
3. Export the solution and import it into environment B as managed
4. Remove some of the choices from the unmanaged solution in environment A, update the version of the solution, and run Import-CrmSolutionAsync to import this new version of the solution into environment B.
5. Notice that the choice values were not moved as expected in environment B.

**Comment by ryanlraines** [comment]
I'm wondering if ImportingAsHoldingSolution changes anything? _(just add `-ImportAsHoldingSolution` swtich to your import command)_

Then you'll need to call Microsoft.Crm.Sdk.Messages.DeleteAndPromoteRequest after the import job completes to activate the new version. 

Worth a shot.

**Comment by Nafferty** [comment]
@ryanlraines Learn something new every day!! That worked great. Would be nice if there was some switch on the PShell function, but that's okay.

I'll close this. If anyone happens to ever come across this and is unsure on exactly how to use it, here's what the script should look like:
```powershell
Import-CrmSolutionAsync -conn $conn -SolutionFilePath $solutionFilePath -MaxWaitTimeInSeconds 3600 -OverwriteUnManagedCustomizations -ActivateWorkflows -PublishChanges -BlockUntilImportComplete -ImportAsHoldingSolution -Verbose

$deleteAndPromoteSolutionRequest = [Microsoft.Crm.Sdk.Messages.DeleteAndPromoteRequest]::new()
$deleteAndPromoteSolutionRequest.UniqueName = "solutionuniquename"
$conn.execute($deleteAndPromoteSolutionRequest)
```
