### ISSUE TITLE
Set-CRMRecordAssociation does not have a parameter for PrimaryEntityRole

### ISSUE THREAD

**Issue by aaronhamilton** [seanmcne/Microsoft.Xrm.Data.PowerShell#468]
I am trying to associate two records in SharePointDocumentLocations as parent-child using the following cmdlet... 

`Add-CrmRecordAssociation -EntityLogicalName1 sharepointdocumentlocation -Id1 $documentLocationID -EntityLogicalName2 sharepointdocumentlocation -Id2 $parentLocationID -RelationshipName sharepointdocumentlocation_parent_sharepointdocumentlocation 
`

but I am getting the following error...

_System.Management.Automation.RuntimeException: ************ FaultException`1 - Associate : Execute (Associate) request to CRM from IOrganizationService |=> Entity role must be specified for reflexive relationship 'sharepointd
ocumentlocation_parent_sharepointdocumentlocation.'_

I see C# code samples online which use a PrimaryEntityRole, but I'm not sure how to implement this using PowerShell.

Any guidance on this?

Thanks
Aaron

**Comment by seanmcne** [comment]
Let me see if I can look into this today - it should mimic c# unless it's using a specialized function provided by CRMserviceclient. Thanks!

**Comment by seanmcne** [comment]
Can you try this script? 
The current script/cmdlet assumes a more typical relationship type that can be assumed, it looks like the sharepoint doc relationships are a little different and may require this - can you give this script a try? 

```
$EntityLogicalName1 = ""
$$Id1 = "Guid1"
$EntityLogicalName2 = ""
$$Id2 = "Guid2"


$AssociateRequest = [Microsoft.Xrm.Sdk.Messages.AssociateRequest]::new();
$AssociateRequest.Target = [Microsoft.Xrm.Sdk.EntityReference]::new($EntityLogicalName1,$Id1);
$AssociateRequest.Relationship = $RelationshipName;
#see possible EntityRole enum values here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entityrole?view=dynamics-general-ce-9
$AssociateRequest.Relationship.PrimaryEntityRole = [Microsoft.Xrm.Sdk.EntityRole]::Referenced

$RelatedEntityReference = [System.Collections.Generic.List[Microsoft.Xrm.Sdk.EntityReference]]::new()
$RelatedEntityReference.Add(([Microsoft.Xrm.Sdk.EntityReference]::new($EntityLogicalName2,$Id2)))
$RelatedEntityCollection = [Microsoft.Xrm.Sdk.EntityReferenceCollection]::new($RelatedEntityReference)
$AssociateRequest.RelatedEntities = $RelatedEntityCollection

$result = $conn.Execute($AssociateRequest)
```

**Comment by aaronhamilton** [comment]
Thanks Sean!

I figured there was a way involving core .NET classes, but I didn't know
where to start.

I'll test it out and let you know.

Aaron
