### ISSUE TITLE
I can't find any commandlet to update entity metadata like deleting a field from any custom entity.

### ISSUE THREAD

**Issue by KamalKishan** [seanmcne/Microsoft.Xrm.Data.PowerShell#469]
We have Get-CrmEntityAttributeMetadata to get metadata but, For changing metadata I didn't find any command.

**Comment by seanmcne** [comment]
Hi Kamal add/change/delete attributes are handled well by managed solutions which tends to be the more typical use case. I have some samples of manipulating metadata here though which could be adapted to deletion or creation - https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/tree/master/Metadata

If you create something you want to share I'd be happy to add it to then samples (you can also submit a PR there as well). Thanks!

**Comment by seanmcne** [comment]
@KamalKishan, I just checked a oneNote notebook I have from various tests and found a sample which creates a new custom entity called new_repro, and then creates 330 custom attributes on that entity (it was a test to find if an obscene number of attributes would break certain platform components).  This could also be adapted to add different attributes types as well as adapted to support a DeleteAttributeRequest Message: https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.messages.deleteattributerequest?view=dynamics-general-ce-9

PowerShell based on .NET/.NET objects and will enable us pretty much do anything .NET can do, but using powershell script language/syntax (the syntax can get a little funky but it works): 

```
#Hypothetical code for attribute deletion - this assumes you've already called connect-crmonline
$entityName = "new_something"
$attributeName = "new_somethingattribute"
$deleteAttribute = new-object Microsoft.Xrm.Sdk.Messages.DeleteAttributeRequest
$deleteAttribute.EntityLogicalName="$($entityName)"
$deleteAttribute.LogicalName=$attributeName
$conn.ExecuteCrmOrganizationRequest($deleteAttribute)
```

 
```
$publisherPrefix= "new_"
$entityName="entityWithALotOfAttributes"
$fieldsToCreate= 330 

#OPTIONAL 
$primaryAttribute = new-object Microsoft.Xrm.Sdk.Metadata.StringAttributeMetadata
$primaryAttribute.SchemaName = "$($publisherPrefix)_primaryfield"
$primaryAttribute.MaxLength=1
$primaryAttribute.DisplayName = new-object Microsoft.Xrm.Sdk.Label -ArgumentList @("Primary Entity",1033)

$entity = new-object Microsoft.xrm.sdk.metadata.EntityMetadata
$entity.SchemaName = "$($publisherPrefix)$($entityName)"
$entity.DisplayName = new-object Microsoft.Xrm.Sdk.Label -ArgumentList @("Repro",1033)
$entity.DisplayCollectionName = new-object Microsoft.Xrm.Sdk.Label -ArgumentList @("Repros",1033)
$entity.ChangeTrackingEnabled = $true

$createEntityRequest = new-object Microsoft.Xrm.Sdk.Messages.CreateEntityRequest 
$createEntityRequest.Entity = $entity
$createEntityRequest.PrimaryAttribute = $primaryAttribute

#create a ton of string attributes on the new entity just created
For ($i=0; $i -lt $fieldsToCreate; $i++)  {
	$displayLabel = new-object Microsoft.Xrm.Sdk.Label -ArgumentList @("$($i)",1033)
	$stringAttrMeta = new-object Microsoft.Xrm.Sdk.Metadata.StringAttributeMetadata
	$stringAttrMeta.SchemaName="$($publisherPrefix)s$($i)"
	$stringAttrMeta.MaxLength = 100
	$stringAttrMeta.DisplayName = $displayLabel
	$createAttribute = new-object Microsoft.Xrm.Sdk.Messages.CreateAttributeRequest
	$createAttribute.EntityName="$($publisherPrefix)$($entityName)"
	$createAttribute.Attribute=$stringAttrMeta
	$conn.ExecuteCrmOrganizationRequest($createAttribute)
}

Publish-CrmEntity "$($publisherPrefix)$($entityName)"
```
