### ISSUE TITLE
Import-CrmSolution gets importId: 00000000-0000-0000-0000-000000000000 and waits forever

### ISSUE THREAD

**Issue by taarskog** [seanmcne/Microsoft.Xrm.Data.PowerShell#47]
Using ver 2.1 on CRM Online 2016 I'm unable to import my CRM solution (export works great). This is the command I'm running:

```
C:> Import-CrmSolution -SolutionFilePath Demo.zip -ActivatePlugIns -conn $xrmConn -PublishChanges
Importing solution file Demo.zip into: https://<removed>.api.crm4.dynamics.com/XRMServices/2011/Organization.svc
Import of file completed, waiting on completion of importId: 00000000-0000-0000-0000-000000000000
005 seconds of max: 900 ... ImportJob%: 0
..
..
902 seconds of max: 900 ... ImportJob%: 0
Import-CrmSolution : System.Management.Automation.RuntimeException: Import-CrmSolution halted due to exceeding the maximum timeout of 900.
At line:1 char:1
+ Import-CrmSolution -SolutionFilePath Demo.zip -ActivatePlug ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution
```

Nothing gets updated in CRM Online.

Finally thank you for an excellent tool.

**Comment by seanmcne** [comment]
does this repro on multiple instances?  I tried a similar import into my own test instance and can't repro getting an empty GUID.  I'm wondering if there's something in the solution itself that we may be tripping up on? 

![junk](https://cloud.githubusercontent.com/assets/2292260/12763289/329f9c86-c9b9-11e5-9b4e-9a49a7362f7b.png)

**Comment by RedsGT** [comment]
Hi  @taarskog.  I was able reproduce your issue by using an non-existent SolutionFilePath.  Try using a full path to your solution file, it should work.  I'm also going to submit a change that will check if the file path is valid prior to trying to run the import.

**Comment by seanmcne** [comment]
Leave a comment
