### ISSUE TITLE
Compatibility with Microsoft.PowerApps.Administration.PowerShell

### ISSUE THREAD

**Issue by agupta-au** [seanmcne/Microsoft.Xrm.Data.PowerShell#476]
Hi there, 

Any plans for supporting/using the Modern Auth mechanisms that are used in Microsoft.PowerApps.Administration.PowerShell?

For example, if I've already connected to CRM using `Add-PowerAppsAccount` I don't really want to reinitiate a connection using the old CRM Connector again.

This is especially true in scenarios where I'm resetting an environment, then adding application users for ALM/DevOps in the same script.

P.S. Thank you for the awesome work on this module. And keeping the `-ConnectionString` parameter in - it has been most helpful!

**Comment by seanmcne** [comment]
Hi Agupta thanks for taking the time to write in and I'm glad this module has helped you.  One point of clarification that might help: the powershell module for powerapps is focused at providing capabilities to configure and manage your environments (not the data within the environment).  Whereas this module is focused on connecting directly to the environment and allowing you to manage the data within the Dataverse database.  

Regarding re-use of the credential or token from the powerAppsAccount cmdlets: the credential used to acquire the token for the PowerAppsAccount is not stored and the Token retrieved is not valid for the Dataverse api endpoint(s) - the token used is only valid for the bap endpoints (which manage the powerapps environments via the admin api's and do not access/interact with the data in the dataverse DB).  

Regarding the use of connectionString, I'm curious to know the benefits of using the ConnectionString parameter - do you use that primarily for debugging & testing connection strings?  I'm curious if there's a scenario where the connectionstring parameter has to be used and the connect-crmonline function doesn't support or handle? 

Thanks again!
