### ISSUE TITLE
Add-CrmSecurityRoleToTeams

### ISSUE THREAD

**Issue by awshaik** [seanmcne/Microsoft.Xrm.Data.PowerShell#487]
Hi Is it possible to add some bulk CRM security roles to different teams by using powerShell.

If yes, please share inputs.

thanks

**Comment by seanmcne** [comment]
Yep, you can use Add-CrmSecurityRoleToTeam to add roles, you can also query user or team roles, etc.  

Here is one example which gets all of a users roles and removes them - you can use similar approaches to query roles and add them to another user. 

https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/28dd323b4ff55498a97640a55bfc96649ec1c7e1/UserOperations/Role_RemoveRoleFromAllUsers.ps1
