### ISSUE TITLE
Edit a security role possible?

### ISSUE THREAD

**Issue by Henry-Sir** [seanmcne/Microsoft.Xrm.Data.PowerShell#502]
Hi there,

Is it possible to edit a security role?
We want to give the "Basic User" role the read permissions on Process (entity "workflow"). Unfortunately I have not found a way to change this via Powershell or by editing a CRM record.

Alternatively, a team can also be granted access to the entity.
I have only found the Grant-CrmRecordAccess cmdlet which only grants access to one record and not to the whole entity.

![image](https://user-images.githubusercontent.com/75314095/166816095-8cadeb5a-6727-4cc6-a0e7-50e80205310d.png)

**Comment by seanmcne** [comment]
Security roles (role record) links to a set of "Role Privileges" for that role, role privileges is essentially an N:N table which links the 'role' to which 'privileges' it should have as well as what level of the given privilege (ie: scope or depth) - you can technically edit or construct a role using the api's and the entities you'd interact with are: 
- role
- roleprivilege
- privilege 

If it helps, the way I typically would approach something like this is: 
- Create a role with the privilege and depth you want to change (in the ui) 
- Look at that role via the api (which can be done using this module)
- Then toggle the privilege level in the UI 
- re-inspect the underlying configuration data using powershell 
- then model your changes so you can apply them to any other given roles

One note or 'heads up' is that roles cascade down to lower business units - you need to edit roles at the 'root' level - or just look at roles which do not have a parent role. When you edit that role then all other business units will inherit this change as well. 

Hope that helps!

**Comment by seanmcne** [comment]
This request is also possible via the request/response (organization request/response pattern) using the AddPrivilegesRoleRequest and AddPrivilegesRoleResponse. 

It would look something like this: 
```
$rolePriv1 = New-Object Microsoft.Crm.Sdk.Messages.RolePrivilege
$rolePriv1.Depth = 3
$rolePriv1.PrivilegeId =$crmPrivilegeId
$rolePriv1.BusinessUnitId =$crmBusinessUnitId

$AddPrivRoleReq = new-object Microsoft.Crm.Sdk.Messages.AddPrivilegesRoleRequest
$AddPrivRoleReq.RoleId = $CrmRoleIdToSetNewPrivilege
$AddPrivRoleReq.Privileges = @($rolePriv1)

$response=$conn.ExecuteCrmOrganizationRequest($AddPrivRoleReq) 
```

**Comment by Henry-Sir** [comment]
Thank you very much.

**Comment by seanmcne** [comment]
I also added a sample for future reference - thanks for adding a new scenario! 
https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples/blob/master/UserOperations/Role_AddPrivilegeToRole
