### ISSUE TITLE
[FR] Connect-CrmOnline with Certificate

### ISSUE THREAD

**Issue by Henry-Sir** [seanmcne/Microsoft.Xrm.Data.PowerShell#503]
Could you implement in the "Connect-CrmOnline" Cmdlet the possibility to connect to CRM via ClientId and certificate?

**Comment by seanmcne** [comment]
Yes, this has been on my list to try out for a while but I haven't had the chance to - as a test I think you could try the code below. My understanding is the connection code would open the store name and look specifically for the certificate with the given thumbprint. If you give it a try please let me know if it works as-is or if it takes some additional work. 

```
$clientid = "ClientId"
$AppCertThumprint = "Thumbprint"
$CertStoreName = "Certificate store name"

$ConnectionString="ServiceUri=https://someenvironment.crm.dynamics.com/XRMservices/2011/Organization.svc;AuthType=Certificate;SkipDiscovery=true;ClientId=$clientId;thumbprint=$AppCertThumbprint;CertificateStoreName=$CertStoreName"

Connect-CrmOnline -ConnectionString $ConnectionString -Verbose
```

**Comment by seanmcne** [comment]
@Henry-Sir  
If you have a moment, please let me know if that worked - thanks!
