### ISSUE TITLE
Issue with Get-CrmRecords in 2.8.17

### ISSUE THREAD

**Issue by dylanhaskins** [seanmcne/Microsoft.Xrm.Data.PowerShell#513]
Hey Team,

Sent a message via PowerShellGallery, but I am not sure that those work, so thought I would log the issue here too. With 2.8.17 Get-CrmRecords has stopped working when Filtering. It appears to parse the filters and send them to Get-CrmRecordsByFetch but results in an error. Below is an example using the "example call" provided in your Get-Help documentation, but seeing the same error with all filtered queries that we have been using ....

PS C:\Users\dhaskins> Get-CrmRecords -conn $Conn -EntityLogicalName account -FilterAttribute name -FilterOperator "eq" -FilterValue "Adventure Works (sample)" -Fields name,accountnumber -Verbose
VERBOSE: Using the supplied single filter of name 'eq' Adventure Works (sample)
Get-CrmRecordsByFetch : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'records' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At C:\Users\dhaskins\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\2.8.17\Microsoft.Xrm.Data.Powershell.psm1:3327 char:20
+ ...  $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch

At C:\Users\dhaskins\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\2.8.17\Microsoft.Xrm.Data.Powershell.psm1:1696 char:9
+         throw LastCrmConnectorException($conn)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:String) [], RuntimeException
    + FullyQualifiedErrorId :

**Comment by Skubakoob** [comment]
I hit the same error - I then tried to build out the fetch query and use Get-CrmRecordsByFetch directly, and same behaviour. It works fine if it successfully retrieves data, throws this error if there are no results

**Comment by seanmcne** [comment]
Let me see if I can reproduce this - thanks for the info, it looks like it's if works fine but errors if there are no results (which is definitely not intended).

**Comment by Skubakoob** [comment]
I should be able to give it a try tomorrow, will let you know!

**Comment by dylanhaskins** [comment]
Thanks Sean.

I can confirm that the 2.8.19-alpha release is working in our scenarios 😊

From: Sean McNellis ***@***.***>
Date: Friday, 11 November 2022 at 5:15 AM
To: seanmcne/Microsoft.Xrm.Data.PowerShell ***@***.***>
Cc: Dylan Haskins ***@***.***>, Author ***@***.***>
Subject: Re: [seanmcne/Microsoft.Xrm.Data.PowerShell] Issue with Get-CrmRecords in 2.8.17 (Issue #513)

I've published an alpha build/pre-release package - are either of you able to test out and validate if the fix works for you? I'm relatively certain this will resolve it as I was able to reproduce. I still don't have a good idea for why this is taking place now and not in prior builds. I'm almost positive it has something to do with the updated assembly - the code for both functions remained the same in both releases but I can't repro in .14 and I can reproduce it in the newer build.

**Comment by seanmcne** [comment]
Thanks for confirming!
