### ISSUE TITLE
Get-CrmRecordsByFetch errors Cannot bind argument to parameter 'records' because it is null. when fetchxml criteria gives no records

### ISSUE THREAD

**Issue by ameed** [seanmcne/Microsoft.Xrm.Data.PowerShell#534]
Hi , 

This has started happening recently. We use a powershell script in our CI/CD to reassign ownership of processes records to environment specific service account. If there is any record, owned by Azure DevOp service connection SPN, then it is reassigned to environment specific service account

This has been working without any issues, but today it broke, to which i found out that the fetcxml is correct but does not have any records in result, and it failed with following error. 

Get-CrmRecordsByFetch : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'records' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At C:\Work\PowerShell\Change Processes Ownership To SVC Account.ps1:39 char:23
+ ... omponents = Get-CrmRecordsByFetch -conn $connection -Fetch $fetchXml  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch
 
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\2.8.20\Microsoft.Xrm.Data.Powershell.psm1:1696 char:9
+         throw LastCrmConnectorException($conn)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:String) [], RuntimeException
    + FullyQualifiedErrorId :

Command used
Get-CrmRecordsByFetch -conn $connection -Fetch $fetchXml -Verbose

FetchXml used
<fetch>
  <entity name="workflow">
    <attribute name="workflowid" />
    <filter>
      <condition attribute="ownerid" operator="eq" value="4667ffeb-f945-ef11-a316-6045bd5f1269" uitype="systemuser" />
    </filter>
    <link-entity name="solutioncomponent" from="objectid" to="workflowid" alias="scw">
      <filter>
        <condition attribute="componenttype" operator="eq" value="29" />
      </filter>
      <link-entity name="solution" from="solutionid" to="solutionid" alias="sol">
        <filter>
          <condition attribute="uniquename" operator="eq" value="ImportedSolutionName" />
        </filter>
      </link-entity>
    </link-entity>
  </entity>
</fetch>

**Comment by CoreySutton** [comment]
Experiencing the same error when using command `Get-CrmRecords`.

```powershell
Get-CrmRecordsByFetch : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to 
parameter 'records' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At C:\Program 
Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.20\Microsoft.Xrm.Data.Powershell.psm1:3327 char:20
+ ...  $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch
```

Using a try/catch to bypass this error.

**Comment by ameed** [comment]
@CoreySutton i did the same here to handle with try/catch

**Comment by radevic** [comment]
Same issue here, any alternative solutions so far?

**Comment by radevic** [comment]
Ok, didn't realize it is working when number of records is higher than 0. Thanks @ameed !

**Comment by furkankaracan** [comment]
+1 to this

**Comment by AgentDess** [comment]
This has caused so much headache this morning!  
We had a number of in-flight pipelines which had to be re-run.

the try catch worked  :)

**Comment by seanmcne** [comment]
> Hi ,
> 
> This has started happening recently. We use a powershell script in our CI/CD to reassign ownership of processes records to environment specific service account. If there is any record, owned by Azure DevOp service connection SPN, then it is reassigned to environment specific service account
> 
> This has been working without any issues, but today it broke, to which i found out that the fetcxml is correct but does not have any records in result, and it failed with following error.
> 
> Get-CrmRecordsByFetch : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'records' because it is null. at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) At C:\Work\PowerShell\Change Processes Ownership To SVC Account.ps1:39 char:23
> 
> * ... omponents = Get-CrmRecordsByFetch -conn $connection -Fetch $fetchXml  ...
> * ```
>               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>   * FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch
> 
> At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.PowerShell\2.8.20\Microsoft.Xrm.Data.Powershell.psm1:1696 char:9
> 
> * ```
>       throw LastCrmConnectorException($conn)
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : OperationStopped: (:String) [], RuntimeException
>   * FullyQualifiedErrorId :
> 
> Command used Get-CrmRecordsByFetch -conn $connection -Fetch $fetchXml -Verbose
> 
> FetchXml used

Did this just start as of yesterday or has it been happening for a while?  I'm looking at the changes and only two things really changed: 
- #526 
- Updated assemblies from 3.3.0.964 to 3.3.0.1007 - notably the release notes for all these releases are identical, I'm assuming very little has changed.

**Comment by seanmcne** [comment]
Ok, I figured out the issue though I'm not entirely sure how it happened - a former version of the code for getCrmRecordsByFetch was published (everything else was the same, just that one part).  It's been re-merged properly and should properly reflect the change now. To the best of my knowledge, I think this didn't get caught in my testing was due to the updated code for the module not loading entirely (when testing). I'll need to be mindful about closing out all of my PowerShell instances, when testing, to ensure nothing is holding an open file handle.  Please let me know ASAP if you see anything else off but this should bring things back to what you would expect, now.

Thanks!

#536

**Comment by ameed** [comment]
Thanks @seanmcne i just tested my script, it is fixed now for Get-CrmRecordsByFetch
i believe it is also fixed for other cmdlet Get-CrmRecords as @CoreySutton  reported

**Comment by seanmcne** [comment]
Thanks for confirming @ameed!
