### ISSUE TITLE
CRM 2013 OnPrem Export error

### ISSUE THREAD

**Issue by Tri413** [seanmcne/Microsoft.Xrm.Data.PowerShell#54]
I'm getting an error when I try to export from a 2013 OnPrem. The error says that "ExportSales" is not supported. It works fine when I manually skip this line in the Microsoft.Xrm.Data.PowerShell.psm1 file.

$exportRequest.ExportSales =$ExportSales

The version of CRM said 6.1.x in the debugger, so perhaps a quick check of the version before setting this property would solve the problem?

**Comment by seanmcne** [comment]
Closed with fix #55
