### ISSUE TITLE
Add same function that PSSnapin Microsoft.crm.powershell

### ISSUE THREAD

**Issue by andrescolodrero** [seanmcne/Microsoft.Xrm.Data.PowerShell#61]
Hi,
great tool.

However i miss all the functions to work remotely with Servers

https://msdn.microsoft.com/en-us/library/9c12aabb-e8da-4607-81fe-9131f75c4357(v=crm.7)#CRM

As far as i know, functions like Get-CrmOperationStatus can be only done connection straight to the server.

**Comment by seanmcne** [comment]
@andrescolodrero, these are 100% onprem only - I would love to see our ops/dev team add a rest endpoint to execute the org management functions (that are done via the instance picker today) but there is no such thing today.  The goal of this project today is to really zero in on the 'in org' or 'instance' level core operations that are frequently used/required for both onprem and online.  

I would suggest logging in to https://connect.microsoft.com and going to dynamics feedback (https://connect.microsoft.com/dynamicssuggestions).  I have created a feedback item out there asking specifically for an Office Graph or similar API to manage our CRM Online instances. Feel free to vote up the suggestion and add some discussion there: https://connect.microsoft.com/dynamicssuggestions/feedback/details/2373154 

One additional note, bear in mind that functions like 'get-crmoperationstatus' only returns asynchronous **deployment** operations - so this only returns status of pending 'new organization' or 'update organization' tasks (which would be like creating new orgs or editing orgs in the crm online instance picker).  Getting status of the async jobs pending (for instance) can be done with this project by querying the system jobs. 

Hope this helps!

**Comment by andrescolodrero** [comment]
I @seanmcne

Thanks for your answer.

Im running CRM on-premises and i would like to full manage CRM from my
desktop,not sign.in into some of the crm servers.

While i can use get-crmconnection from my desktop,i cant use all cmdlets
that are alreay in the server.

Regards

**Comment by seanmcne** [comment]
Oh if you're onprem, just import the dll that contains the deployment functions and you can use those as they are today to manage your onprem environment in combination with this project.
