### ISSUE TITLE
False positive on get-CrmRecord

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#62]
#use a valid OpptyId but enter a field name that doesn't exist
$oppty = Get-CrmRecord -EntityLogicalName opportunity -Id 7DDFDB03-2AD7-E511-80F8-3863BB35BF30  -fields some_invalidFieldName 

Expected: you'd get an exception stating the column is not found or a re-thrown exception 

Actual: it appears we are swallowing the exception and providing an invalid "text" response (with no exception).  There is not exception whatsoever, and the $oppty object is a string with the result "Record Id: 7ddfdb03-2ad7-e511-80f8-3863bb35bf30Does Not Exist"

**Comment by kenakamu** [comment]
fixed
