### ISSUE TITLE
Retrieve relationship meta-data

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#64]
I tried to run this code, but the properties "OneToManyRelationships", "ManyToManyRelationships" and "ManyToOneRelationships" contain no data:

`# $conn = Get-CrmConnection -InteractiveMode
$metedata = Get-CrmEntityAllMetadata -conn $conn
$entity = $metedata | ? { $_.logicalname -eq 'account' }

$entity.OneToManyRelationships.count
$entity.ManyToManyRelationships.count
$entity.ManyToOneRelationships.count`

Do I needed to use a different cmdlet?

**Comment by kenakamu** [comment]
Hi, try the following command.
```powershell
$metedata = Get-CrmEntityAllMetadata -conn $conn -EntityFilters All
$entity = $metedata | ? { $_.logicalname -eq 'account' }

$entity.OneToManyRelationships.count
$entity.ManyToManyRelationships.count
$entity.ManyToOneRelationships.count`
```
Please use Get-Help command to see more details for each command :) This takes time and I recommend to run this non-peak time.

```powershell
Get-Help Get-CrmEntityAllMetadata
```

**Comment by thuld** [comment]
Oh dammit, my fault. 
Thanks for the help.

**Comment by kenakamu** [comment]
Great☺
