### ISSUE TITLE
Set-CrmConnectionCallerId & User Queries

### ISSUE THREAD

**Issue by thuld** [seanmcne/Microsoft.Xrm.Data.PowerShell#65]
I try to utilize the "Set-CrmConnectionCallerId" cmdlet to load a list of all user-query of the disabled user. But the following code will only return the user-queries of my own system-user:

````
$conn = Get-CrmConnection -InteractiveMode

Set-CrmConnectionCallerId -conn $conn -CallerId 'bd728a45-3e40-e111-89b1-002655878919' 

$userViewes = Get-CrmRecords `
        -EntityLogicalName 'userquery' `
        -FilterAttribute 'querytype' `
        -FilterOperator 'eq' `
        -FilterValue 0 `
        -Fields 'name', 'userqueryid', 'ownerid' `
        -conn $conn

$userViewes.CrmRecords | ft
````

Is something wrong with my code?

**Comment by kenakamu** [comment]
It works as expected in my side. Please try the latest module just in case. And please double check if caller id is not your id but the user's id.

**Comment by thuld** [comment]
Hello kenakamu, 
I am using the version 2.2. Is it possible that this is not working for disabled users?

**Comment by kenakamu** [comment]
actually, you are right. I tried with disabled user and I repro the issue. As its user scope read for all userquery, I cannot think of getting it if user is disabled?

**Comment by kenakamu** [comment]
I believe this is expected behavior and couldn't find any workaround for now. I will close this but if you have any good idea, please let us know!
