### ISSUE TITLE
Version 2.2 and PowerShell Gallery

### ISSUE THREAD

**Issue by davidmcd** [seanmcne/Microsoft.Xrm.Data.PowerShell#66]
I'm really happy to see that you've added Upsert.  It doesn't appear that you have put version 2.2 in PowerShell Gallery yet.  When you get time, can you guys update PowerShell Gallery with the latest?

**Comment by kenakamu** [comment]
Thanks David. @seanmcne will update the module to gallery when he has time, but meanwhile please download from here. If you find any issue, please let us know :)

**Comment by seanmcne** [comment]
Hey @davidmcd 
I ran into a bit of a snag, it appears upsert is not an approved verb and we're getting warnings on import.  My suggestion, at this point, is to hold off on publishing into the gallery until we iron out the wrinkle by using an approved verb or by updating our set-crmrecord to include an -upsert switch/flag instead.

**Comment by davidmcd** [comment]
Yeah, I noticed the verb issue when I manually imported I was going to let you know about it.  I like the idea of using the switch flag.    
Date: Sun, 28 Feb 2016 11:56:26 -0800

**Comment by kenakamu** [comment]
I have removed upsert-crmrecord and added -Upsert switch to Set-CrmRecord. Sorry for this change.
