### ISSUE TITLE
UPSERT is not an approved verb 

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#67]
I think we should consider using MERGE instead of upsert as upsert is not an approved verb in powershell.  We could also consider adding switch property for "-Upsert" to set-crmRecord.

**Comment by Cherokee800** [comment]
I find the switch option is more intuitive than a separate command.

**Comment by kenakamu** [comment]
Make sense. I will change Upsert- to Merge-

However, as how implemented the function inside is quite different, I don't think its good idea to implement it inside current set- new-crmrecord.

Upsert uses pure SDK message, and Update uses XrmTooling one for now.
I will change the verb only for now to see how we should make change for update one later.

**Comment by seanmcne** [comment]
Ken, can we instead just add a switch param to set-crmrecord (see my other bug regarding the renaming / aliasing of that function)? Should we discuss more tomorrow/later this week?

**Comment by kenakamu** [comment]
sure. For now, I updated Upsert- to Merge-. Let's discuss about Set- and New-CrmRecord and Merge handling. I close this issue for now and will discuss on newly opened issue
