### ISSUE TITLE
Seperate set-CrmUserBusinessUnit into two commands 

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#71]
Should add a new function to re-assign all records and drop this from the set-CrmUserBusinessUnit.  This command should simply take in the UserGuid and BusinessUnitGuid and not assume the re-assign of all records.

**Comment by kenakamu** [comment]
As SDK works in that why, how about make ReassignUiserId as optional and if you omit it, just reuse the UserId so all the records remain owned by the same user?

**Comment by kenakamu** [comment]
fixed by making ReassignUserId as optional. When omitting use UserId
