### ISSUE TITLE
Remove psm1 bloat by converting to xml based help

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#81]
Start converting help to XML based help to reduce the size of the PSM1 for easier editing and comparisons. 

Have taken branch to start the work. 
For editing I'm using: https://pscmdlethelpeditor.codeplex.com/ 

The project file for creating help is included with the project as part of this branch.

**Comment by kenakamu** [comment]
nice. if this work, let do it with version 2.3

**Comment by kenakamu** [comment]
I see several comments and examples are missing..
I try to find a better way to check which ones are missing and how to add them back.

**Comment by seanmcne** [comment]
Here is a way to list the number of examples in each functions help: 

Get-Command -Module Microsoft.xrm.data.powershell|foreach{
(get-help $_.name).examples.example.count
}

**Comment by seanmcne** [comment]
Based on this, I see the following produce zero examples (which probably indicates there's missing help info).  I'm seeing help working for every function given these results - which ones are missing?  All the help comments and examples were copied and pasted by hand so they should be there with the exception of a couple redundant examples that appeared to be there in error. 

Coalesce - 0   <--local function no help needed
Connect-CrmOnline -   <-- Not sure why this is null, i verified help is working though 
New-CrmMoney - <-- Not sure why this is null, i verified help is working though 
UnzipCrmRibbon - 0  <--local function no help needed
VerifyCrmConnectionParam - 0      <--local function no help needed
Get-CrmConnection - 0           <--we don't provide the help for this 
Get-CrmOrganizations - 0       <--we don't provide the help for this 

The rest have 1 or more examples as expected.

**Comment by kenakamu** [comment]
The ones I noticed were:
Description of Upsert switch is gone.
Description of example 3 of Publish-CrmCustomization is gone.

So it seems like several descriptions are missing. I will add them back.
Do we use the codeplex tool to auto generate the help files?

**Comment by kenakamu** [comment]
Added missing description.
