### ISSUE TITLE
Rename functions for better usability

### ISSUE THREAD

**Issue by seanmcne** [seanmcne/Microsoft.Xrm.Data.PowerShell#82]
- Get-MyCrmUserId -> Either: Replace with Invoke-CrmWhoAmI, or Replace with something like Get-CrmCurrentUserId - so that it's clear the cmdlet is for CRM. 

- Add-CrmNoteToCrmRecord -> AddCrmNote (the object entityname and ID will be mandatory) 
- Add-CrmActivityToCrmRecord -> Add-CrmActivity (EntityName and ID will be an optional set)

**Comment by kenakamu** [comment]
I agree on Get-MyCrmUserId.
For Add-CrmNoteToCrmRecord and Add-CrmActivityToCrmRecord, I know name is too long but as intelisense will resolve it anyway and more precise, i want to keep it as it is. For Add-CrmActivity without parameter, i recommend to use New-CrmRecord if you don't associate with any other record.

Thoughts? I will add alias for Get-myCrmUserId anyway.
