### ISSUE TITLE
Get-CrmEntityAttributeMetadata always return null

### ISSUE THREAD

**Issue by henryhwang** [seanmcne/Microsoft.Xrm.Data.PowerShell#83]
There is a bug in Get-CrmEntityAttributeMetadata due to a typo, I think, which makes this function returning null always. See the code in following where the "-ne" should be "-eq".

    try
    {
        $result = $conn.GetEntityAttributeMetadataForAttribute($EntityLogicalName, $FieldLogicalName)
		if($result -ne $null)
        {
            return $conn.LastCrmException
        }
    }

**Comment by kenakamu** [comment]
so true. I will fix it now.
